### ISSUE TITLE
Optimize 'electronize start' faster

### ISSUE THREAD

**Issue by GregorBiswanger** [ElectronNET/Electron.NET#10]
Install npm packages only for one time.. possibly on 'electronize init'?!

**Comment by robertmuehsig** [comment]
"init" ist currently only used for the manifest file and "init" currently doesn't know anything about the target platform that we want to run and it doesn't know the obj/desktop folder construct, so... this would be not a good fit IMHO.

But: We can make the build and start command much smarter. In theory (with a bit of risk of course), if we detect the npm_modules folder, we may just skip npm install. 

At first I need to do this one: https://github.com/ElectronNET/Electron.NET/issues/7

The rest of the idea is discussed there.

**Comment by robertmuehsig** [comment]
Maybe not ideal, but if we detect the node_modules folder, we skip npm install... which speeds things up.
