### ISSUE TITLE
Get Url of window

### ISSUE THREAD

**Issue by ru-sh** [ElectronNET/Electron.NET#103]
Is it possible to get the url of a window?
I'm trying to detect if browser was redirected and find out where it was redirected.

**Comment by GregorBiswanger** [comment]
Hey @ru-sh,

use from the chrome dev tool the console and type:
`window.location.href`

Another way is to send you the information over the IPC... As example:

**Your HTML-View:**
`<script>  
    var { ipcRenderer } = require("electron");  
    ipcRenderer.send("currentUrl", window.location.href);  
</script>
`

**Your C# Part:**
`
public IActionResult Index()
{
    Electron.IpcMain.On("currentUrl", (url) =>
    {
        // Here you get the url from url parameter
    });
    return View();
}
`

I hope my answer helps you.
