### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cissemy** [ElectronNET/Electron.NET#104]
My application close when i run : dotnet electronize build win
![electron build](https://user-images.githubusercontent.com/87177/36551982-d38d5162-17c6-11e8-8b37-5e5c118100f3.PNG)
Thanks

**Comment by robertmuehsig** [comment]
Hi - with the most recent version we changed the Syntax. Please try: 

    dotnet electronize build /target win

**Comment by robertmuehsig** [comment]
This changes was needed to support other params as well. Please check https://github.com/ElectronNET/Electron.NET#build

**Comment by cissemy** [comment]
Thanks .
That works.
How can I create windows and Mac ?

**Comment by robertmuehsig** [comment]
Not in the same run - you need to invoke /target win and later /target osx  (etc.)

**Comment by robertmuehsig** [comment]
Be aware that the packager has some problems to package a application for OSX on Windows. It should be fine on Linux however.

**Comment by cissemy** [comment]
I understand .
I mean i want to create a setup file like setup.exe i could run and install my electron app

**Comment by robertmuehsig** [comment]
Good question - this is currently out of scope of this project. Maybe @GregorBiswanger can give some hints.

**Comment by robertmuehsig** [comment]
Is this issue for you solved?

**Comment by cissemy** [comment]
Yes.
Thanks

**Comment by cissemy** [comment]
Hi,
I have one last question .
How can i add a serial port based barcode scanner to my electron.Net app ?
Thanks

**Comment by robertmuehsig** [comment]
@GregorBiswanger Any ideas?

**Comment by cissemy** [comment]
If I can control serial com port from electron.Net  i do not need winform any for building desktop app.
Thanks

**Comment by robertmuehsig** [comment]
Well... you can use any .NET Core compatible NuGet package to communicate with the serial port. I don't see any electron.net issue here.

**Comment by cissemy** [comment]
Like what? 
Do you know any ?

**Comment by robertmuehsig** [comment]
Nope - sorry.
