### ISSUE TITLE
How to Achieve addDevToolsExtension？

### ISSUE THREAD

**Issue by PeachT** [ElectronNET/Electron.NET#105]
BrowserWindow.addDevToolsExtension();
method does not exist

**Comment by GregorBiswanger** [comment]
Use please:

`
var mainWindow = Electron.WindowManager.BrowserWindows.First();
mainWindow.WebContents.OpenDevTools();
`

**Comment by 4deeptech** [comment]
@GregorBiswanger According to the Electron docs there is a way to expose the ability to load a browser extension into the electron browser window via addDevToolsExtension referenced here:

https://electronjs.org/docs/tutorial/devtools-extension

@PeachT was referencing this to be able to load up a supported Dev Tool Extension.  Not opening the Dev Tools themselves.

Any way to expose that method to Electron.Net on the BrowserWindow?

**Comment by Daddoon** [comment]
@GregorBiswanger Maybe a little off topic, but do you have any plan to support to load WebExtensions through ElectronNET ? As it seem to be supported according to the official doc:

https://electronjs.org/docs/api/browser-window#browserwindowaddextensionpath

Thanks !
