### ISSUE TITLE
Hibernation problems

### ISSUE THREAD

**Issue by pardahlman** [ElectronNET/Electron.NET#106]
Hello, gang! I played around with my Electron.NET application and left it running over the night (after starting it with `dotnet electronize start`). When I came back to it the day after, and "woke up" my computer, I could see the application was still running. None of the windows where visible (expected), but I tried to open a window through the use of a hotkey binding and also through an item in the tray that I've added. Nothing happened, and I could see no new entries in the terminal from which I run the application. I didn't really know how to trouble shoot any further, so I just restarted the application and it started working. 

I'm wondering if this is a known issue or if there is anything I can do to make the application more resilient to hibernation.

Thanks!

**Comment by BrainSlugs83** [comment]
Can you share a simplified version of your project and reproduction steps?

**Comment by pardahlman** [comment]
Give me a few days to try to create a deterministic step-by-step guide. It has happened a few times, but always as a result of me leaving the computer for a large period of time.

**Comment by GregorBiswanger** [comment]
Hi @pardahlman 
What OS do you use?

A step-by-step guide would help us :)

**Comment by sommerschnee** [comment]
Hi there,
I ran into the same issue with my app on win10 & macOS. Same as @pardahlman reported. I installed a global ExceptionFilter in my app to log any exceptions in vain... 
It's more or less a polling client with a local tcp listener... What we can see is that the listener is still working in the background and receives messages. But there is no way to get the renderer process back.

**Comment by GregorBiswanger** [comment]
fixed in the new Electron.NET update 5.22.12.
