### ISSUE TITLE
dotnet electronize start

### ISSUE THREAD

**Issue by gesneriana** [ElectronNET/Electron.NET#109]
![91f8 9r5l9 3g yu nt_g](https://user-images.githubusercontent.com/19161353/37905903-fc230060-3132-11e8-898c-80f09032081f.png)

**Comment by GregorBiswanger** [comment]
Hi @gesneriana 
do you use all relevant setup steps?

1. UseElectron WebHostBuilder-Extension
2. dotnet electronize init
