### ISSUE TITLE
There is some chance 'ready-to-show' event is fired before ReadyToShow event is registered

### ISSUE THREAD

**Issue by jijiechen** [ElectronNET/Electron.NET#111]
Sometimes, the BrowserWindow's `ready-to-show` is fired before the ReadyToShow event handler of CSharp object is synced and registered onto the BrowserWindow JavaScript object. 
In this case, the ReadyToShow event handler will never be executed. 

In the following code, the browserWindow would never be shown:

```cs
var browserWindow = await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions
{
    Width = 1152,
    Height = 864,
    Show = false
});

browserWindow.SetTitle("MyApp");
browserWindow.OnReadyToShow += () => browserWindow.Show();
```

This case occurred randomly and especially more frequent on Windows systems.
It seems by adding some status caching in `BrowserWindow.js` and invoke the event handler immediately if the event handler is bound after the 'ready-to-show' has been triggered once, we can solve this problem.

**Comment by The-MAZZTer** [comment]
I can confirm this on 0.0.9 and 0.0.11. My window is configured to open on ReadyToShow and half the time nothing happens when I run my program.

**Comment by GregorBiswanger** [comment]
fixed in Electron.NET 5.22.12.

**Comment by LordKanelsnegle** [comment]
I'm still encountering this error while using 5.22.12

**Comment by schotime** [comment]
I"m still getting this on 5.22.13
