### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by ramin0011** [ElectronNET/Electron.NET#112]
When i start the app it loads defined menus in my code but after a moment ( usually a few seconds ) it will change to the defualt electron.net menu 
![image](https://user-images.githubusercontent.com/4890955/38172545-e2d43550-3562-11e8-8548-e9a17ec7323c.png)

i tryed to set the menu everywhere in the code  (in events: OnReadyToShow, OnShow , also before and after the events ) but it didnt help me

`          Electron.Menu.SetApplicationMenu(menuItems);
window.OnReadyToShow += () =>
            {
                window.Show();
                window.SetTitle("myapp");
                Electron.Menu.SetApplicationMenu(menuItems);
            };
            window.SetTitle("myapp");
            window.OnShow += () =>
            {
                window.SetTitle("myapp");
                Electron.Menu.SetApplicationMenu(menuItems);
            };
Electron.Menu.SetApplicationMenu(menuItems);`

**Comment by GregorBiswanger** [comment]
Hi @ramin0011 
set your own menu outside of the events please. 
The best way is after you create a window.

I think you get a exception from your defined menu call logic and electron switch to his own menu.
See in the console from the developer tools (Ctrl+I)

I hope my answer helps you.

**Comment by ramin0011** [comment]
i do not get any exception from developer console ...

**Comment by srameh** [comment]
@ramin0011 please try the solution in this page. It worked like a charm for me.
https://elanderson.net/2018/05/electron-net-custom-application-menus/
