### ISSUE TITLE
Cannot find Module 'detect-port'

### ISSUE THREAD

**Issue by svelluto** [ElectronNET/Electron.NET#113]
I just found this project (and Electron in general) and find it could be really great with a legacy application migration we're planning... and we're all .Net developers which makes this even better.

The trouble I have is I'm unable to run an executable on Windows.

I'm able to start the app through **dotnet electronize start**. that works just fine.
I'm using the command **dotnet electronize /target win** to generate the executable, and I get prompted with an error: "Cannot find module 'detect-port'". The error has an ok button, and when I click it nothing happens next. Also - the exe remains running which I didn't noticed until I had plenty running.

Thanks.

**Comment by rayhanhasnat** [comment]
run 'npm install' in YourProject > bin > desktop > YourProject.Host-win32-x64 > resources > app
That fixed the problem in my case but I'm looking for a better solution

**Comment by GregorBiswanger** [comment]
We use in the background the electron-packager.. and I got the same problem with native Electron..
I don´t know what is the best solution here.. we can try to execute "npm install" after the packaging.. but that is a workaround, and I dont think that is a good way..

**Comment by pookdeveloper** [comment]
Same problem here
