### ISSUE TITLE
First app always launching

### ISSUE THREAD

**Issue by Sushi21** [ElectronNET/Electron.NET#117]
Hi,

I tried to quick convert one of my personal application and now i want to run the demo.
Somehow whaveter i do it keeps launching the first app in electron.

I am in a completly another folder. I try to do the donet electronize init command and the start.
It keeps launching my first app.

It is caching or setting something somewhere that keep pointing to my first app?

Thanks

**Comment by GregorBiswanger** [comment]
Hi @Sushi21 

I´m not sure what you mean. The init command is only for the json manifest file.
Please list your steps.

**Comment by Sushi21** [comment]
steps:

Project 1
C:/project1
I ran command into that folder to launch project1 with electron.net

Few days later
Project 2 (demo)
C:/Project2 (demo)
I ran command into that folder to launch project 2 with electron.net

Result: Project 1 is showing all the time in electron instance even if i ran my commands into project 2 folder

Thanks

**Comment by EldinZenderink** [comment]
A bit late, but is the actual code for that project not being used or is it only the front-end? In that case, you have the same issue as mentioned here: https://github.com/ElectronNET/Electron.NET/issues/135

**Comment by GregorBiswanger** [comment]
Duplicate issue #135
