### ISSUE TITLE
Error in CLI dotnet electronize start

### ISSUE THREAD

**Issue by vbmanuel22** [ElectronNET/Electron.NET#120]
Hi, Can you please help me why I am encountering this error when i run dotnet electronize start. Please see attached file. Many thanks! 
![test23](https://user-images.githubusercontent.com/38751593/39296391-5f8e01ba-4973-11e8-9282-d90432fbe2c0.PNG)

**Comment by vbmanuel22** [comment]
After i cleared nugget cache and create a new test project. This is what I encounter when dotnet electronize start.

![image](https://user-images.githubusercontent.com/38751593/39351532-658f9c38-4a34-11e8-9f03-551f4f11c5fe.png)

**Comment by robertmuehsig** [comment]
Can you open a command prompt and enter "npm"? It seems it is not installed on your machine (see first screenshot "npm is not recognized")

**Comment by vbmanuel22** [comment]
Hi Robert,

This is what i get after doing what you said 'npm' is not recognized as an internal or external command,
operable program or batch file. How can I install it?

**Comment by robertmuehsig** [comment]
Nope - node.js is required and if you run on osx or linux you might need to install the electron packages manually (check readme).

**Comment by vbmanuel22** [comment]
Robert,

Seems like I'm having another issue with creating an installer for windows and mac. Based on this tutorial I followed https://www.youtube.com/watch?v=nuM6AojRFHk. I do not see any Electron.NET folder or something on my bin, same as when I tried to create for mac osx. Please see attached file. Many thanks.

![image](https://user-images.githubusercontent.com/38751593/39353492-711b8688-4a3a-11e8-9f6a-d7003531c4dc.png)
