### ISSUE TITLE
notification api seems does not work

### ISSUE THREAD

**Issue by WeihanLi** [ElectronNET/Electron.NET#121]
`Electron.Notification.Show(NotificationOptions notificationOptions)` seems does not work as expected.

how I use is as follows:

``` csharp
Electron.Notification.Show(new NotificationOptions("DbTool", "message"));
```

you may wanna view my project on [here](https://github.com/WeihanLi/DbTool/blob/dev/src/DbTool/Controllers/NotificationController.cs#L22)

**Comment by GregorBiswanger** [comment]
Unfortunately, it is a Electron bug with Windows 10:
https://github.com/electron/electron/issues/10864

You find workarounds in the comments.

**Comment by GregorBiswanger** [comment]
By the way, nice project 👍 :)
