### ISSUE TITLE
D:\ElectronNet\ElectronSample\ElectronSample>dotnet electronize init No executable found matching command "dotnet-electronize"

### ISSUE THREAD

**Issue by himansu-Bhusan93** [ElectronNET/Electron.NET#125]
I got the error after try dotnet electronize init, i followed each step as you mention in previous article ,but i don't get any solution till now. please give me any solution for it.

**Comment by R00iBaard** [comment]
Hey, did you remember to add the CLI? Add this to your csproj file then Init and start as per normal:

`<ItemGroup>
       <DotNetCliToolReference Include="ElectronNET.CLI" Version="*" />
</ItemGroup>`

**Comment by c4bo3l** [comment]
Hi, I got same problem here when trying the demo project.
I have tried CMD but still get same error.
In the csproj file, CLI has been added.

**Comment by ebuzyuma** [comment]
Hey, 
It also depends on the directory you are running init from.
It should be a project directory, not a solution directory!
That worked in my case.
