### ISSUE TITLE
Update to the latest Electron version (2.0.0)

### ISSUE THREAD

**Issue by R00iBaard** [ElectronNET/Electron.NET#126]
Hi there, is it possible to get if updating to version 2 is on the radar or not?
We are starting a project very soon that will make use of Electron.NET and very interested to start on the latest version at the beginning.

**Comment by GregorBiswanger** [comment]
Yes, our next big update supports the newest Electron version.
But not all API functions. As example in-app-purchase etc.

Every pull request is welcome :)
