### ISSUE TITLE
dotnet electronize build win giving error in vs 2017  asp.net core mvc

### ISSUE THREAD

**Issue by himansu-Bhusan93** [ElectronNET/Electron.NET#127]
Unhandled Exception: System.AggregateException: One or more errors occurred. (Th
e given key was not present in the dictionary.) ---> System.Collections.Generic.
KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ElectronNET.CLI.Commands.BuildCommand.<ExecuteAsync>b__13_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at ElectronNET.CLI.Program.Main(String[] args)

**Comment by WeihanLi** [comment]
Can you run `dotnet build` to see if there's a problem during `dotnet  build`?

**Comment by solidsloth** [comment]
I'm getting the same error. ``dotnet build`` does not return any errors for me. I can replicate by following the getting started and creating a new empty mvc app, installing dependencies, and trying to run ``electronize build``.

**Comment by twtyypmb** [comment]
@solidsloth  perhaps one dependency of dotnet did not install correctly,that is "vcredist_x64.exe for visual studio 2015"

**Comment by mgamache** [comment]
I am getting the same error 'dotnet build' has no errors, but I get the parent's  'Unhandled Exception' error when using 'dotnet electronize build'. Yes, vcredist_x64.exe for visual studio 2015 is installed.

**Comment by ernestotw85** [comment]
I added the keyword /target to this command and this minor change works fine for me.
 'dotnet electronize build /target win' 

That was the command that I executed, my current problem is that I would like to know where is located the .exe file to open the released solution

**Comment by mgamache** [comment]
actually I figured that out also from another thread. 
it seemed to generate an EXE for me on the following path:
`bin\desktop\ElectronNET.Host-win32-x64\ElectronNET.Host.exe`

**Comment by ernestotw85** [comment]
thank you @mgamache I am going to check this path in my current project
