### ISSUE TITLE
`dotnet electronize start` command throws errors when used asp.netcore2.1 with the angular

### ISSUE THREAD

**Issue by WeihanLi** [ElectronNET/Electron.NET#129]
`dotnet electronize start` command throws errors when used asp.netcore2.1 with the angular.
The error is as follows:
```
Error occurred during dotnet publish.
```
but when I run `dotnet publish`,there's no error.

My Environment:
- Asp.Net Core 2.1
- ElectronNET.CLI/ElectronNET.API 0.0.9

**Comment by WeihanLi** [comment]
When I use asp.net core2.0, it works great.
So I'm not sure whether it is a bug of asp.net core2.1 or asp.netcore2.1spa or Electron.NET bug

**Comment by WeihanLi** [comment]
It seems to be a bug of `ElectronNET.CLI`

**Comment by srameh** [comment]
I have a MVC site in Asp.Net Core 2.1 and when I run I get same error.
"Error occurred during dotnet publish."
Now even when I downgrade it to Core 2 I get the same error.
Is there a fix for this?
