### ISSUE TITLE
Credential manager

### ISSUE THREAD

**Issue by R00iBaard** [ElectronNET/Electron.NET#131]
Hey, is there a way to store credentials via an electron API of some kind?
Im just asking before I look at doing my own. 
The only thing I have found so far - https://github.com/atom/node-keytar

**Comment by JilkOwez** [comment]
I think it would be best to write your own credential manager with a hash of your choice.

**Comment by R00iBaard** [comment]
Yeah thanks man, ended up doing that. However we aren't using Electron.NET anymore, far from a production ready solution unfortunately.
