### ISSUE TITLE
how to use node module

### ISSUE THREAD

**Issue by leovictor** [ElectronNET/Electron.NET#133]
I'm trying to use a node module (iohook) but appears the message: Cannot find module 'iohook'. Is it possible to use node module with electron.net?

**Comment by GregorBiswanger** [comment]
Hello @leovictor 
how would you like to use your feature request?

Best, 
Gregor

**Comment by sachin-devitpl** [comment]
Hello Gregor,
What is the solution for this ? If I want to use iohook package to be added in my electronize build, then what should I do ?

Thanks in advance..

**Comment by GregorBiswanger** [comment]
Hi @sachin-devitpl 

the **HostHook API** allows you to execute your own JavaScript/TypeScript code on the host process.

Create first an ElectronHostHook directory via the Electron.NET CLI, with the following command: `electronize add hosthook`.

In this directory you can install any NPM packages and embed your own JavaScript/TypeScript code. It is also possible to respond to events from the host process.

You find the sample source code in ours Demo-App (ElectronNET.WebApp) `Controllers\HostHookController.cs` and in the `ElectronHostHook` folder.

Cheers,
Gregor
