### ISSUE TITLE
Is there a tool support for dotnetcore 2.1 global tools?

### ISSUE THREAD

**Issue by WeihanLi** [ElectronNET/Electron.NET#134]
accounding to  <https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#update-the-project-file-to-use-21-versions>, `DotNetCliToolReference` should be removed from netcore2.1 apps, is there a guide for migrate to .netcore2.1 app?

> Remove all references to <DotNetCliToolReference> elements for "Microsoft.AspNetCore", 
> "Microsoft.VisualStudio", and "Microsoft.EntityFrameworkCore" packages. These tools have been 
> replaced by global tools.

**Comment by robertmuehsig** [comment]
With the most recent version we switched to .NET Core Tools instead of the old way.
