### ISSUE TITLE
Publishing an app

### ISSUE THREAD

**Issue by kwakuduahc1** [ElectronNET/Electron.NET#137]
Hi. I am quite a newbie to electron and the accompanying tech. I wanted the script to use to publish a project. I have a project running and it tests alright but i cannot figure out how to publish an executable app that will run on a target machine. Thanks in advance

**Comment by GammaSoul** [comment]
cut and paste from the main page of this repository.....

> Build
> 
> Here you need the Electron.NET CLI too. Type following command in your ASP.NET Core folder:
> 
>     dotnet electronize build /target win
> 
> There are additional platforms available:
> 
>     dotnet electronize build /target win
>     dotnet electronize build /target osx
>     dotnet electronize build /target linux
> 
> Those three "default" targets will produce x64 packages for those platforms.
> 
> For certain NuGet packages or certain scenarios you may want to build a pure x86 application. To support those things you can define the desired .NET Core runtime, the electron platform and electron architecture like this:
> 
>     dotnet electronize build build /target custom win7-x86;win32 /electron-arch ia32 
> 
> The end result should be an electron app under your /bin/desktop folder.

**Comment by kwakuduahc1** [comment]
Checked it, it is not an app  per se. I am sure it has to be built or something but it is not executable. Ther app there is for debugging purposes and it would not be wise to push an app in debug mode downstream. It actually creates another app in the obj folder but once again, it requires some scripting to get that translating into an app.

**Comment by kwakuduahc1** [comment]
You were right @GammaSoul . I was misled by the final statement. It does create the executable. I was looking for an installer, which of course, is not there.
