### ISSUE TITLE
Create Window

### ISSUE THREAD

**Issue by kwakuduahc1** [ElectronNET/Electron.NET#144]
Hi guys, whenever i do a 
<code>
string path= "path to a controller action that renders a view";
await Electron.WindowManager.CreateWindowAsync(path)</code>, it creates the window alright but it is always empty.

2. Secondly, could it be possible to give an html to the create window to render?

Thanks

**Comment by GregorBiswanger** [comment]
@kwakuduahc1 you need the complete URL to your action.

As example to HomeController and FooBar action:
`string path = $"http://localhost:{BridgeSettings.WebPort}/Home/FooBar"`

**Comment by kwakuduahc1** [comment]
Thanks

**Comment by VerxivrEltaire** [comment]
> @kwakuduahc1 you need the complete URL to your action.
> 
> As example to HomeController and FooBar action:
> `string path = $"http://localhost:{BridgeSettings.WebPort}/Home/FooBar"`

Thanks for this reply, but what if i want to create a new window without localhost running? How can i achieve this
