### ISSUE TITLE
Crash when using Database

### ISSUE THREAD

**Issue by HurricanKai** [ElectronNET/Electron.NET#146]
Just recently started using this project, and after some testing i hoped to base a project on it.
thought, i now added a Db, using the normal DbContext - ensure create way.
but once it reaches EnsureCreated() it simply crashes:
(Attached, too large)

starting it as a normal application, meaning with `dotnet run` just runs the webserver fine.
using `dotnet electronize start` thought causes this error.
[Error.txt](https://github.com/ElectronNET/Electron.NET/files/2103153/new.9.txt)
sorry for my bad english, woud be great if someone is able to understand why it doest load.
(seems to have something to do with a module called e_sqlite3 but none of the stuff i coud find anywhere else helped.

**Comment by pargsoft** [comment]
I had the same problem. I fixed it by adding the nuget package Microsoft.Data.Sqlite. This comes with the correct DLLs for publishing.

**Comment by kwakuduahc1** [comment]
While you are at it, add efcore.sqlite to it( <code>Install-Package Microsoft.EntityFrameworkCore.Sqlite</code> NuGet package)
