### ISSUE TITLE
SetMenu error, menuItems are undefined....

### ISSUE THREAD

**Issue by nvrnight** [ElectronNET/Electron.NET#148]
Getting an error trying to set the menu items. menuItems is undefined in browserWindows.js when executing.

window.SetMenu(new[] {
					new MenuItem()
					{
						Role = MenuRole.reload
					}
				});

**Comment by GregorBiswanger** [comment]
Hello @nvrnight 
Use **Electron.Menu.SetApplicationMenu**.

See on our example:
https://github.com/ElectronNET/electron.net-api-demos/blob/master/ElectronNET-API-Demos/Controllers/MenusController.cs

Best,
Gregor
