### ISSUE TITLE
cli module not found

### ISSUE THREAD

**Issue by hard-rox** [ElectronNET/Electron.NET#149]
My .csproj file contents are these.

![image](https://user-images.githubusercontent.com/20935652/42055336-a7cc8748-7b38-11e8-868f-a4b3206e70fd.png)
But when I enter this command-
`dotnet electronize start`
Then I got this error. What is the solution?
![image](https://user-images.githubusercontent.com/20935652/42055495-23960d4a-7b39-11e8-8b1f-49751ea01d57.png)

**Comment by GregorBiswanger** [comment]
Hi @hard-rox 

do you have installed Node.js (8.x or upper)?
do you execute this command in "E:\Projects\ElectronApp\ElectronApp"?
