### ISSUE TITLE
jQuery not loading

### ISSUE THREAD

**Issue by kwakuduahc1** [ElectronNET/Electron.NET#150]
I have tried every trick I know off to load jquery but for some strange reasons, it does not get loaded. When i publish the app with visual studio publish tool however, the jquery works seamlessly. I would be glad if that can be investigated. Thanks in advance

**Comment by EldinZenderink** [comment]
https://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined (hat the same issue here)
