### ISSUE TITLE
Package Size and Optimization  

### ISSUE THREAD

**Issue by srameh** [ElectronNET/Electron.NET#157]
I have successfully built an application using MVC Core 2 and SQLite. After running the BUILD command I noticed the following issues:
- The size of the build folder is 360MB. This is huge for simple MVC app.
- The app launch time is very slow. It takes about 20-30 seconds before you see the window.
- The Application name defaults to **ElectronNET.Host**.  This value is coming from package.json  which is generated by the Electron.net. 

- The App icon defaults to Electron icon. Passing new icon path as part of the build command parameter did not help.
How can I include my own package.json file so it does not take the name **ElectronNET.Host**?
How can I reduce the size of the application and fix the above issues?

**Comment by EldinZenderink** [comment]
For windows: #153 

Linux still has issues. 

For getting smaller sizes I am currently trying to package the damn thing manually for distribution, if I use electron-builder for windows my installer sits around 65 ish MB. 

I am currently trying to bypass the build command for electronnet by doing the following:

Build the application once using the command `dotnet electronize start`

Then, there should be an directory within obj/Host containing just the electron application (folder contains main.js)

Edit the package.json and change the name and version(in my case).

then within that directory I run 'electron-builder build'.

A dist directory appears in that directory with an (nsis) installer of about 65mb. Which works.
Though, extracted/installed, the directory is again around 230mb. 

Currently trying to get a linux build going on (AppImage fails without giving an explanatory error, deb file gives some package.json error, such as author name and emailaddress + homepage, etc. All required by a deb file. Some customization for the package.json file would be helpfull, like some kind of property file for custom package.json parameters so when the package.json file is being generated the values from the property file are added and or replaced within the package.json file.

**Comment by srameh** [comment]
@EldinZenderink  Thank you SO MUCH! 
Please share the batch file and the package.json if you don't mind.

**Comment by EldinZenderink** [comment]
Its ugly AF (my first try at writing an actual batch script ;) ) but here it is: 

[custombuildelectronnet.zip](https://github.com/ElectronNET/Electron.NET/files/2270322/custombuildelectronnet.zip)

Just put these files in your root project folder. For help, type ./build.bat help

Just replace the values within package.json & electron-builder.json to the values you want (highly recommend to use the wiki of electron-builder, you can leave the linux target in there even if you dont want linux, if you specify that you only want to build windows (see the help) it will ignore the linux target. 

Hope it helps.

*Btw linux packaged deb files are not working in my case, it's giving me an anoying ENOENT for both AppImage and deb files and neither Icons are visible, so, or my script is doing something weird, or the target setup is wrong, I will keep experimenting. 

*Oh and you do need to in stall electron-builder globally! `npm install electron-builder -g` before using this script!

**Comment by srameh** [comment]
You are awesome! Thank you again.

**Comment by EldinZenderink** [comment]
BTW, I made a stupid mistake, depending on which os you want to build, you need to run the `dotnet electronize build /target linux ` for linux, and use the generated files within `/obj/desktop/linux` for the build directory. That one will install and run just fine on linux. (The one in Host does work on windows).

**Comment by srameh** [comment]
@EldinZenderink:
So I came across this post. I needed to optimize my build.  I a am not sure if this is going to help you.
https://stackoverflow.com/questions/45984273/chained-msi-installer-with-electron/46474978#46474978

**Comment by EldinZenderink** [comment]
@srameh 
I'm fine with using the default nsil installer, I honestly think it wont get much smaller than 60mb ish, but just for curiosity sake: is there much of a difference using wix?

**Comment by srameh** [comment]
@EldinZenderink:
I have been able to successfully generate a build with WiX yet.

**Comment by EldinZenderink** [comment]
@RogerDodger123 

As mentioned in my post above, you can't use the Host directory most of the time. (Mine for some reason did work when using the Host directory, but only for the platform that I build upon, but that might just have been a stroke of not helpfull luck). So when performing the 'dotnet electronize build command' you need to use the `/obj/desktop/win` (or windows not sure not at home right now) directory instead of the host one. If that doesn't work, then I am not really sure what is going on. Did you modify the build-electron.json file? If so, did you enable asar? For some reason when I do that, I have ENOENT errors appearing as well.

Also when installing to the Program Files directory, you might need to run it with admin rights, depending on what your back-end does. 

I do need to mention that in the end I gave up on getting it to work  (icon issues and all that as well) with ElectronNET. ElectronNET is cool, especially if you need to use the API from electron directly from the back-end, but I didn't need that. 

In my case I manually created a electron project, added a directory for my .net core back-end and interface, moved my back-end to that directory after publishing it (creating an executable). Then I just initiate a child process within main.js (nodejs stuff) from electron. For my interface, since my interface is a standalone single page (typescript/angular 5) webpage I just directly load it in. (Or you could load the url of your back-end if that is what you desire). And it works fine. I then can just use electron-builder to package it without any issue (you need to replace the back-end stuff when compiling for a different platform such as linux with a published backed with target linux).

**Comment by RogerDodger123** [comment]
@EldinZenderink 

Oh sorry I missed that. I have also tried to do this by performing the build command and trying to use your scripts in the following location `/bin/desktop/win` where the build places the files. I have also tried it in the location where the build makes the exe when using the command `dotnet electronize build /target win`. So this location I tried was `APPNAME\bin\desktop\ElectronNET.Host-win32-x64\resources\app`. I tried using your exact electron build file and package json in the zip file to see if i could get it to work.

From what I have seen online I have also been running `electron-builder build` so it performs a build based on the host os and the name from the package.json file. The only this I have changed was removing a depencecy that was in the package.json file. Electron-build doesn't like electron dependency being the dependency section only in devDependencies of the package.json

**Comment by RogerDodger123** [comment]
This is the error I receive:
Error: spawn ENOENT
at exports._errnoException (util.js:1050:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:367:16)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by EldinZenderink** [comment]
@RogerDodger123  spawn error generally means that there is an issues "spawning" the process runing your .net core application. Again, did you try using the /obj directory? Another thin you can try and can do is the following: go to the installation directory, try to find the location of the main.js file (dont know it out of my head) (and make sure you asar disabled before packaging the installer), install electron globally, and then run  through cmd: `electron .` in the installation directory, maybe it will give more information about the error then.

**Comment by EldinZenderink** [comment]
Oh btw, my bad, in the electron builder json file i didnt add the `"asar":false`,  key value, try to add it underneath "productName":"CustomTitle", key value pair. (so within the top level object).

**Comment by RogerDodger123** [comment]
I have just tried to use your bat file to create the installer from the obj directory but I am getting errors from the electron-builder process

**Comment by RogerDodger123** [comment]
@EldinZenderink 
I have managed to get it to run from an installer turning off asar!!!!
Any ideas why it doesnt work unless asar is disabled?

**Comment by RogerDodger123** [comment]
I have looked into this abit more and went through electron packaging doc. 
It comes down to the fact that `child_process.spawn` does not support executing binaries inside an asar file where as `child_porcess.execFile` would perform this for you.

I have got it working now by unpacking the .exe like suggested in your post and making a slight change to the main.js to counter for the different file location. 

Thanks for your help

**Comment by EldinZenderink** [comment]
No problem, glad to be of help.

**Comment by RogerDodger123** [comment]
Something I have realised... after performing `dotnet electronize build /target win` and running the app it creates in the `bin\desktop` folder does the menu bar still appear for you. For me it does not. It only appears when running `dotnet electronize start`

This is without making any changes to files to do with the asar issue I was having.

**Comment by RogerDodger123** [comment]
That make sense!!! Thanks again.

**Comment by GregorBiswanger** [comment]
@robertmuehsig can you do that for the CLI?

**Comment by cRUSHER-HLG** [comment]
This would be very nice if we can compress the sizes more. In this fact we also need less time to load the programs. If you compare javascript electron implementation it needs for a empty running programm only 80mb of ram but Electron.Net for exactly the same needs 240-255mb Ram.

**Comment by GregorBiswanger** [comment]
We have been switching to electron builder since version 5.22.12. That creates an extremely compact version. At a startup performance will continue to be intensified.
