### ISSUE TITLE
SSL content all fails to load in windows with error "net::ERR_SSL_PROTOCOL_ERROR"

### ISSUE THREAD

**Issue by HirenPatelhv** [ElectronNET/Electron.NET#158]
Hi Team ,I have facing an issue with **SSL** protocol,when i make API call via ajax it give an error  "**net::ERR_SSL_PROTOCOL_ERROR**",please help me for solve this issue.

![ssl](https://user-images.githubusercontent.com/30865775/43756364-e8ec3120-9a31-11e8-888d-a9f03bc439bd.png)

**Comment by HirenPatelhv** [comment]
I have solve this error.

**Comment by tytech3** [comment]
@HirenPatelhv would you mind sharing how you solved it? I'm getting the same thing.
