### ISSUE TITLE
Help diagnose package.json not picked up

### ISSUE THREAD

**Issue by MartinKuhne** [ElectronNET/Electron.NET#161]
I have a VS project on 0.0.9. The file structure is \source\solutiondir\projectdir and the projectdir has both the client and API, as well as a package.json

My goal is to set 'build' properties as per https://github.com/electron-userland/electron-builder
In particular, I need to add a license file to be distributed with the project (using the extraFiles property)

I tried
```
  "build": {
    "artifactName": "beer.exe",
```

That wasn't picked up either

I ran procmon and I can see that package.json is being read.

I think I am on the wrong track here. What is the expected behaviour?

Thanks, Martin

**Comment by robertmuehsig** [comment]
I think this is still on the ToDo list :-/ When I remember correctly we only invoke the electron builder via the command line and unfortunatly don't support the build file, See this line in the CLI project: https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.CLI/Commands/BuildCommand.cs#L135

**Comment by MartinKuhne** [comment]
Thanks for the quick reply. I tried a CopyFile msbuild task, however it seems it clears out any existing files in the target folder, so that won't work. Finally, added a step on bamboo to add my license file
