### ISSUE TITLE
Create an experimental demo with Ooui.Forms

### ISSUE THREAD

**Issue by FWJay** [ElectronNET/Electron.NET#164]
Is it possible to create a simple starter demo using Frank Kruger's excellent Ooui.Forms for us non web developers so that we can start developing desktop apps using Xamarin Forms UI markup? it'll help us carry the platform forward.

**Comment by GregorBiswanger** [comment]
Hello @FWJay 
I don´t know. You can try it with Blazor.
That should work.

Best,
Gregor
