### ISSUE TITLE
Serial port access over .Net

### ISSUE THREAD

**Issue by Franki1986** [ElectronNET/Electron.NET#166]
Hello,

is it possible to create a serial port connection over .Net, e.g with the 'ElectronNET.API.Entities'?

**Comment by GregorBiswanger** [comment]
Hello @Franki1986 

Yes, you can 👍 

Use the .NET Core 2 Library System.IO:
https://docs.microsoft.com/en-us/dotnet/api/?term=serialport&view=netcore-2.0

Best,
Gregor

**Comment by renanosoriorosa** [comment]
@Franki1986 Were you able to communicate with the serial port? if so, share with me?
