### ISSUE TITLE
Old Version of node.dll in the Output dir

### ISSUE THREAD

**Issue by LukasSlizik** [ElectronNET/Electron.NET#168]
Hi,

executing **dotnet electronize build /target win** creates an output directory with all the necessary win files. Among them node.dll in the version **7.9.0.0**. 

Starting ElectronNET.Host.exe works fine on a machine with pre-installed Node.js.
But after de-installing Node.js and starting ElectronNET.Host.exe once again, the electron window starts only to show me the following Error:

An error occurred while processing your request.
Request ID: 0HLH563TG4VCE:00000001

Other Electron Applications that come with newer version of node.dll work fine even on machines without Node.js, so my assumption here is that the problem might be in the old version of node.dll. 

my node version:
node --version -> v8.12.0

How do I get **dotnet electronize build /target win** to use newer version of node.dll in the output directory ? Am I missing something ?
Thanks.

regards 
Lukas

**Comment by GregorBiswanger** [comment]
Hi Lukas,
each Electron version has its own Node.js version whatever is installed as a large version on the host.

**Here the information about the Node versions in Electron versions:**
https://github.com/electron/node

**Here a documentation from the native Electron:**
https://electronjs.org/docs/development/upgrading-node

Could I help you with my answer?

Best,
Gregor
