### ISSUE TITLE
Can`t include pepflashplayer.dll

### ISSUE THREAD

**Issue by rid-32** [ElectronNET/Electron.NET#170]
Hello! We try to include this plugin pepflashplayer.dll using this command:
"Electron.App.CommandLineAppendSwitch("ppapi-flash-path", pathToPlugin)"

But nothing happens. Without errors in console.
We see this message: "This content requires the latest version of Adobe Flash Player. Download for free Flash Player now "

**Comment by GregorBiswanger** [comment]
Hi @rid-32,
Electron.NET based on the native Electron. Electron is a combination of Node.js and Chromium.
Chromium stopped the support of Adobe Flash Player.

Sorry, that will not work.
