### ISSUE TITLE
User Interface issue when running the via Electron.NET.

### ISSUE THREAD

**Issue by vbmanuel22** [ElectronNET/Electron.NET#171]
Hi,

We are having some UI issues when running the electron.net app. When we run it via browser the UI is fine but when it's on the electron its messed up. Please see attached screenshots.
![web view](https://user-images.githubusercontent.com/38751593/46770950-07e89580-cd24-11e8-95c6-f23b57b9a6f4.PNG)

![electron view](https://user-images.githubusercontent.com/38751593/46759603-61d86380-cd02-11e8-8255-f8ef1e96c458.PNG)

![webview 1](https://user-images.githubusercontent.com/38751593/46759912-1a9ea280-cd03-11e8-88ee-336164942e52.PNG)
![electron view1](https://user-images.githubusercontent.com/38751593/46759916-1d00fc80-cd03-11e8-8d08-e550bcb06379.PNG)

Thank you.

**Comment by RogerDodger123** [comment]
Are you able post any code? It just looks like styling issues

**Comment by vbmanuel22** [comment]
Hi Roger,

Not sure if it is a styling issues as the ui is ok when run it via browser.

Please see attached files.
[Login.zip](https://github.com/ElectronNET/Electron.NET/files/2474080/Login.zip)

**Comment by abuassar** [comment]
this might be cause by Node.js integration of Electron,
to over come this issue try the following:


    
    
    <script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>

    
    <script src="scripts/jquery.min.js"></script>    
    <script src="scripts/vendor.js"></script>    

    
    <script>if (window.module) module = window.module;</script>

more on this issue:
https://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined

**Comment by vbmanuel22** [comment]
Hi Abuassar,

Thank you for sharing the link but the issue still persist after inserting the above code. One thing I noticed is that we do not have the vendor.js file. Do we really need that file?

Thank you.

**Comment by vbmanuel22** [comment]
Btw, here's the error on the browser console, hope it will help. 
![console error](https://user-images.githubusercontent.com/38751593/46970409-93c73c80-d0eb-11e8-9243-6a0c139552c2.PNG)

**Comment by abuassar** [comment]
@vbmanuel22 it seams that you didn't interpret my reply well

this section in my reply is just an example, read the comment it says "**your normal script imports etc**" :

    
    <script src="scripts/jquery.min.js"></script>    
    <script src="scripts/vendor.js"></script>

**Comment by vbmanuel22** [comment]
Hi @abuassar,

Thanks for the clarification, but sadly the issue still persist.

**Comment by abuassar** [comment]
@vbmanuel22 sorry it didn't work for you, I had the exact same error as yours (jquery is not defined), and I fixed it using the solution the I gave you, try reading the stackoverflow thread I posted above as it has more solutions.

**Comment by GregorBiswanger** [comment]
@vbmanuel22 Is the lib directory in the wwwroot?

Compare your solution with the Electron.NET API Samples App please (wwwroot and home view file):
https://github.com/ElectronNET/electron.net-api-demos
