### ISSUE TITLE
electron version

### ISSUE THREAD

**Issue by RogerDodger123** [ElectronNET/Electron.NET#172]
The version of electron that is used to start and build the app is very old. I think its 1.7.2. Will it be updated to a new version of electron.

thank

**Comment by svernyi** [comment]
According to the Package.json it's using Electron 3.0, which is very recent.

`  "dependencies": {
    "detect-port": "^1.2.3",
    "electron": "^3.0.0",
    "socket.io": "^2.1.1"
},`

Unless I'm missing something.

**Comment by robertmuehsig** [comment]
The current NuGet release should include the electron 3.0 release.

Checkout:
https://www.nuget.org/packages/ElectronNET.API/0.0.10 & https://www.nuget.org/packages/ElectronNET.CLI/0.0.10
