### ISSUE TITLE
Publish / installer / auto update guidance?

### ISSUE THREAD

**Issue by thnk2wn** [ElectronNET/Electron.NET#175]
Any documentation or guidance on distributing apps created with Electron.NET? I see the build output but would like installers for Windows and Mac and auto update. Can Electron Builder be used or is there something different that needs to be done? It'd be great to have that info in the README or Wiki as that's a big missing gap to me.

**Comment by Khaoz-Topsy** [comment]
I would also like to see some publish/installer/auto update guidance 😀

**Comment by kwakuduahc1** [comment]
To create an installer is a bit tricky. The shortest way for me is to rather package the ../obj/desktop/win7-x86 folder with electron-packager if you build for win32. It is easier changing the name of the application, setting the icon and providing other useful information. 

While i have not tried that, it should be easier to set the update features from there

**Comment by GregorBiswanger** [comment]
Available with the next Electron.NET update.

**Comment by LapinskasL** [comment]
@GregorBiswanger, I see you closed this as completed but I can't find docs on how to create the installer. Where can I find this?
