### ISSUE TITLE
Code Sercurity

### ISSUE THREAD

**Issue by cRUSHER-HLG** [ElectronNET/Electron.NET#177]
Hello, 

I want to ask how we can secure our code that is finally generated by the Electron.CLI build is made? For C# it would help a bit to work with obfuscation/encoding. My first check was with IL-Spy that says that this is an unmanaged assembly. 
At addion how we can clean the build up? The folder structure looks a bit strange and messy. 

Good Regards,
cRUSHER

**Comment by samdubey** [comment]
Have you found answer to code security question?

**Comment by anaether** [comment]
Hi @samdubey not really. When i found a way i will update this ticket.

**Comment by srameh** [comment]
I am looking for a similar solution. Have you guys found a fix for this?
