### ISSUE TITLE
(Feature) Folders

### ISSUE THREAD

**Issue by cRUSHER-HLG** [ElectronNET/Electron.NET#179]
Hallo, 

Zu erst muss ich wirklich sagen, dass mir eure Arbeit sehr gut gefällt und ein Lob für eure Mühen aussprechen. Ich habe dennoch Ideen, wie wir zusammen dieses Projekt noch weiter verbessern können. Die Idee ist ein noch einheitlichere Ordner Struktur zu gestalten. 

Die aktuelle Situation sieht ja so aus (Windows build):
![dekstop](https://user-images.githubusercontent.com/35463368/47601802-0ed6ff80-d9d6-11e8-9bdc-d96166d6f01d.JPG)

So könnte es z.B. dannach aussehen (Windows build):
![dannach](https://user-images.githubusercontent.com/35463368/47601891-12b75180-d9d7-11e8-8c55-50a9c3d8a57a.JPG)

Der Grund:
Für Kunden wirkt solch ein installiertes Programm dann nicht alzu professionell und sie gehen dann schon meistens mit einer schlechten Meinung/Haltung in die "Interaktion" mit dem Programm.

Die Idee an sich beschrieben ist das .dll files oder .so files in einen libraries Ordner wandern und resource Dateien wie .pak und .dat in einen Ordner data landen. Sowohl die .bin dateien sollen in einen Ordner namens bin. 

Ich habe jetzt versucht mir einen Überlick zu verschaffen, wie man das handhaben kann. Wenn ich es richtig sehe nutzt die Electron.NET CLI ja nur einen Befehl der mittels der JavaScript implementierten Electron Version dann letzlich compiliert wird. Falls ich es falsch verstanden habe, dann würde ich euch bitten mich da klarzustellen. Das würde dann ja heißen, das man selbst am Original Electron hand anlegen müsste um dieses feature so zu erhalten. Gibt es denn die Möglichkeit dies auch per CommandLine zu bestimmen, dann wäre die Implementierung für diese Idee sehr einfach.

Falls ihr noch Fragen an mich haben solltet, dann bin ich gerne Bereit euch diese zu beantworten, falls ihr etwas an meiner Fragestellung oder Problem-/Optimierungsbeschreibung nicht verstanden habt oder anderes.

MfG,
Andi

**Comment by GregorBiswanger** [comment]
Hallo @cRUSHER-HLG,

wir verwenden das native electron-builder Tool zum Erzeugen der Electron Binaries.
Leider erzeugt dieses die Dateien und wir haben kaum Einfluss darauf.

Eventuell findest du dazu eine Lösung im Netz? Am liebsten wäre ja nur eine Binary-Datei und das nur gewünschte Ressourcen allein stehend untergebracht werden.

Wir sind auf jede Unterstützung angewiesen.
@robertmuehsig und ich sind beide Eltern mit wenig Zeit.

Beste Grüße,
Gregor

**Comment by GregorBiswanger** [comment]
We search a solution for the builded binary files. 

We use electron-packager and that creates a lot of files.

**Comment by GregorBiswanger** [comment]
The new Electron.NET update 5.22.12 used electron-builder with clickonce support now.
