### ISSUE TITLE
CLI: Include electron-builder configuration over the electron.manifest.json

### ISSUE THREAD

**Issue by GregorBiswanger** [ElectronNET/Electron.NET#18]
The electron-builder supports a build configuration through the package.json.
We need to inlcude a default configuration in the electron.manifest.json, that based on the electron-builder build configuration.

Maybe we can include an assets folder with sample images? ("electronize init").

Information about the electron-builder configuration:
https://github.com/electron-userland/electron-builder/blob/master/docs/configuration/configuration.md

http://electron.rocks/electron-builder-explained/

**Comment by robertmuehsig** [comment]
Could you share a sample configuration? I'm not sure how to apply those config values :/

**Comment by GregorBiswanger** [comment]
`
 "build": {    
   "appId": "com.jamzi.quickstart",  
   "win": {  
     "target": "nsis",  
     "icon": "build/icon.ico"  
   }  
}  
`

See here too:
https://medium.com/@jamzi/building-desktop-applications-with-electron-electron-builder-47484193cbcc

**Comment by robertmuehsig** [comment]
What is "nsis"? Can we use this to configure App Title names / icons for the different platforms?

**Comment by GregorBiswanger** [comment]
Good question. I don't know...

**Comment by yoDon** [comment]
Is this the right place to ask about how to add additional assets/resources to the build process? 

I ran into the need for additional assets/resources as kind of a blocker while working on the [Electron.NET-React-Typescript-MobX boilerplate] as described [here](https://github.com/yoDon/Electron.NET-React-Typescript-MobX/#hack-hack-hack-begin).

**Comment by DrSensor** [comment]
> I +1 for supporting `electron-builder` because it has more features (e.g injecting auto-updater and etc) than `electron-packager`
One of use case that I need `electron-builder` is to package my app into [snap](https://snapcraft.io) then deploy it to arm device for kiosk app.

**Comment by robertmuehsig** [comment]
Electron-builder is a more advanced electron packer? (my electron knowledge is pretty low :/)

**Comment by DrSensor** [comment]
My opinion is biased because previously I build desktop app with [electron-vue](https://github.com/SimulatedGREG/electron-vue) and I need some features of electron-builder have (mainly packaging for many linux distros and CI support). Maybe this short [section doc](https://simulatedgreg.gitbooks.io/electron-vue/content/en/building_your_app.html) can explain better.

**Comment by robertmuehsig** [comment]
We released a new version and now support addional params from electron-packager, e.g. we can now execute something like this:
build /target custom win7-x86;win32 /dotnet-configuration Debug /electron-arch ia32  /electron-params "--prune=true "

Via the /electron-params a user can just tunnel the desired commands directly to the electron-packager.

Please give feedback to this feature. I'm not sure if this will solve any problem, but maybe this is a start :)

**Comment by DrSensor** [comment]
Would you reference which commit or PR for that feature?
