### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by Lynchy703** [ElectronNET/Electron.NET#185]
Can someone update the NuGet package? This is missing some features that I'm trying to use even though it's merged into the same version here and NuGet supposedly has. Don't think NuGet has been updated since april.

**Comment by robertmuehsig** [comment]
https://www.nuget.org/packages/ElectronNET.API/0.0.10 & https://www.nuget.org/packages/ElectronNET.CLI/0.0.10 should be out in some minutes.

Sorry for the late response. Hope this fixes some issues :)
