### ISSUE TITLE
No executable found matching command "dotnet-electronize"

### ISSUE THREAD

**Issue by paillave** [ElectronNET/Electron.NET#189]
- open dos command prompt
- `dotnet add package ElectronNET.API`
- `dotnet tool install ElectronNET.CLI -g`
```
You can invoke the tool using the following command: electronize
Tool 'electronnet.cli' (version '0.0.10') was successfully installed.
```

- `dotnet tool list -g`
```
Package Id            Version      Commands
----------------------------------------------
electronnet.cli       0.0.10       electronize

```
- `dotnet electronize`
```
No executable found matching command "dotnet-electronize"
```
- `electronize`
```
Electron.NET Tools (0.0.10)
Project Home: https://github.com/ElectronNET/Electron.NET
etc...
```

Is there anything wrong with what I did for electronize tool not working with dotnet command?

**Comment by golyakho** [comment]
Try call it without dotnet key,
Or modify launchSettings.json
 ```json
"Electron App": {
      "commandName": "Executable",
      "executablePath": "C:\\Users\\<user name>\\.dotnet\\tools\\electronize.exe",
      "commandLineArgs": "start <path to core app>"
    }

Works for me

**Comment by ruohki** [comment]
solution:

C:\Users\<username>\.dotnet\tools and rename or clone the electronize.exe to be called dotnet-electronize.exe

```
PS C:\Users\ruohk> dotnet electronize
Keine ausführbare Datei zum Befehl "dotnet-electronize" gefunden.
PS C:\Users\ruohk> dotnet electronize
Electron.NET Tools (0.0.10)
Project Home: https://github.com/ElectronNET/Electron.NET


Commands to start the Electron Application:

        start                   Start your ASP.NET Core Application with Electron, without package it as a single exe. Faster for development.

Commands to build the Electron Application:

        build                   Build your Electron Application.

Commands to init the Electron Application:

        init                    Creates the needed Electron.NET config for your Electron Application.

Commands to see the current ElectronNET version number:

        version                 Displays the ElectronNET.CLI version


To get help on individual commands execute:
        dotnet electronize help <command>
```

**Comment by paillave** [comment]
@golyakho , @ruohki I already had the work around as I mentioned on the post. But still, I opened an issue for the pb to be solved at the next release so that either we can make a `dotnet electronize` by following what the document mentions, or so that the documentation can be updated. Anyway, the goal is that the behavior matches what is in the documentation :).

**Comment by robertmuehsig** [comment]
Ah - sorry for this misunderstanding. With the most recent version it is just "electronize". "dotnet electronize" was needed in the pre-tools .NET Core age.

Maybe checkout the PR #192 

I hope this change will clear some questions.

**Comment by robertmuehsig** [comment]
The PR is merged - please let me know if you would like further changes.

**Comment by paillave** [comment]
Thanks a lot @robertmuehsig , actually having the issue #188 solved would be good as it is an almost blocking bug to build any package on a fresh project. Very easy solution as I mentioned in my analysis: https://github.com/ElectronNET/Electron.NET/issues/188#issuecomment-449859346
