### ISSUE TITLE
How to navigate in C#?

### ISSUE THREAD

**Issue by Symbai** [ElectronNET/Electron.NET#196]
How can I load a different view within C#? The documentation and all samples only contain javascript code. The file secondView.cshtml is in the same folder as index.cshtml is.
```
var mainWindow = Electron.WindowManager.BrowserWindows.First();
mainWindow.LoadURL("file://${__dirname}/secondView.html");
```

**Comment by robertmuehsig** [comment]
You boot up a complete ASP.NET Core Application - so you just can "navigate" via typical links or redirects. 
When your mainWindow has an open "index.cshtml" just put a link inside it and point to the secondView.html. 
The negative point here is, that this will "re-render" the view (just like in a normal web browser)..

Hope this helps!

**Comment by Symbai** [comment]
But I don't want to navigate within the app via buttons or links. Instead within C# from the controller.

**Comment by robertmuehsig** [comment]
Well - you could just redirect the browser to the target view. This would be the "normal" behavior. I'm not sure if there are other options available.

**Comment by Symbai** [comment]
That sounds fine but how would do that? How can I tell the browser to visit secondView.cshtml from C# controller? That's where I'm stuck.

**Comment by robertmuehsig** [comment]
Like this: https://stackoverflow.com/questions/45830460/how-to-redirect-to-a-asp-net-core-razor-page-no-routes

Or just google "ASP.NET Core Redirect"
