### ISSUE TITLE
Bugs and Performance in Demo App 

### ISSUE THREAD

**Issue by Sekkei** [ElectronNET/Electron.NET#202]
The Windows notification doesn't work (*edit I see there is already a report about this)

Open a path in file manger (I have QTTabs installed) > opens a new tab in explorer as it should be but freezes the demo for like 15sec than open a new seperated window with the same path > demo unfreezes but open a path doesn't work anymore 
(Open paths with VSCode does works)

Also the demo app needs 10sec to start, this is way to slow, is this normal at this state in development, or is there also something wrong, and which performance improvment could we expect in the future? [#1476](https://github.com/AvaloniaUI/Avalonia/issues/1476#issuecomment-381410232)

Adding a Splashscreen for "booting" the demo app would give a better first impression (like very big projects like photoshop, even if this demo app is more or less small in comparison)

Also I would like to know if this chart is right: [Image](https://i.ibb.co/0KdmwFw/c-Flow-chain2.png)

**Comment by GregorBiswanger** [comment]
Hi @Sekkei,

This is a known bug with Electron with Windows 10: https://github.com/electron/electron/issues/10864

I will try to build the workaround into the API.

Best,
Gregor

**Comment by GregorBiswanger** [comment]
We implemented a splashscreen support and optimized a little bit the performance on release build.
