### ISSUE TITLE
Convert ElectronJS to C# instead of using Node.js

### ISSUE THREAD

**Issue by Sekkei** [ElectronNET/Electron.NET#203]
Would have some benefits; but would it work flawless and with good performance?
Thinking of something like Widgetoko reversed; Convert ElectronJS before compiling
Replace and convert Node.JS API and V8 with .Net

**Comment by GregorBiswanger** [comment]
Hi @Sekkei,
the native implementation of the APIs for Chromium with .NET Core requires a considerable implementation effort. We rely on an already powerful solution with the native electron. It also often requires direct access to Node.js from the community.

Best,
Gregor
