### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by rataman098** [ElectronNET/Electron.NET#207]
Hi, folks!

At first, I have to say that I'm in love with Electron.NET. The idea of not having to use JS that much is fantastic! The problem is that there isn't much documentation around to get used to this API.

The only things I have found are a couple of videos of 2017, and another in german (language I don't understand for the moment), all of them to some point outdated.

It would be incredible to have something like Javadoc at least, with classes, methods and what they do.

**Comment by duncanawoods** [comment]
So far I have resolved most of my issues by looking at the main electron docs https://electronjs.org/docs and a bit of browsing about with intellisense / goto definition :)

The current thing I am struggling with is packacking into an installer which I would happily have some more documentation on!

**Comment by GregorBiswanger** [comment]
We keep very close to the standard electron.js api, so that you can use the official documentation ideally. Some great blog posts have been posted in the community. We are grateful for any help.
