### ISSUE TITLE
Any community for this library?

### ISSUE THREAD

**Issue by grofit** [ElectronNET/Electron.NET#208]
Is there any community for this library? I couldnt see one on gitter, and cant find anything about a Discord or Slack room so was just wondering if there was anywhere I could go to discuss some queries I have on this rather than clogging up github issues.

**Comment by duncanawoods** [comment]
One option would be creating a channel in the Electron slack. Might help with visibility too. 

http://atom-slack.herokuapp.com/

**Comment by pha3z** [comment]
> was just wondering if there was anywhere I could go to discuss some queries I have on this rather than clogging up github issues.

I am often frustrated by the number of github repos that have no discussion board or community and you have to clog the issues board.  I wish Github would *at least* offer a second category of "issues" called "Discussion" or something to just keep things clean.

**Comment by grofit** [comment]
I would expect a big boom in this tech when Blazor hits its stride with ASP.Net as this will basically allow .net devs to make complex rich client applications without leaving VS, historically Razor was fine for non dynamic UIs but the moment you want to do anything fancy like dynamic forms or updating of data once the page has loaded it was painful and would be the domain of JS... but not so much now with WASM.

So anyway it would be prudent to look at getting a community together before the netcore 3 release which contains it, as that way you are at least gonna have everyone in the same place... minimal effort option would be to just setup a gitter room for this repo (I personally perfer discord, wish it had threaded conv but the hassle of setting up user reg with slack offset the benefit).

**Comment by grofit** [comment]
@GregorBiswanger Any preference or ideas going forward here as given the large amount of users it would be good to have an official place to discuss things.

**Comment by GregorBiswanger** [comment]
Hey Communiy, 
I have now opened a channel for us at Gitter. I can not promise how active we will be on it ourselves. But the goal is to bring the community closer and better together.

https://gitter.im/ElectronNET/community
