### ISSUE TITLE
support for asp.net core 2.2

### ISSUE THREAD

**Issue by LukasSlizik** [ElectronNET/Electron.NET#209]
Hi,

quick question
do you plan to support ASP.NET Core 2.2 ? Thanks !

best regards
Lukas Slizik

**Comment by angelcalvasp** [comment]
Any updates on this?

**Comment by jiewei915** [comment]
Hi, @LukasSlizik @angelcalvasp 
i did it on asp.net core 2.2 ,but i don't know why it worked.
see: [https://www.cnblogs.com/fansite/p/10516208.html]

**Comment by angelcalvasp** [comment]
Wow does seem to work
