### ISSUE TITLE
File Associations

### ISSUE THREAD

**Issue by dlitty** [ElectronNET/Electron.NET#212]
Hello,

Is there a mechanism in place that we can associate file extensions at the operating system level to our Electron.NET app, such that if you double click a file with a custom extension, it would automatically launch the app and open the file?  Looking primary for a macOS solution, but of course windows support would be great also.

Thanks.

**Comment by GregorBiswanger** [comment]
We are currently using the **electron-packager** to create a deliverable binary. For your wish, something has to be integrated with the builder. 

We are working to use **electron-builder** and this will make your request easy.

**Comment by GregorBiswanger** [comment]
Available with the next Electron.NET update.
