### ISSUE TITLE
Single exe?

### ISSUE THREAD

**Issue by iqmeta** [ElectronNET/Electron.NET#213]
Is it somehow possible to pack it in a single file like with

https://github.com/Fody/Costura
https://github.com/dotnet/ILMerge

Kind regards.

**Comment by win32nipuh** [comment]
Yes, it may be useful, but sometimes it will be single exe file >100MB

**Comment by gfs** [comment]
Costura and ILMerge only work on .NET not .NET Core.  For .NET Core you can try either waiting for 3.0 or [ILLink](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md)

**Comment by mu88** [comment]
I was able to produce a single EXE by setting `["build"]["win"]["target"] : "portable"` in `electron.manifest.json`.
