### ISSUE TITLE
require() in webpage doesn't use proper relative paths

### ISSUE THREAD

**Issue by The-MAZZTer** [ElectronNET/Electron.NET#216]
I am using electornize start to start my project from my project folder. I am using Electron.NET 0.0.11 under .NET Core 2.1.6 (I was going to use 2.2 but I got some warnings suggesting Electron.NET wasn't yet compatible).

I get "cannot load module" even though I can confirm the module is at the proper location.

For example for the url http://localhost:8001/ I have an index.html with the JavaScript: require("./scripts/main");

Trying to access ~~https~~ http://localhost:8001/scripts/main.js manually from a browser properly returns the JavaScript file I want it to load.

I pulled in these files from a normal Electron project where they worked.

I did some JS debugging in both Electron and Electron.NET. There is a parent value passed in which appears to contain the path of the script that is executing, which allows require() to resolve relative paths.

In Electron.NET, this value is INCORRECTLY set as "\<ProjectDir\>\obj\Host\node_modules\electron\dist\resources\electron.asar\renderer\init.js". It appears this is the path the webpage thinks it is at in the Module class which is responsible for creating a proper require command and tracking its current path and a bunch of other stuff. I am seeing this value propagate from Module.prototype._compile.

**Comment by JimmyTheJ** [comment]
You can't use HTTPS with electronNET.

**Comment by The-MAZZTer** [comment]
Sorry, I meant HTTP. I am not using HTTPS in Electron.NET.

**Comment by GregorBiswanger** [comment]
Please include the following base href in your index file:
`<base href="./">`

Note that usually the wwwroot directory is directly mapped and your relevant files are there.
