### ISSUE TITLE
Electron.NET serves webpages over network

### ISSUE THREAD

**Issue by The-MAZZTer** [ElectronNET/Electron.NET#217]
From the console window that shows when you run electronize start:

Now listening on: http://0.0.0.0:8001

ASP.NET should be configured to listen on 127.0.0.1, not 0.0.0.0, as the latter allows for external computers to connect, which is not desired for Electron.

**Comment by JimmyTheJ** [comment]
Correct, so don't expose all IPs like that in your dotnet code.

Just add .UseUrls() in program.cs, or add a JSON config to setup your kestrel or whatever other way you want to configure it.

**Comment by The-MAZZTer** [comment]
I think I ended up with 0.0.0.0 just following the README quickstart so I assume that is the ASP.NET default? Perhaps .UseElectron should call .UseUrls for you? (Not like you need to know the url anyway, it's all internal.)

**Comment by MichelArendt** [comment]
> Edit: If I call .UseUrls before .UseElectron, it has NO EFFECT. I have to call it AFTER .UseElectron. I think .UseElectron is trying to force 0.0.0.0. I think this should be considered a potential security vulnerability since even if the developer indicates 0.0.0.0 should not be used, it is still used.
> 
> Edit 2: I was correct, I went looking for the function in the code and found this:
> 
> [2fb3062](https://github.com/ElectronNET/Electron.NET/commit/2fb3062d4b11cbafe5ad8fe9c689626584ffbb36)

Thank you @The-MAZZTer. This comment was a life saver! \o/
