### ISSUE TITLE
Orphaned child processes when running electronize start

### ISSUE THREAD

**Issue by The-MAZZTer** [ElectronNET/Electron.NET#218]
I have launchSettings.json set to run electronize start (it may also happen from the command prompt).

If I run my program and then close the console window in an attempt to stop it, Visual Studio stops debugging and my console closes, but the Electron portion of the app continues running and I can see node and other processes continuing to run in Task Manager.

This can cause problems as if your program is not creating any UI (eg the ready-to-show bug) attempting to run the program again will fail as the compiled DLLs are in use and cannot be built.

**Comment by Fydar** [comment]
I get this issue so often, it's not just the Electron process that doesn't get cleaned up by my app and a load of other processes.

**Comment by GregorBiswanger** [comment]
The terminal shows a print-out of the ongoing process. The explicit termination via the terminal is possible, but if this is detached, the process continues independently.

We can not change that. by the way, there will be an additional Visual Studio plugin that allows for direct debugging. This is intended to remedy such pain.

Is anyone of you familiar with the VSSDK Extensibility? I'm still looking for how I get a button in the debug area. :)

**Comment by grbd** [comment]
I've noticed that in package.json we're using
```
"start": "tsc -p ."
```
instead of
```
"start": "electron ."
```
could this have something to do with it?

For debugging my plan is to setup apps which can also be run as websites (that don't dip into the electron api too much, by letting the .net code handle that side of things)
then debug it as a website first before deploying out as an application.
That way I can single step / debug both the .net code and any javascript / typescript in the IDE

**Comment by The-MAZZTer** [comment]
I forgot I filed this bug report.

This is generally only a problem when debugging since in production the user is going to be closing by the application window anyway.

However if the electron host is launching the asp.net core application, it could use the following event to detect if the asp.net core app closes, and to exit if it does:

https://nodejs.org/api/child_process.html#child_process_event_exit

It could potentially do something similar with the electronize process, not sure.
