### ISSUE TITLE
Application starts with Window Title "Electron.Net"

### ISSUE THREAD

**Issue by ErikApption** [ElectronNET/Electron.NET#220]
When I launch my Electron.net app - it takes a little while for the window title to change. On startup, it says "Electron.NET" and then later on after my web stack is ready, it changes to the proper name. 
I tried to trace where the initial window title comes from but was not able to figure that one out. Is that configurable?

Thanks

**Comment by flexbp** [comment]
You can pass the name into the window creation

`Task.Run(async () => await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions { Title = "Your fancy name here" }));`

**Comment by gfs** [comment]
@flexbp Thanks! Worked for me.
