### ISSUE TITLE
Error handling in ProcessHelper

### ISSUE THREAD

**Issue by paralaxsd** [ElectronNET/Electron.NET#223]
Hi,

While trying to electronize an asp.net core angular application I found a limitation in the way "electronize start" works that prevents the process from finishing successfully:

Running `electronize start` in my web application directory bails with _"Error occurred during dotnet publish: 1"_

The reason for this became clear once I looked at ElectronNET.CLI:
1.) Angular ASP.NET Core applications come with an extra msbuild target that's run when publishing. This target runs `npm install` and `npm run build -- --prod`. This yields lots of console output.
2.) `electronize start` ends up running `dotnet publish <args>` using the `ProcessHelper.CmdExecute` method.
3.) ProcessHelper **will bail out with return code 1** once it detects the sub string "_error_" in the process output streams.
4.) `electronize start` bails out because the output generated by npm run contains the string "_error_". In my case the exact value is "_14% building 40/42 modules 2 active ...pp\src\app\views\error\404.component.ts_".

Now that I know what's happening I can temp fix this issue by ensuring that npm stays silent. However I'd appreciate if you could come up with a way to prevent us from falling into this trap.

Thanks!

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
