### ISSUE TITLE
Exception in electronize start

### ISSUE THREAD

**Issue by KenneticKoncepts** [ElectronNET/Electron.NET#224]
I have been trying to get the electronize start to complete for 2 days.  It is a windows 10 installation.
**ENV: Windows 10
Electron Version : 0.0.11**

 Unfortunately I am getting the same error whether i am doing **electronize start**.  The error is.
Invoke electron.cmd - in dir: C:\Users\appe57c\source\repos\Electron.Net.Sample\Electron.Web.Sample\obj\Host\node_modules\.bin
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.
C:\Users\appe57c\source\repos\Electron.Net.Sample\Electron.Web.Sample\obj\Host\node_modules\.bin>electron.cmd "..\..\main.js"
module.js:487
    throw err;
    ^
Error: Cannot find module 'C:\Users\appe57c\source\repos\Electron.Net.Sample\Electron.Web.Sample\obj\Host\node_modules\electron\cli.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

if i try to do npm i electron i get 
$ npm i electron -g
C:\Users\appe57c\AppData\Roaming\npm\electron -> C:\Users\appe57c\AppData\Roaminnpm\node_modules\electron\cli.js

> electron@4.0.8 postinstall C:\Users\appe57c\AppData\Roaming\npm\node_modules\ectron
> node install.js

Downloading tmp-25508-0-electron-v4.0.8-win32-x64.zip
Error: read ECONNRESET
C:\Users\appe57c\AppData\Roaming\npm\node_modules\electron\install.js:49
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:607:25)
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\appe57c\AppDatRoaming\npm\node_modules\electron\node_modules\concat-stream\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\appe57c\Appta\Roaming\npm\node_modules\electron\node_modules\concat-stream\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\appe57c\\AppData\\Roaming\\npm\\node_modules\\electn\\node_modules\\concat-stream\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@4.0.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@4.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logng output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appe57c\AppData\Roaming\npm-cache\_logs\2019-03-13T13_49_4612Z-debug.log

is there anything that i am doing incorrectly.

**Comment by GregorBiswanger** [comment]
did you execute the following command before?

 `electronize init`
