### ISSUE TITLE
Windows created via window.open are not registered in Electron.WindowManager.BrowserWindows

### ISSUE THREAD

**Issue by CrisVrinceanu** [ElectronNET/Electron.NET#225]
As specified in the title the windows created via JavaScript  "window.Open" don't get registered in BrowserWindow list neither are marked as a child of parent. However via JavaScript you can see them as child.

It would be nice to have them in order to have full control of child windows.

**Comment by GregorBiswanger** [comment]
Please avoid creating windows with DOM. These are getting rid of the standard electron implementation. Both have nothing in common.

Alternatively, you can do the following:
```
const { BrowserWindow } = require('electron').remote
let win = new BrowserWindow({ width: 800, height: 600 })
win.loadURL('https://github.com')
```

**Important! Electron.NET will NOT get these into the WindowManager. Because the windows were created outside of our API.**
