### ISSUE TITLE
linux - electron app when close window dont finish all process

### ISSUE THREAD

**Issue by krubenrc** [ElectronNET/Electron.NET#226]
Hi, when i run the electron app, and i close the window, dont close all process, for example, if i run it with terminal, in the terminal the process still running.

But in Window, this dont happens. You can help me pls.

A kind regards.

**Comment by GregorBiswanger** [comment]
This is the normal electron architecture. You have a main process and a renderer process. Each window runs on the renderer process. The main process continues. It may be that your application does not need active windows. 

The following command ends everything:

`Electron.App.WindowAllClosed += () => Electron.App.Exit();`
