### ISSUE TITLE
electronize is not fount in macOS

### ISSUE THREAD

**Issue by seanmars** [ElectronNET/Electron.NET#229]
I install the cli tool with `dotnet tool install ElectronNET.CLI -g` in macOS, but the command `electronize` is not found. But it's worked on Windows.

```
> dotnet tool list -g
Package Id                            Version      Commands
------------------------------------------------------------------------------
dotnet-aspnet-codegenerator           2.2.2        dotnet-aspnet-codegenerator
electronnet.cli                       0.0.11       electronize
microsoft.web.librarymanager.cli      1.0.172      libman
```

**Comment by LuciferJun1227** [comment]
I have the same problem.
command not found: electronize

**Comment by win32nipuh** [comment]
May be the same solution as for Windows:
Rename or clone the electronize.exe to be called dotnet-electronize.exe

**Comment by phamquocthang** [comment]
Any update ? I'm facing same issue also

**Comment by RockNHawk** [comment]
I have the same issue On MacOS

**Comment by netpoetica** [comment]
@seanmars  @LuciferJun1227 @phamquocthang You *must* add dotnet tools to your $PATH. Most likely, you are using Bash, so you will have a ~/.bashrc or ~/.bash_profile that gets loaded in your terminal.

In your file, you must add

```
# .NET 
# For tools installed with `dotnet tool` command
export PATH="$HOME/.dotnet/tools:$PATH"
```

and then you must either `source` that file (eg `source ~/.bash_profile`) or create a new terminal window/tab.
