### ISSUE TITLE
UWP API

### ISSUE THREAD

**Issue by meteorsnows** [ElectronNET/Electron.NET#232]
How does we setup with UWP project, not desktop app / desktop bridge.
Would great it can run Windows 10 Compact Overlay, or only subset of Winrt?

**Comment by GregorBiswanger** [comment]
You can use WinRT with .NET Core:
https://stackoverflow.com/questions/35277359/how-to-use-windows-runtime-classes-in-net-core-libraries

But your Desktop Application have no cross-platform compatibility!
