### ISSUE TITLE
Responsive voice api not working in Electron.NET

### ISSUE THREAD

**Issue by Voljinlvlan** [ElectronNET/Electron.NET#237]
Hi, I'm working with electron.net first time and i create queue application but i have some issue about audio in client machine, So in my develop machine work fine. But when i build this software to client the audio not working

i use Responsive Voice to play text

i already add 
```
<!-- Insert this line above script imports  -->
    <script>if (typeof module === 'object') { window.module = module; module = undefined; }</script>
```

`<script src="~/js/responsivevoice.js"></script>`

and end of script already add
`<script>if (window.module) module = window.module;</script>`

i don't know why, Have someone get this issue and solved it ? Please shared, Thank you so much.

**Comment by Voljinlvlan** [comment]
look like on windows 8 (64bit) & 8 (32bit) work fine. But in window 10 sounds not working

**Comment by GregorBiswanger** [comment]
I do not think it's a Electron problem. Have you already opened the Chrome Developer Tools and looked for errors?

`Electron.WindowManager.BrowserWindows.First().WebContents.OpenDevTools();`

Other options for you:

Electron uses Chromium and here is an API for it:
https://developers.google.com/web/updates/2014/01/Web-apps-that-talk-Introduction-to-the-Speech-Synthesis-API

Alternatively one could try a .NET core solution in the main process:
https://www.c-sharpcorner.com/article/convert-text-to-speech-in-multiple-languages-using-asp-net-core-c-sharp/
