### ISSUE TITLE
Support for other package managers

### ISSUE THREAD

**Issue by grbd** [ElectronNET/Electron.NET#238]
Hi,
would it be possible to add support for pnpm or yarn instead of using npm
so instead of "npm install" the use of "pnpm install" or "yarn install"

pnpm tends to use a lot less disk space since it creates links inside node_modules that point to a single shared directory on the drive

**Comment by GregorBiswanger** [comment]
NPM gets better from version to version. We want to use the established technolegy in the market. Recognizing the extra implementation of what is still running on the system and then performing that preferrably would be more unnecessary. Sorry.

But you are welcome to do a pull request again.

**Comment by grbd** [comment]
I've added an option for it in some of the code I'm working on, I'll be putting that through on a pull request once I've finished with it
note I agree there may not be any advantages to yarn over npm

however pnpm does have one huge advantage in that it just stores just one copy of the files for node_modules in a single directory for all projects on a users drive
it then creates file links to that single copy.
So the end result is that you save a large amount of disk space with lots of websites under development since each one's node_modules just links back to a single copy on the disk.

**Comment by zaneclaes** [comment]
The [Electron.Build docs](https://www.electron.build/index.html#installation) (upon which this repo is built) now _"strongly recommend"_ using yarn over npm. It may be worth reconsidering this stance.
