### ISSUE TITLE
How to open file/url in external app

### ISSUE THREAD

**Issue by robalexclark** [ElectronNET/Electron.NET#244]
I'm trying to open pdfs and external urls in the default browser for both applications (not within the electron app). I researched and found that there might be a way using the electron shell:

    const shell = require('electron').shell;
    shell.openItem("https://www.google.com");

But the about does not work 'require is not defined' I appreciate I am probably missing something fundamental here! How do you access the electron js functions from your own js files?

**Comment by GregorBiswanger** [comment]
You can open external URLs via the Electron.NET API in C#:

`Electron.Shell.OpenExternalAsync("https://github.com/ElectronNET");`

[Have a look at our demo app.](https://github.com/ElectronNET/electron.net-api-demos)

P.S. Running your own TypeScript / JavaScript code will be possible with the next major Electron.NET version.
