### ISSUE TITLE
Can't Install dotnet tool

### ISSUE THREAD

**Issue by fals** [ElectronNET/Electron.NET#246]
When trying to install the dotnet tool, the fallowing message appears and the tool won't install.

Command:

`dotnet tool install --global ElectronNET.CLI --version 0.0.11`

Using Windows 10

>dotnet tool install ElectronNET.CLI -g
error NU3004: Package 'ElectronNET.CLI 0.0.11' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
error NU3004: Package 'ElectronNET.CLI 0.0.11' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
The tool package could not be restored.
Tool 'electronnet.cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

**Comment by grbd** [comment]
I just tried uninstalling and installing and it didn't seem to have any problems
```
dotnet tool uninstall --global ElectronNET.CLI
Tool 'electronnet.cli' (version '0.0.11') was successfully uninstalled.
```
dotnet tool install --global ElectronNET.CLI --version 0.0.11

```
You can invoke the tool using the following command: electronize
Tool 'electronnet.cli' (version '0.0.11') was successfully installed.
```

There's a recommendation here that you might need to update to a later dotnet sdk version due to a bug in Nuget

  * https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3004

**Comment by fals** [comment]
Indeed @grbd! After updating the SDK to the latest version it works! We can close this, But would be nice if you mention to use the last SDK within the instructions, because I'm almost sure more users can have this issue in the future.

Best Regards,
