### ISSUE TITLE
How to add menu to an app?

### ISSUE THREAD

**Issue by win32nipuh** [ElectronNET/Electron.NET#248]
How to add yet another menu to the app?
For example: the default menu is
File, Edit, View, Window, Help

I'd like to add my menu item + subitems
File, Edit, View, **Tools (Options, Customize)**, Window, Help

How to do it? 
When I do as in example, sipmle : 
[            var menu = new MenuItem[]
            {
                new MenuItem
                {
                    Label = "Tools",
                    Click = async () =>
                    {
                        await Electron.Dialog.ShowMessageBoxAsync("Go-go Pockemon!");
                    }
                }
            };
            Electron.Menu.SetApplicationMenu(menu);
](url)

it replaces entire application menu.

**Comment by win32nipuh** [comment]
Danke Gregor! :-)

**Comment by GregorBiswanger** [comment]
The native Electron has a default development menu.
If you add your own menu, this will be used.
You can not use the development menu and your own menu together..

**Comment by win32nipuh** [comment]
Ok, if I understand correctly it means: if I need to add my menu item I need create my own menu with the same items File, Edit etc, add my own and then replace application menu ?

**Comment by GregorBiswanger** [comment]
Yes, you have to implement that yourself again. Is a native Electron behavior.

**Comment by win32nipuh** [comment]
ok, I see. Please close this question.
