### ISSUE TITLE
What exactly is it? NET wrapper on top of Electron?

### ISSUE THREAD

**Issue by jitbit** [ElectronNET/Electron.NET#25]
The homepage lacks the most important information... What is this exactly? I though tit was a .net alternative to Electron, turns out it's it's just Electron (JS-based yeah) with a web-app running on the background?

**Comment by robertmuehsig** [comment]
Valid point. 

I quote my [intro blogpost](https://blog.codeinside.eu/2017/10/31/introducing-electrondotnet/), which may show you the basic "communication" 

> The basic functionality is not too complex:

> We ship a “standard” (more or less blank) Electron app
> Inside the Electron part two free ports are searched:
> The first free port is used inside the Electron app itself
> The second free port is used for the ASP.NET Core process
> The app launches the .NET Core process with ASP.NET Core port (e.g. localhost:8002) and injects the > first port as parameter
> Now we have a Socket.IO based linked between the launched ASP.NET Core app and the Electron app itself - this is our communication bridge!

Currently it is a __Wrapper__ - __not a port__. We heard the feedback and I assume that many think Electron.NET is a port. I will open another issue how a port might look like and what the problems are. Some aspects and ideas are already mentioned in this [issue](https://github.com/ElectronNET/Electron.NET/issues/22).

I think we need to update the readme @GregorBiswanger 

Anyway - thanks for your feedback 👍

**Comment by jitbit** [comment]
Thanks! You should probable mention this on the home page to fix this issue

**Comment by joaocc** [comment]
Have you guys considered using something like Bridge.Net (https://bridge.net/) to speed up the integration work?

**Comment by robertmuehsig** [comment]
I saw this project in combination with [Retyped](https://retyped.com/) a couple of weeks back. There are lot of possibilities. The idea was to get a familiar environment for ASP.NET Core devs, this might not be ideal, but we are looking for feedback :)

**Comment by joaocc** [comment]
Hi. Googled a bit more and I found these https://github.com/bridgedotnet/Widgetoko which seems closer to what I was asking about (something about it https://blog.bridge.net/widgetoko-a-node-js-and-electron-application-written-in-c-1a2be480e4f9).
Both approaches seem very interesting even though, in our case, the Widgetoko seems more interesting (we have an existing Electron/Angular/TS app).
Anyway, excellent initiative!

**Comment by Suchiman** [comment]
I wonder how much effort it would be to plug into electron to create a `<script type="text/csharp" />` since that would perform better than compiling C# to JS

**Comment by robertmuehsig** [comment]
So - I added some notes to the Readme.md and hope it is now clear what it is. Feel free to comment here if you have some more questions.
