### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by johna1203** [ElectronNET/Electron.NET#251]
I need to include in my project a dll that only works on x86.
When I run the "electronize start" it works, but I have a Controller that is using that DLL when I make the request using Ajax I get this error;

`System.BadImageFormatException: Could not load file or assembly 'LoginId, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`

is there any way to run the 'electronize start' for x86?

Thanks,

**Comment by GregorBiswanger** [comment]
Did you copy the same code to a prototype and tried again with x86?

**Comment by GregorBiswanger** [comment]
@robertmuehsig how we can build a dotnet binaries with x86 with the `electronize start` command?

**Comment by johna1203** [comment]
I'm just running "electronize start" and I was wondering if there is a way to run for x86. I think that would solve the error.

**Comment by robertmuehsig** [comment]
mh - currently not. Maybe we should add some arguments there as well...

**Comment by GregorBiswanger** [comment]
The Electron team will discontinue support for 32-bit Linux (ia32 / i386) starting with Electron v4.0. The last version of Electron that supports 32-bit based installations of Linux is Electron v3.1, which will receive support releases until Electron v6 is released. Support for 64-bit based Linux and armv7l will continue unchanged.

https://www.electronjs.org/blog/linux-32bit-support
