### ISSUE TITLE
MenuItem Icon exception.

### ISSUE THREAD

**Issue by Tum4ik** [ElectronNET/Electron.NET#254]
Hi.
I've created a simple tray application. I tried to add icon to some menu item, but it fails.
```csharp
  public class Desktoper
  {
    private readonly MenuItem[] _menuItems = new[]
    {
      new MenuItem
      {
        Label = "RunStop"
      },
      new MenuItem
      {
        Type = MenuType.separator
      }, 
      new MenuItem
      {
        Label = "Exit",
        Click = ()=> Electron.App.Exit(),
        Icon = "Desktop/icons/tray-stop-icon.png"  // <-- here fails
      }
    };


    public void Desktopize()
    {
      Electron.Tray.Show("Desktop/icons/tray-stop-icon.png", _menuItems);  // <-- here works fine
    }
  }
```

Here is the exception popup
![image](https://user-images.githubusercontent.com/21317790/58049013-80ce8c00-7b54-11e9-9bd2-997bd3aa0b58.png)

May be it supports only some specific image formats? Help me pls to understand or figure it out.
Thanks!

**Comment by GregorBiswanger** [comment]
This is a native electron problem. You need a complete path to the picture.
https://github.com/electron/electron/issues/7657

**Solution for Electron.NET:**
```
new MenuItem
{
    Label = "Exit",
    Click = ()=> Electron.App.Exit(),
    Icon = env.ContentRootPath + "/Desktop/icons/tray-stop-icon.png"
}
```

**Comment by Tum4ik** [comment]
Nice! Many thanks.
