### ISSUE TITLE
Why >electronize start does not start the application?

### ISSUE THREAD

**Issue by win32nipuh** [ElectronNET/Electron.NET#256]
I have build the simple app as Gregor showed in youtube.
It was built in VS2019, all is ok. 
But when I do
>dotnet electronize start
the app does not appear.
That is all what I see:
--------------
PS E:\MyProjects\CrossPlatform\Federmesser\fmapp5> electronize start
Start Electron Desktop Application...
Microsoft Windows [Version 10.0.17134.765]
(c) 2018 Microsoft Corporation. All rights reserved.
E:\MyProjects\CrossPlatform\Federmesser\fmapp5>dotnet publish -r win-x64 --output "E:\MyProjects\CrossPlatform\Federmesser\fmapp5\obj\Host\bin"
Microsoft (R) Build Engine version 16.1.54-preview+gd004974104 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restore completed in 594.66 ms for E:\MyProjects\CrossPlatform\Federmesser\fmapp5\FMApp5.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [E:\MyProjects\CrossPlatform\Federmesser\fmapp5\FMApp5.csproj]
  FMApp5 -> E:\MyProjects\CrossPlatform\Federmesser\fmapp5\bin\Debug\netcoreapp3.0\win-x64\FMApp5.dll
  FMApp5 -> E:\MyProjects\CrossPlatform\Federmesser\fmapp5\bin\Debug\netcoreapp3.0\win-x64\FMApp5.Views.dll
  FMApp5 -> E:\MyProjects\CrossPlatform\Federmesser\fmapp5\obj\Host\bin\
E:\MyProjects\CrossPlatform\Federmesser\fmapp5>
Skip npm install, because node_modules directory exists in: E:\MyProjects\CrossPlatform\Federmesser\fmapp5\obj\Host\node_modules
Invoke electron.cmd - in dir: E:\MyProjects\CrossPlatform\Federmesser\fmapp5\obj\Host\node_modules\.bin
Microsoft Windows [Version 10.0.17134.765]
(c) 2018 Microsoft Corporation. All rights reserved.
E:\MyProjects\CrossPlatform\Federmesser\fmapp5\obj\Host\node_modules\.bin>electron.cmd "..\..\main.js"
stdout: info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5057
stdout: info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: E:\MyProjects\CrossPlatform\Federmesser\fmapp5\obj\Host\bin
	  
--------------

and silence...

Then I go to the folder and run FMApp5.exe manually  - the same, no app.

What I do wrong?
I have attached my project
[FMApp51.zip](https://github.com/ElectronNET/Electron.NET/files/3202647/FMApp51.zip)

**Comment by GregorBiswanger** [comment]
Currently we have version 5.22.12 -> Support for Electron version 5, .NET Core 2.2, our release 12.

You used .NET Core 3 preview. Please try it again with an .NET Core 2.2 project.

**Comment by win32nipuh** [comment]
Thank you. I have build the new app (.NET Core 2.2), the same reaction, I run it but app does not appear.
[WA1.zip](https://github.com/ElectronNET/Electron.NET/files/3207409/WA1.zip)

**Comment by GregorBiswanger** [comment]
Okay, I found your problem.

You need the **UseElectron**-WebHost extension in the **program.cs**:

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseElectron(args)
            .UseStartup<Startup>();
}
```

And remove your fixed url-port assignment.

A tip, first set your application menu and then open the window:

```
public async void Bootstrap()
{
    var menu = new MenuItem[]
    {
        new MenuItem
        {
            Label = "File",
            Submenu = new MenuItem[]
            {
                new MenuItem
                {
                    Label = "Выход",
                    Click = () => { Electron.App.Exit(); }
                }
            }
        },
        new MenuItem
        {
            Label = "Инфа",
            Click = async () =>
            {
                await Electron.Dialog.ShowMessageBoxAsync("Go-go Pockemon!");
            }
        }
    };

    Electron.Menu.SetApplicationMenu(menu);

    var options = new BrowserWindowOptions
    {
        Show = false
    };

    var mainWindow = await Electron.WindowManager.CreateWindowAsync(options);
    mainWindow.OnReadyToShow += () => { mainWindow.Show(); };
}
```

**Comment by win32nipuh** [comment]
Thank you Gregor! Sorry.
das ist mein Fehler :-)
