### ISSUE TITLE
Menu Item visibility

### ISSUE THREAD

**Issue by Tum4ik** [ElectronNET/Electron.NET#257]
Hi,
As far as I understand the "Visibility" property set to "false" should hide the MenuItem.

![image](https://user-images.githubusercontent.com/21317790/58123475-90ada500-7c14-11e9-9df0-1483f1722d1b.png)

But "Stop Server" item is still present.

![image](https://user-images.githubusercontent.com/21317790/58123540-b63aae80-7c14-11e9-9c32-bf8a25a829c2.png)

Thanks!

**Comment by GregorBiswanger** [comment]
Fixed for version [5.22.13](https://github.com/ElectronNET/Electron.NET/milestone/6)

**But unfortunately not for top level menu items.** A native electron bug that stands under wontfix:
https://github.com/electron/electron/issues/8703
