### ISSUE TITLE
electron.manifest.json - singleInstance not working

### ISSUE THREAD

**Issue by bata-miroslav** [ElectronNET/Electron.NET#258]
Hi,
I downloaded demo from url https://github.com/ElectronNET/electron.net-api-demos/tree/v5.22.12 where should be probbably used nuget package in version 5.22.12 and I edited electron.manifest.json file 

![2019-05-22 15_15_32-ElectronNET-API-Demos - Microsoft Visual Studio](https://user-images.githubusercontent.com/50915138/58178675-e0d54780-7ca6-11e9-82e1-7452eca31f24.png)

After build (electronize build /target win) application is not opened . If you change  "singleInstance" to false application is opened.

Thanks

**Comment by GregorBiswanger** [comment]
Fixed for version [5.22.13](https://github.com/ElectronNET/Electron.NET/milestone/6)
