### ISSUE TITLE
Full implementation of autoUpdater api

### ISSUE THREAD

**Issue by GregorBiswanger** [ElectronNET/Electron.NET#259]
**Events**
- error
- checking-for-update
- update-available
- update-not-available
- download-progress
- update-downloaded
- before-quit-for-update

**Methods**
- downloadUpdate
- autoUpdater.setFeedURL(options)
- autoUpdater.getFeedURL()

https://www.electron.build/auto-update

**Comment by OmiCron07** [comment]
Where is the documentation for that feature?

**Comment by sachinmakhre** [comment]
please Any one can help me to implement auo update in electron Server blazor application ..
