### ISSUE TITLE
electron.manifest ("singleInstance": true) does not work properly

### ISSUE THREAD

**Issue by Tum4ik** [ElectronNET/Electron.NET#267]
* **Version**: 
ElectronNET.CLI Version: 5.22.12.0
ElectronNET.API Version: 5.22.12
.NET Core Version: 2.2.300
Node.js Version: 8.11.3

* **Target**: 
Windows

If I set "singleInstance" property to `true` in the electron.manifest.json, it is not possible to start any more the application either via `electronize start` command or via exe file from built application.

My expectation for `"singleInstance": true` is that I can run only one instance of my application.

**Comment by GregorBiswanger** [comment]
Duplicate of #258

Fixed for the next Electron.NET Update 5.22.13
