### ISSUE TITLE
Add new Electronize CLI command

### ISSUE THREAD

**Issue by Oleg26Dev** [ElectronNET/Electron.NET#273]
Add  Electronize CLI command 'clear cache' or something like this to have a possibility to clean cache manually as it can be done in code :
`await browserWindow.WebContents.Session.ClearCacheAsync();`

**Comment by GregorBiswanger** [comment]
I implemented a new CLI command:
`electronize start /clear-cache`

Every new window will created with an clear cache.

This new feature is aviable with the new Electron.NET Version 8.31.1
