### ISSUE TITLE
Electron.NET & Sqlite Installer Issue

### ISSUE THREAD

**Issue by hamendranathtyagi** [ElectronNET/Electron.NET#276]
My test app is running fine by using **electronize start** command. Now I am trying to create Installer by applying following command command : **electronize build /target win**. I am able to create **electron.net.host Setup 1.0.2.exe** under **..obj\desktop\win\dist folder**. But When I am running this exe it gives me attached error. Kindly assist on same
![Electro Net Installer issue](https://user-images.githubusercontent.com/51729757/59353943-b0cb1280-8d41-11e9-97c5-852fd5d97a08.PNG)

**Comment by AlexTM92** [comment]
Have you tried to build with the latest version of the CLI?

**Comment by GregorBiswanger** [comment]
Use our newest 5.22.12 API & CLI Version.

And then type the following command in your ASP.NET Core folder:
`electronize init`

**Comment by hamendranathtyagi** [comment]
I am using .NET core 2.2 and 5.22.12 API already  and when I am trying to include 5.22.12 CLI Version, It gives attached error. I have below entry in my csproj file. Kinldy assit on same.   
<ItemGroup>
    <DotNetCliToolReference Include="ElectronNET.CLI" Version="0.0.9" />
  </ItemGroup>


![Electro Net Installer issue-ElectronNET CLI](https://user-images.githubusercontent.com/51729757/59355836-60ee4a80-8d45-11e9-8a03-e29fefbd6e30.PNG)

**Comment by AlexTM92** [comment]
Try to install the CLI globally:
`dotnet tool install electronnet.cli -g`

**Comment by hamendranathtyagi** [comment]
I already did this and tried again as you asked. Get below message 

C:\Electron\10June2019Sqlite\netcoretutorial\Tutoriel>**dotnet tool install ElectronNET.CLI -g**
**Tool 'electronnet.cli' is already installed.**

**Comment by GregorBiswanger** [comment]
@hamendranathtyagi Which version does the CLI output?

`electronize version`

Alternatively, you can also remove the CLI globally and reinstall:

`dotnet tool uninstall ElectronNET.CLI -g`

**Comment by hamendranathtyagi** [comment]
@GregorBiswanger
ElectronNET.CLI Version: 5.22.12.0
But in cs project file I am using below entry:
  <ItemGroup>
    <DotNetCliToolReference Include="ElectronNET.CLI" Version="0.0.9" />
  </ItemGroup>


And when I changed my cs project entry with

  <ItemGroup>
    <DotNetCliToolReference Include="ElectronNET.CLI" Version="5.22.12.0" />
  </ItemGroup>

I am getting below errror;
![Electro Net Installer issue-ElectronNET CLI-In CS project](https://user-images.githubusercontent.com/51729757/59419890-7ddc5980-8de9-11e9-9ae7-fdab2c7e8c67.PNG)

**Comment by GregorBiswanger** [comment]
Strange. Normally, Electron.NET supports the .NET Core Version 2.2. - Normally, the ItemGroup entry is no longer needed. Remove the part and try again. It is only needed for the API.

Possibly. can you reproduce the problem and provide it to me. Then I can arrange it for you.

**Comment by hamendranathtyagi** [comment]
I removed the the ItemGroup entry from cs project as you suggested.
Application run fine with IIS express as well electronize start.

And then I tried **electronize build /target win64** . I got dist folder created as well electron.net.host Setup 1.0.2.exe created. But When I am running the **electron.net.host Setup 1.0.2.exe** I will be getting below error.
But 
![InstallerIssue-13June2019](https://user-images.githubusercontent.com/51729757/59422560-373d2e00-8dee-11e9-9985-26bcea3666ef.PNG)

**Comment by hamendranathtyagi** [comment]
@ GregorBiswanger
Please find attached electron.manifest. If I am missing something then pls let me know.

**Comment by hamendranathtyagi** [comment]
@ GregorBiswanger - Kindly assist on my issue. Regards

**Comment by GregorBiswanger** [comment]
@hamendranathtyagi do you have the new **electron.manifest.json** file structure? see in the readme.md at important notes...

**Comment by LarsPedersen** [comment]
@hamendranathtyagi I've seen the same problem on a recent .NET Core 3.0 project building with ElectronNET.CLI version 5.30.1.0. When I examined the **electron.manifest.json** I realized that the final output was to the **bin** folder, as per my manifest file:
```
    "directories": {
      "output": "../../../bin/Desktop"
    },
```
The installer the bin/Desktop folder works fine.

I hope that this helps.
