### ISSUE TITLE
Blank Page with Blazor (ASP.NET Core hosted) Preview 6

### ISSUE THREAD

**Issue by MaherJendoubi** [ElectronNET/Electron.NET#277]
* **Version**: 5.22.12

dotnet --version
3.0.100-preview6-012264

* **Target**: win-x64

Steps to Reproduce:

1. Created a vanilla Blazor (ASP.NET Core hosted)
2. Added ElectronNET.API to the Server project
3. Setup Electron.NET stuff as described here https://maherjendoubi.io/blazor-electron/
4. electonize init
5. electronize start

The result is the following:

![image](https://user-images.githubusercontent.com/1798510/59561991-f714c000-9026-11e9-8200-c5849be60d75.png)

**Comment by MaherJendoubi** [comment]
**electronize start**
Start Electron Desktop Application...
Microsoft Windows [version 10.0.18362.175]
(c) 2019 Microsoft Corporation. Tous droits réservés.
C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server>dotnet publish -r win-x64 --output "C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\bin"
Microsoft (R) Build Engine version 16.2.0-preview-19278-01+d635043bd pour .NET Core
Copyright (C) Microsoft Corporation. Tous droits réservés.
  Restauration effectuée dans 19,34 ms pour C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Client\WebApplication20.Client.csproj.
  Restauration effectuée dans 19,21 ms pour C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Shared\WebApplication20.Shared.csproj.
  Restauration effectuée dans 23,89 ms pour C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\WebApplication20.Server.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message : NETSDK1057 : Vous utilisez une préversion de .NET Core. Voir : https://aka.ms/dotnet-core-preview [C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\WebApplication20.Server.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message : NETSDK1057 : Vous utilisez une préversion de .NET Core. Voir : https://aka.ms/dotnet-core-preview [C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Shared\WebApplication20.Shared.csproj]
  WebApplication20.Shared -> C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Shared\bin\Debug\netstandard2.0\WebApplication20.Shared.dll
  WebApplication20.Client -> C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Client\bin\Debug\netstandard2.0\WebApplication20.Client.dll
  Blazor Build result -> 33 files in C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Client\bin\Debug\netstandard2.0\dist
  WebApplication20.Server -> C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\bin\Debug\netcoreapp3.0\win-x64\WebApplication20.Server.dll
  WebApplication20.Server -> C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\bin\
C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server>
Skip npm install, because node_modules directory exists in: C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\node_modules
Invoke electron.cmd - in dir: C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\node_modules\.bin
Microsoft Windows [version 10.0.18362.175]
(c) 2019 Microsoft Corporation. Tous droits réservés.
C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\node_modules\.bin>electron.cmd "..\..\main.js"
stdout: Use Electron Port: 8000
stdout: info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Maher\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
ASP.NET Core Application connected... global.electronsocket GLstc8UetcSP0PiFAAAA 2019-06-17T22:08:12.520Z
stdout: Hosting environment: Production
Content root path: C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\bin\
Now listening on: http://localhost:8001
Application started. Press Ctrl+C to shut down.
stdout: BridgeConnector connected!
stdout: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:8001/
stdout: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback {*path:nonfile}'
stdout: info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback {*path:nonfile}'
stdout: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 29.200300000000002ms 404
C:\Users\Maher\source\repos\WebApplication20\WebApplication20.Server\obj\Host\node_modules\.bin>

**Comment by robertmclaws** [comment]
Any luck with this yet?

**Comment by MaherJendoubi** [comment]
Let's wait for Preview 7.

**Comment by robertmclaws** [comment]
I spent a few hours yesterday digging into this issue, and I figured it out. It really has nothing to do with Electron.NET, and everything to do with the changes they made to the Endpoint Routing. With the Preview 6 changes, not all of the files were exposed to the Host, and the ones that were weren't in the right spot.

After a few hours of testing, I was able to get everything working and into [a NuGet package](https://github.com/CloudNimble/ElectronNET.Blazor) that could handle the changes. I didn't make a PR here yet because it requires VS2019, and I didn't want to force that upgrade on the project without asking. So for now, [it's in my own repo](https://github.com/CloudNimble/ElectronNET.Blazor).

If you get a chance, please test it out (instructions are on the repo home page) and let me know if it works for you. Then we can discuss if it needs to move.

Thanks!

**Comment by MaherJendoubi** [comment]
@robertmclaws I really appreciate your great effort digging into this issue.
I tested it:
![image](https://user-images.githubusercontent.com/1798510/60771349-0c8d7f00-a0e7-11e9-8b79-94b5bb98de80.png)

Thanks !

**Comment by robertmclaws** [comment]
Since this was not an Electron.NE issue, but an ASP.NET Core routing issue, you can feel free to close this bug.

**Comment by GregorBiswanger** [comment]
@robertmclaws Thank you very much for your support!

The native Blazor support in Electron.NET is important to us. Can you please submit your PR.

**Comment by ThuCommix** [comment]
Nice work @robertmclaws, it would be cool if this would be in the standard extensions provided by electron.net.

**Comment by MaherJendoubi** [comment]
Excuse my ignorance but I cannot see the pull request fixing this issue.

**Comment by robertmclaws** [comment]
That's because one is no longer required. Either Microsoft or this team fixed the issue, and the package is no longer necessary. I've updated ElectronNET.Blazor for Preview 7 to restore the original behavior without breaking anyone who already installed it. I'm not recommending anyone remove it yet, in case something breaks between now and Blazor RTM, but I'll put a note in the readme.txt file when it's safe to uninstall the package.

**Comment by MaherJendoubi** [comment]
@robertmclaws Thank you for the answer.
