### ISSUE TITLE
Electron.NET & .Net Core 2.2 Web API

### ISSUE THREAD

**Issue by hamendranathtyagi** [ElectronNET/Electron.NET#278]
How to host and consume .Net Core 2.2 Web API inside Electron.Net ?

**Comment by robalexclark** [comment]
Web API is just a set of controller methods that provide data to the client side (or another client side system). You would not use electron to host just a Web API for other systems to consume.

**Comment by hamendranathtyagi** [comment]
@robalexclark - My current Project has 3 Web API to interact with database. Also My UI has been developed in Angular. Now I am trying to create desktop application using Electron.Net framework and need to host 3 Web API inside electron framework as well. So that my end users can run this project as EXE and host all 3 Web API inside Electron.Net framwork only. Regards

**Comment by robalexclark** [comment]
As long as your web API is in the same project as the client side Angular they should work fine.

For example, if you take a look at the following electron net based repo:
https://github.com/robalexclark/SilveR

Specifically the controllers at:
https://github.com/robalexclark/SilveR/tree/master/SilveR/Controllers

You will see that there are controllers for views (e.g. homecontroller), but there are also web API controllers as well (e.g. ValuesController), that provide methods for the client side javascript to consume

**Comment by hamendranathtyagi** [comment]
@robalexclark - My Web APIs are not in the same project as Angular. These are different 3 Web API projects and 4th one is UI project. Hence I am looking the way to host these 3 web APIs in Electron so that I can consume by Angular UI. Regards

**Comment by robalexclark** [comment]
It might be possible to combine all projects into a single Visual Studio solution with the UI project as the entry point that you apply electron.net to. However I have no idea how you would sort out the routing. Easiest solution would be to copy all the web api methods into a single VS solution though...
