### ISSUE TITLE
buildAll.sh fails "out of the box" on macOS

### ISSUE THREAD

**Issue by markmcgookin** [ElectronNET/Electron.NET#279]
* **Version**: 
Latest version from source based on commit dc8987d
$ node --version v10.15.3
$ dotnet --version 2.2.107

* **Target**: macOS
Pull the latest version of the source code on macOS and run buildAll.sh you get the error:

Build FAILED.
Solution file error MSB4249: Unable to build website project "ElectronNET.Host". The ASP.NET compiler is only available on the .NET Framework version of MSBuild.

Steps to Reproduce:

1. Pull latest version
2. Run buildAll.sh

**Comment by GregorBiswanger** [comment]
I now referenced the assemblies directly. Works best for me.

**Comment by dafergu2** [comment]
This issues till happens if you simply run `dotnet build` in the main directory.  In addition, the builds for linux and windows fail during the `buildAll.sh` as well.

The issue with the solution is due to the project reference in the solution file.  Is there a need to set the following in the .sln file?

```
Project("{E24C65DC-7377-472B-9ABA-BC803B73C61A}") = "ElectronNET.Host", "ElectronNET.Host\", "{B33E9B82-B6B4-4DB0-B6EE-61CC34641518}"
	ProjectSection(WebsiteProperties) = preProject
		TargetFrameworkMoniker = ".NETFramework,Version%3Dv4.0"
		Debug.AspNetCompiler.VirtualPath = "/localhost_56840"
		Debug.AspNetCompiler.PhysicalPath = "ElectronNET.Host\"
		Debug.AspNetCompiler.TargetPath = "PrecompiledWeb\localhost_56840\"
		Debug.AspNetCompiler.Updateable = "true"
		Debug.AspNetCompiler.ForceOverwrite = "true"
		Debug.AspNetCompiler.FixedNames = "false"
		Debug.AspNetCompiler.Debug = "True"
		Release.AspNetCompiler.VirtualPath = "/localhost_56840"
		Release.AspNetCompiler.PhysicalPath = "ElectronNET.Host\"
		Release.AspNetCompiler.TargetPath = "PrecompiledWeb\localhost_56840\"
		Release.AspNetCompiler.Updateable = "true"
		Release.AspNetCompiler.ForceOverwrite = "true"
		Release.AspNetCompiler.FixedNames = "false"
		Release.AspNetCompiler.Debug = "False"
		VWDPort = "56840"
		SlnRelativePath = "ElectronNET.Host\"
	EndProjectSection
EndProject
```
