### ISSUE TITLE
Can't run under Linux 

### ISSUE THREAD

**Issue by CrisVrinceanu** [ElectronNET/Electron.NET#285]
I can't run my application under Linux anymore after the new release.
It's creating a .snap file which I can't use because of the environment we have (can't install snap in production OS). I have tried copying the linux-unpacked folder which seems to have the same hierarchy as the previous one, given execution permissions but no output is shown when executing.

I can still build with the previous CLI version (which wasn't using the build server I guess).

How can I avoid building a .snap?

**Comment by CrisVrinceanu** [comment]
@GregorBiswanger

**Comment by GregorBiswanger** [comment]
What was your previous CLI version?

**Comment by CrisVrinceanu** [comment]
The previous version which is working:
ElectronNET.CLI Version: 0.0.11.0

Actual version I'm trying to use:
ElectronNET.CLI Version: 5.22.13.0

The command is the same:
electronize build /target linux

Electronize start works with both (on windows)

**Comment by GregorBiswanger** [comment]
In the new version (5.22.12), we moved from electron-packager to electron-builder.
Please, use the new "electron.manifest.json" file. Delete the old one, and execute the "electronize init" command inner your asp.net core project.

If you develop under Linux, please install electron-builder with:
`sudo npm install electron-builder --global  `

**Comment by CrisVrinceanu** [comment]
I have followed the steps but the result is still the same.

I am trying to build from Windows for Linux.

It keeps doing that remote build and generating the .snap file. The files in linux-unpacked are still not working.

**Comment by CrisVrinceanu** [comment]
Update

Now it works, I figured out that this behaviour occurs only if the electron.net.host is run as root (with sudo).
Executing it with a lower level user works fine.

Thank you for the help @GregorBiswanger

**Comment by CrisVrinceanu** [comment]
Re-Opening

Seems like I need to find a way to run the application with elevated privileges (root). Is there any way to do it?

Also is there an electron log I can enable to see what's going wrong when launching as root?
Could be because of the chrome-sandbox? I can see similar behaviour on chromium-browser if trying to launch as root without the "--no-sandbox" flag, but even setting Sandbox to false in WebPreference nothing happens.

**Comment by GregorBiswanger** [comment]
Hi @CrisVrinceanu, 
unfortunately, I can not handle your problem right now. Under the hood, Electron.NET uses the **electron-builder**. You can **configure** it in the **electron.manifest.json** file under the **build part**. You can find the documentation here: https://www.electron.build/configuration/snap

Alternatively you have to google it and try it afterwards.
