### ISSUE TITLE
Environment Variable for running in Electron

### ISSUE THREAD

**Issue by robertmclaws** [ElectronNET/Electron.NET#287]
Is there currently a safe way to detect whether or not an app is running in Electron? If not, would it be possible for you folks to be able to compile in an environment variable (like "IS_ELECTRON") when a .NET app is running under Electron.NET? Right no I'm having to [make my users add it manually](https://github.com/CloudNimble/ElectronNET.Blazor#installation-instructions), but it would be nice if I could detect it automatically.

Thanks!

**Comment by GregorBiswanger** [comment]
Hi @robertmclaws 

we have the static property `HybridSupport.IsElectronActive`

is that what you want?
