### ISSUE TITLE
.Net Standard Issue

### ISSUE THREAD

**Issue by donniefitz2** [ElectronNET/Electron.NET#290]
I'm trying to add ElectroNet to a new Blazor application (.net core 3.0 preview, client side only) and I'm getting the following error when attempting to restore the Nuget package:

`ElectronNET.API 5.22.13 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package ElectronNET.API 5.22.13 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)`

I get that my template is targeting netstandard2.1 and ElectronNet targets netcoreapp2.1 but shouldn't they be compatible?

This Blazor project file targets netstandard2.0 with the following csproj settings:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview6.19307.2"/>
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview6.19307.2" PrivateAssets="all"/>
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview6.19307.2" PrivateAssets="all"/>
    <PackageReference Include="ElectronNET.API" Version="*"/>
  </ItemGroup>
</Project>
```

Thanks.

**Comment by robertmclaws** [comment]
It looks like you're trying to add it to the Client app, not the Server app. Electron.NET + Blazor does not run in the Standalone Blazor template. The directions here should help get you going: https://github.com/CloudNimble/ElectronNET.Blazor

**Comment by GregorBiswanger** [comment]
In the versioning of Electron.NET -> **5.22.XX** is the support of Electron in version **5** and .NET Core in version **2.2**. With the finished .NET Core 3.0 and Blazor we will offer full support when it's released.

**Comment by donniefitz2** [comment]
Thanks.
