### ISSUE TITLE
There is no appsetting.json 

### ISSUE THREAD

**Issue by Oleg26Dev** [ElectronNET/Electron.NET#293]
I have built my app in Windows, it works ok. 
Then decided to test it in Linux. I have built target linux, copied to Ubuntu and run. It stars and tries to work. 
But I do not see appsetting.json and log4net.config in output directory. These files contain some settings.
Where are these files located? How to change settings for runtime?

**Comment by win32nipuh** [comment]
Sorry, I have found it in subdirectory.

**Comment by GregorBiswanger** [comment]
The appsettings.json file can be read in as usual with ASP.NET Core and work with it.
https://www.c-sharpcorner.com/article/reading-values-from-appsettings-json-in-asp-net-core/

After the build you can see the file here:
ProjectName\bin\Desktop\win-unpacked\resources\bin
