### ISSUE TITLE
How to avoid EventEmitter Max Listeners warning?

### ISSUE THREAD

**Issue by win32nipuh** [ElectronNET/Electron.NET#294]
I use Ipc to exchange data:
```
     <button id="cmdShowData">Process</button>

    <script>
        (function () {
            const { ipcRenderer } = require("electron");

            document.getElementById("cmdShowData").addEventListener("click", () => {
                ipcRenderer.send("doProcess", 'args');
            });

            ipcRenderer.on('sendData1', (event, msg) => {
                document.getElementById("ResponseOK").innerHTML = msg;
            });
        }());
    </script>

```
But after 11 page loadings I receive:

> (node:29284) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 doProcess listeners added. Use emitter.setMaxListeners() to increase limit

How and where I can increase this limit?
Is it problem or it is warning only?

**Comment by GregorBiswanger** [comment]
The code is called again and again when you reload your page. You should therefore not repeat an event registration.

It is best to register your code globally rather than directly on the same page. Or use the unload event and cancel the registrations.

https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event

**Comment by Oleg26Dev** [comment]
Thanx, ok. 
Now I do it in Controller/Action method. 
But when I click menu the Controller object created again, its constructor etc.
Where is the best place to register it?

**Comment by GregorBiswanger** [comment]
It's best to use a single-page app, or see the code from our demo app. 
Alternatively, you can also use Blazor.

https://github.com/ElectronNET/electron.net-api-demos
