### ISSUE TITLE
Bug with SetUserAgent

### ISSUE THREAD

**Issue by MerrickKing** [ElectronNET/Electron.NET#295]
Using the following code, which according to what I can find online, should but doesn't set the UserAgent header accordingly, and instead uses the default UserAgent string.

`var mainWindow = await Electron.WindowManager.CreateWindowAsync(options);
mainWindow.WebContents.Session.SetUserAgent("ModX");
mainWindow.OnReadyToShow += () =>
{
    mainWindow.Show();
};`

**Comment by GregorBiswanger** [comment]
The documentation from native electron says: _"This doesn't affect existing `WebContents`, and each `WebContents` can use `webContents.setUserAgent` to **override** the session-wide user agent."_
(see https://electronjs.org/docs/api/session).

Maybe that's your problem?

**Comment by MerrickKing** [comment]
Well I'd assume that this would effectively be me overriding the default
UserAgent for my main window?

**Comment by GregorBiswanger** [comment]
Hi @MerrickKing,

I found the following example: https://stackoverflow.com/questions/35672602/how-to-set-electron-useragent

Here is the solution for change the UserAgent with Electron.NET.

```
Task.Run(async () =>
{
    var browserWindowOptions = new BrowserWindowOptions()
    {
        Show = false
    };

    var mainWindow = await Electron.WindowManager.CreateWindowAsync(browserWindowOptions);
    mainWindow.LoadURL("http://localhost:" + BridgeSettings.WebPort, new LoadURLOptions
    {
        UserAgent = "ModX",
    });

    mainWindow.OnReadyToShow += () => mainWindow.Show();
});
```

In your view you can see the new UserAgent with:

`navigator.userAgent;`

I hope I could help you. Have fun with Electron.NET! Happy coding...
