### ISSUE TITLE
>electronize Unhandled exception

### ISSUE THREAD

**Issue by Oleg26Dev** [ElectronNET/Electron.NET#296]
If I run electronize with incorrect arguments it crashes with "Unhandled Exception". For example:
>electronize build -?
>electronize build

etc
May be catch all exceptions and output some messages about error in command line?
Also, to extend the output help, for example: about command
>electronize build 
and so on

**Comment by Oleg26Dev** [comment]
Also, I run
>electronize build /target macos

There are no errors, it works, successfully builds Windows version.
It may be be better: 
1. Parse "macos" as "mac" and build mac version
2, Show error in cases like this and display correct arguments for /target option

**Comment by GregorBiswanger** [comment]
The solution is, use this command:

`electronize build /target osx`

**Comment by Oleg26Dev** [comment]
Yes, the solution is as you wrote but IMHO in any case need to catch all exceptions and extend the help output.

**Comment by GregorBiswanger** [comment]
@robertmuehsig FYI

**Comment by GregorBiswanger** [comment]
Fixed with Electron.NET Version 7.30.2
