### ISSUE TITLE
Is there an easier way to debug

### ISSUE THREAD

**Issue by GanZhiXiong** [ElectronNET/Electron.NET#298]
![image](https://user-images.githubusercontent.com/27394631/62099426-92ed4900-b2c0-11e9-8678-a1b584ac1387.png)

Each time the code is modified, electronize start should be executed, and then Attach to Process. This Process is a little troublesome, but there is no simpler debugging method

**Comment by GregorBiswanger** [comment]
Hi @GanZhiXiong, 

yes that is still our problem that we do not have our own debug profile, which makes the whole thing easier. Currently I can only recommend the following: 

Develop your web app as you are used to in the browser. If you then want to implement and test desktop features, you have to choose the not so nice way. However, that should usually only be 10% of the case. The rest would be normal in the browser possible.

**Comment by GanZhiXiong** [comment]
@GregorBiswanger   Thank you for your answer😀
