### ISSUE TITLE
BrowserWindow.SetMenu(null) not working

### ISSUE THREAD

**Issue by shazha** [ElectronNET/Electron.NET#301]
Thanks for this great project, it's really helpful  😃

* **Version**:  5.22.14
.Net Core SDK version: latest 2.2 release

* **Target**: Windows 10

The menu bar is supposed to be removed completely by invoking `BrowerWindow.SetMenu(null)` or `Menu.setApplicationMenu(null)`. However, the default menu, which contains standard items such as `File` and `Edit`, is not suppressed and the menu bar is not removed from created BrowserWindow on Windows.

**Comment by hack2root** [comment]
The menu bar is supposed to be removed completely by invoking browerWindow.RemoveMenu();

**Comment by GregorBiswanger** [comment]
Big thanks to @hack2root for your contribution!

This new feature comes with the next version **5.22.15**.
