### ISSUE TITLE
No symbols loaded during debug

### ISSUE THREAD

**Issue by hhfranzo** [ElectronNET/Electron.NET#302]
Hello,

I'm struggling to debug my Electron .Net application with VS2019. I tried also with the Demo and I have the same issue. 
I run "electronize start" from a console. Then I attach the process (the exe produced). I set a break point and a I see a warning message when hoovering on the break point saying that no symbols were loaded for that specific source file. I looked at the pdb files in the "electronize" target folder and they are present.
The version I'm using is 5.22.14.0

Is there something that I'm missing?

Thanks for your help.

**Comment by GregorBiswanger** [comment]
please use our newest version and install global the newest Electron.NET version.
