### ISSUE TITLE
How to hide the top menu

### ISSUE THREAD

**Issue by qcjxberin** [ElectronNET/Electron.NET#304]
How to hide the top menu

**Comment by qcjxberin** [comment]
The removeMenu() method was not found

**Comment by GregorBiswanger** [comment]
The native Electron has a default development menu.
If you add your own menu, this will be used and you can remove it.

**Comment by GregorBiswanger** [comment]
See https://electronjs.org/docs/api/menu

**Comment by GregorBiswanger** [comment]
The next version **5.22.15** brings the `BrowserWindow.RemoveMenu()` method.

**Comment by qcjxberin** [comment]
OK，Thanks!

**Comment by sshanzel** [comment]
Hi! Thanks a lot for this repo. May i know when will this be possible for .Net 2.2?
