### ISSUE TITLE
Electronize Command Imporvements

### ISSUE THREAD

**Issue by Nikey646** [ElectronNET/Electron.NET#305]
The CLI is so bare bones, that it's actually hard to work with.

Some suggestions include providing the capability to automatically use Environment Variables provided via the default launch profiles. This will allow the usage of `env.IsDevelopment()` and etc.

Rather than building the main application and than executing the binary, launching the application via `dotnet run` on the .csproj would be preferable. Continuing from this, it should support the `dotnet watch` tool, allowing the developer to make changes to the the ASP.Net Core webapp and having the server automatically re-compile.

On a side note, because I don't really want to make another issue to suggest this, pointing developers using SPA frameworks to the SpaServices extension (`Mircosoft.AspNetCore.SpaServices`) and using the `ISpaBuilder.UseProxyToSpaDevelopmentServer` method to provide hot reloading without any additional configuration from the standard framework methods,

**Comment by GregorBiswanger** [comment]
For 90% of the cases, it is enough to implement the application in the browser and then process it for Electron. So you can easily maintain your developer comfort without any problems.

I'm thinking about a solution for `dotnet watch` with Electron.NET CLI.

**Comment by GregorBiswanger** [comment]
Live reload is on the way with Electron.NET version 8.31.1 >> #380
