### ISSUE TITLE
How to change/customize appname and author

### ISSUE THREAD

**Issue by benlemond** [ElectronNET/Electron.NET#310]
I have downloaded ElectronNET-API-Demos.  I have gotten it running simply enough.  My problem is that I am new and I am trying to figure out how to customize an installer build in order to deploy my custom application.

I have run `electronize build /target win` and I have created a "electron.net.host Setup 1.0.2.exe" file under "ElectronNET-API-Demos\obj\desktop\win\dist\".   My question is which package.json files (or other files) do I need to customize in order to change the Author and other properties about the build for my exe?

**Comment by nareshjois** [comment]
@benlemond you can start with the `electron.manifest.json` from the root folder  and if you want to use a custom package.json you can use `/package-json <customJson>` from the prompt

**Comment by TirumaleswaraReddy** [comment]
I too have the same problem, I'm able to create setup file but setup file having description and company name are wrong. Can you please support me how to customize description and company
![CodeImage](https://user-images.githubusercontent.com/13554466/72067753-8e19d000-3309-11ea-83e5-da9201807d2a.png)
![IssuaImage](https://user-images.githubusercontent.com/13554466/72067754-8e19d000-3309-11ea-90c9-009e35beee64.png)

**Comment by GregorBiswanger** [comment]
I just tested that electron-builder doesn't just let the names and authors be configured externally. This would normally be done using the extraMetadata setting.

**I will add this** as a new feature for the **upcoming Electron.NET version**, which you can easily do in the `electron.manifest.json` file.

**Current workaround to the solution:** While you are executing the following command, for example, `electronize build /target win` - can you be active, before electron-builder becomes active at the end, quickly exchange the `package.json` with your own data. You can find the current file under `PROJECTFOLDER/obj/desktop/win/package.json` - write your desired name for app name and your author name there.

![ElectronNet-Workaround](https://user-images.githubusercontent.com/7336300/75614165-43ad1680-5b36-11ea-99b5-8d5cdf31a464.gif)

Please give me your feedback on whether it worked for you.

**Comment by zenith6495** [comment]
Actually as @Tum4ik mentioned in the chat before, a better temporary workaround solution would be as follow:-
you should modify the author property in your package.json file and pass the package.json file during your build via command electronize build /target win /package-json package.json

**Comment by zenith6495** [comment]
@GregorBiswanger is this issue fixed in the latest version 8. 31.1? What's the new electron.manifest.json file look like?

**Comment by GregorBiswanger** [comment]
You can set a name and author of the app in `electron.manifest.json` with the new Electron.NET version 8.31.1 (#348 )

As example:

```
{
  "executable": "ElectronNet8311",
  "splashscreen": {
    "imageFile": "/wwwroot/assets/electronnet-splashscreen-2.jpg"
  },
  "name": "ElectronNet8311",
  "author": "Max Mustermann",
  "description": "voll my app",
  "singleInstance": false,
  "build": {
    "appId": "com.ElectronNet8311.app",
    "productName": "ElectronNet8311",
    "copyright": "Copyright © 2020",
    "buildVersion": "1.0.0",
    "compression": "maximum",
    "directories": {
      "output": "../../../bin/Desktop"
    },
    "extraResources": [
      {
        "from": "./bin",
        "to": "bin",
        "filter": ["**/*"]
      }
    ],
    "files": [
      {
        "from": "./ElectronHostHook/node_modules",
        "to": "ElectronHostHook/node_modules",
        "filter": ["**/*"]
      },
      "**/*"
    ]
  }
}
```
