### ISSUE TITLE
Linux SSL/port issues

### ISSUE THREAD

**Issue by esperpinion** [ElectronNET/Electron.NET#316]
* **Version**: CLI 5.22.14.0 API 5.22.14

Core 3.0, Node.js v10.16.0

* **Target**: Linux (Ubuntu v16)

Hi. I'm having issues running Blazor + ElectronNET app on Linux. The Windows build works fine. 
We're also running additional API that is accessed through simple full uri requests.

Ubuntu console outputs:
`stdout: warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.`
right after BridgeConnector connected.

In app, the problem is UI not being updated after any changes. API responds as being accessed fine.

The above happens only on Ubuntu, while on Windows everything is fine.

Currently our API is accessed through http protocol, Blazor UI is too. Only Electron Socket is https.
Trying to open electron socket in browser gives SSL error.

I've tried adding to StartupConfigure
```
app.UseCertificateForwarding();
app.UseForwardedHeaders();
```
or removing
```
app.UseHsts();
...
app.UseHttpsRedirection();
```
But the problem remains.
Is it possible to switch electron to http protocol or allow unsafe connection (possible in electronjs)?

Thank you.

**Comment by GregorBiswanger** [comment]
https://www.thesslstore.com/blog/how-to-make-ssl-certificates-play-nice-with-asp-net-core/
