### ISSUE TITLE
After build App not running

### ISSUE THREAD

**Issue by Arslanijaz-009** [ElectronNET/Electron.NET#317]
5.22.14

core 2.2
!-- What target are you building for? -->
win

After build app setup app not found and except of setup there is four folder with many sub files.
There is one app.exe file i run console window is open but app not lunching.

**Comment by kiwidave72** [comment]
Im getting the same issue with windows.

Ive install everything ,and its targeting dotnet 2.2.402, as i have 3.0 installed as well.
If i run the exe after , it still thinks its needs to be hosted?

c:\Github\electron.net-api-demos>electronize build /target win
Build Electron Application...
Build ASP.NET Core App for win-x64...
Executing dotnet publish in this directory: c:\Github\electron.net-api-demos\obj\desktop\win
Build ASP.NET Core App for win-x64 under Release-Configuration...
Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.
c:\Github\electron.net-api-demos>dotnet publish -r win-x64 -c Release --output "c:\Github\electron.net-api-demos\obj\desktop\win\bin"
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restore completed in 39.67 ms for c:\Github\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj.
  ElectronNET-API-Demos -> c:\Github\electron.net-api-demos\ElectronNET-API-Demos\bin\Release\netcoreapp2.2\win-x64\ElectronNET-API-Demos.dll
  ElectronNET-API-Demos -> c:\Github\electron.net-api-demos\ElectronNET-API-Demos\bin\Release\netcoreapp2.2\win-x64\ElectronNET-API-Demos.Views.dll
  ElectronNET-API-Demos -> c:\Github\electron.net-api-demos\obj\desktop\win\bin\
c:\Github\electron.net-api-demos>
Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.
c:\Github\electron.net-api-demos\obj\desktop\win>npm install --production
audited 359 packages in 1.357s
found 0 vulnerabilities
c:\Github\electron.net-api-demos\obj\desktop\win>
Start npm install electron-builder...
Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.
c:\Github\electron.net-api-demos\obj\desktop\win>npm install electron-builder --global
C:\Users\KiwiD\AppData\Roaming\npm\electron-builder -> C:\Users\KiwiD\AppData\Roaming\npm\node_modules\electron-builder\out\cli\cli.js
C:\Users\KiwiD\AppData\Roaming\npm\install-app-deps -> C:\Users\KiwiD\AppData\Roaming\npm\node_modules\electron-builder\out\cli\install-app-deps.js
+ electron-builder@21.2.0
updated 1 package in 4.198s
c:\Github\electron.net-api-demos\obj\desktop\win>
ElectronHostHook handling started...
Build Electron Desktop Application...
Executing electron magic in this directory: c:\Github\electron.net-api-demos\bin\desktop
Create electron-builder configuration file...
Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.
c:\Github\electron.net-api-demos\obj\desktop\win>node build-helper.js
c:\Github\electron.net-api-demos\obj\desktop\win>
Package Electron App for Platform win...
Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.
c:\Github\electron.net-api-demos\obj\desktop\win>electron-builder . --config=./bin/electron-builder.json --win --x64 -c.electronVersion=5.0.8
  ΓÇó electron-builder  version=21.2.0 os=10.0.18362
  ΓÇó loaded configuration  file=c:\Github\electron.net-api-demos\obj\desktop\win\bin\electron-builder.json
  ΓÇó packaging       platform=win32 arch=x64 electron=5.0.8 appOutDir=dist\win-unpacked
  ΓÇó default Electron icon is used  reason=application icon is not set
  ΓÇó building        target=nsis file=dist\electron.net.host Setup 1.0.2.exe archs=x64 oneClick=true perMachine=false
  ΓÇó building block map  blockMapFile=dist\electron.net.host Setup 1.0.2.exe.blockmap
c:\Github\electron.net-api-demos\obj\desktop\win>
... done

**Comment by AyronK** [comment]
Hi, I think you might have the same problem I had (obj files was generated but no binaries/exe). To solve this I reinstalled Electron.CLI.

Try this:

```
dotnet tool uninstall ElectronNET.CLI -g
dotnet tool install ElectronNET.CLI -g
```

After the latest patch with .NET Core 3.0 migration they messed sth up, but the latest CLI handles it (at least for me).

**Comment by Sn3b** [comment]
Just run into the same issue. Originally I was on CLI version 1.0.0, re-installed it specifying the version number to reflect the documentation, turns out re-installing it without version number got me to version 7.30.2.0. Documentation should be updated.

**Comment by jadhavrani123** [comment]
var menu = new MenuItem[] {

             new MenuItem
            {
                Label = "Open",

        Click = async () => mainWindow = await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions
                {
                    Width = 900,
                    Height = 700,
    }),

},

On minimize my exe store it work properly but problem is here in tray icon right click open option exe open multiple items

how to remove it please help us

On open click I want exe open only one time

**Comment by GregorBiswanger** [comment]
Please use the latest version of Electron.NET. 

You can find answers to the system tray on gitter:
https://gitter.im/ElectronNET/community
