### ISSUE TITLE
Rename Electronize.exe for better Azure DevOps support

### ISSUE THREAD

**Issue by robertmclaws** [ElectronNET/Electron.NET#318]
If you change the name of `electronize.exe` to `dotnet-electronize.exe`, when the global tool is installed, you'd be able to use the built-in Azure DevOps .NET Core tasks to call `electronize`, instead of having to use Powershell.

**Comment by robertmuehsig** [comment]
Ah - cool. I guess the correct <toolname> is missing. Maybe this could do the trick - I will see what I can do :)

https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create#setup-the-global-tool
