### ISSUE TITLE
[CLI] /absolute-path or /relative-path do not change output location

### ISSUE THREAD

**Issue by robertmclaws** [ElectronNET/Electron.NET#319]
### Version
* **5.22.14**: 

### Platform
* **Windows**: 

### Issue Details
Entering the following path into the build process does not change how the project is built: `..\tools\electronize.exe build /target win /absolute-path '$(Build.ArtifactStagingDirectory)\Windows'`

Looking into the source code for the CLI, it looks like [these lines do indeed set the path](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.CLI/Commands/BuildCommand.cs#L134-L142) that the `electron-builder` should use, but then the[ actual builder command uses the path calculated](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.CLI/Commands/BuildCommand.cs#L163) for the internal `dotnet build` command:
```
ProcessHelper.CmdExecute($"electron-builder . --config=./bin/electron-builder.json --{platformInfo.ElectronPackerPlatform} --{electronArch} -c.electronVersion=5.0.8 {electronParams}", tempPath);
```

### Steps to Reproduce:

1. Install .NET Core 2.2 SDK during the build process.
2. Install .NET Core ElectronNET.CLI Global tool during the build process.
3. Run command above in the working folder of the project you are building. Example: `$(Build.SourcesDirectory)/CloudNimble.AzureDevOpsBuddy.Server`

**Comment by robertmclaws** [comment]
@GregorBiswanger Any chance this could get in the 7.30 release too? Should be a quick fix, it's just using the `tempPath` at the very end instead of `buildPath`.

Thanks!

**Comment by GregorBiswanger** [comment]
@robertmclaws I can not promise yet. @robertmuehsig is normally responsible for the CLI...

**Comment by GregorBiswanger** [comment]
I see we have an relative-path param...

Use:
electronize build /target win /relative-path "YOUR PATH"
