### ISSUE TITLE
Adding to ElectronNET.Host

### ISSUE THREAD

**Issue by Liam2349** [ElectronNET/Electron.NET#325]
Hi,

I recently started using Electron.NET, and I'm looking to add functionality to one of the JavaScript files in ElectronNET.Host/api. I'm doing this because it appears that not all of the electron-js events are currently available, so I'm adding one, and I was planning on offering it as a contribution if it worked.

I made my changes in a TypeScript file and compiled it in vscode, and the changes are reflected in the JS file, which I believe the TS files compile into.

I made corresponding changes in ElectronNET.API so that this functionality would be accessible from C#. I've built the API project in vs proper, ran the nuget script, got the package, that's fine.

I've got a project I'm consuming this from, and when I look inside obj/Host/api in my own consumer project, the JS files are not showing my changes, so the modifications I made in ElectronNet.Host are not available. I don't know how I'm supposed to get these changes into my consumer project.

Can anyone tell me what I'm missing here? What is the process for getting these JS files in the ElectronNET.Host project into my consumer app?

**Comment by GregorBiswanger** [comment]
Hey

To do this, you must store the JavaScript files in the following file:
`ElectronNET.CLI/Commands/Actions/DeployEmbeddedElectronFiles.cs`

You can then use the generated DLL from the CLI project roughly as follows:
`dotnet "C:\Users\Gregor\source\repos\Electron.NET\ElectronNET.CLI\bin\Debug\netcoreapp3.0\dotnet-electronize.dll" start`

Write to me privately via [Gitter](https://gitter.im/ElectronNET/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge). I am very happy to help you.

Thanks for your contribution.
