### ISSUE TITLE
Electron Jquery error

### ISSUE THREAD

**Issue by vardear1** [ElectronNET/Electron.NET#329]
Developed an application with core 2.2 MVC and followed all the steps to use electron. After starting the application, the electron window opens with the splash page, however, I am receiving an error for jquery - Uncaught TypeError: Cannot read property 'fn' of undefined. Googled a lot for a solution without success. Any assistance to resolve this would be greatly appreciated. Thanks
![Electron error](https://user-images.githubusercontent.com/57007803/67581400-f21ef600-f715-11e9-87bb-1a086cefbee3.JPG)

**Comment by Liam2349** [comment]
Are you trying to load jQuery yourself?

Electron already uses jQuery, so you have to load it a bit differently to use in your own scripts. I'm doing it like this:

<script src="~/js/jquery-3.4.1.min.js" onload="window.$ = window.jQuery = module.exports;" asp-append-version="true"></script>

You could copy this and replace the path to match your own project structure.

The asp-attribute is optional. You shouldn't need it for this file but I use it anyway.

**Comment by vardear1** [comment]
Thanks so much Liam. Your solution worked like a charm
