### ISSUE TITLE
Electron UI crash on input="file" click

### ISSUE THREAD

**Issue by KristiforMilchev** [ElectronNET/Electron.NET#332]
Latest CLI and API for Electron.Net

.net core 3.0 and latest node.js updated last night

Platform Linux/ Distrobution Arch

The bug isn't that trivial because i found a work around but it will be nice to get it fixed. I don't know what's the exact cause of the issue but when the application is started trough visual studio code internal console with electronize start  and any file input is clicked the UI of the electron application just crashes without an error. For those that have experienced the work around that i found is to start the application from a separate terminal then attach a debugger to the app from visual studio code. 

 I have several applications that run electron with node.js as a backend but they are all running Electron 7.0.0 and it might be the earlier version that comes with Electron.Net

**Comment by GregorBiswanger** [comment]
Please try the latest Electron.NET 7.30.2 version. This supports Electron version 7.1.2 and .NET Core 3.0.
