### ISSUE TITLE
dotnet core 3 BlazorServer App start with JavaScript Error

### ISSUE THREAD

**Issue by aboimpinto** [ElectronNET/Electron.NET#333]
I install the new Nuget package that provides support for dotnet core 3.0 and when I run the app using:
# electronize start

I get always this message

![image](https://user-images.githubusercontent.com/1231687/67817854-660f2480-faaf-11e9-982f-a37b29412cd3.png)

sometimes the Electron app run and other times no. Still didn't figure it out when does what.

I'm running in Ubuntu 19.10

**Comment by h2floh** [comment]
I have the same/similar error while using `electronize start` on Windows 10 dotnet core 3.1:

![image](https://user-images.githubusercontent.com/29010283/72042315-82baaa80-32f1-11ea-9cd5-79a340cbcc80.png)

**Comment by h2floh** [comment]
For me it resolved after I added a missing configuration value to appsettings.json which I did not realized when copying code around:

https://github.com/ElectronNET/Electron.NET/blob/68288d9d73bb423c0e500e5bec1149523c3d99e9/ElectronNET.WebApp/Startup.cs#L63
