### ISSUE TITLE
Exceptions during splash screen / net core startup do not exit electron process

### ISSUE THREAD

**Issue by ErikApption** [ElectronNET/Electron.NET#338]
* **Version**: 5.30.1

.net core 3.0 - no node js

* **Target**: windows

Steps to Reproduce:

1. App with long startup (~10s)
2. Exceptions during startup leave the splash screen open and electron processes have to be manually killed

I tried doing a try/catch with Electron.App.Exit() but this did not close the electron process with the splash screen...

**Comment by OmiCron07** [comment]
I got an exception when starting my application and I just find out that you can click on the splash to quit/kill the Electron processes.

**Comment by GregorBiswanger** [comment]
We need a solution for a global exception handling in .net core... I didn´t mean the ErrorMiddleware... that is only for request/response error handling... but I don´t find a global exception handling...

You must set a try-catch block self. In the catch block you can exit the application.
Alternative, you can use the shortcut `[Ctrl] + [C]` in the cmd box (thx @OmiCron07) or click on splashscreen and use `[Alt] + [F4]`.

**This code works for me, to close the app with splashscreen:**
```
Task.Run(async () =>
{
    try
    {
        throw new Exception("whaaa");
    }
    catch (Exception)
    {
        Electron.App.Exit();
        throw;
    }
                
    await Electron.WindowManager.CreateWindowAsync();
});
```
