### ISSUE TITLE
Printing to system printer without browser dialog

### ISSUE THREAD

**Issue by rutzelt** [ElectronNET/Electron.NET#339]
We have a requirement for our browser-based application to print directly to a printer resource.  Depending on the print job, it would need to auto-detect the available printers, select one, and issue the print job to it.  We may need to change options as well (i.e. portrait vs. landscape).  All of this would need to be done WITHOUT a browser window popping up.  Can we have a method of interacting with system resources (printers) without needing to interact with something like "Chrome's Print Preview" ?

Thank you,
Tom

**Comment by x-xx-o** [comment]
I'd like this one too.

[Print capability exists in Electron](https://electronjs.org/docs/api/web-contents#contentsprintoptions-callback), it should be quite simple to implement (and it would be even better if [getPrinters](https://electronjs.org/docs/api/web-contents#contentsgetprinters) were added too).

**Comment by GregorBiswanger** [comment]
Thanks for your contribution @x-xx-o 

The next Electron.NET Version 8.31.1 have your new printer support.
