### ISSUE TITLE
Electronize.exe does not let you specify different electron.manifest.json

### ISSUE THREAD

**Issue by robertmclaws** [ElectronNET/Electron.NET#340]
* **Version**: 5.30.1
* **.NET Core Version**: 3.0

**Issue**: I'm trying to automate my builds and create different "channels" (Dev/Beta/Prod). I wanted to use the /electron-params switch to specify the file myself... but the file name is hardcoded to the executable. I should be able to specify the file name myself, so I can have a electron.manifest.dev.json file, etc.

As for now, I'm kind of stuck, because I can't even use token replacement to get what I want, because that would break local builds. I'm going to have to resort to file renaming on the build server... which is also more complex than necessary.

Thanks so much for looking into this!

**Comment by GregorBiswanger** [comment]
**Thank you for your donation!** 

At the moment I am sick. If I am well again on the weekend, I will take care of your wishes as soon as possible .. at the latest next week ..

**Comment by GregorBiswanger** [comment]
Implemented! Available in Electron.NET version 7.30.2.

**You can add additional manifest files with:**

`electronize init /manifest beta`

The Electron.NET CLI creates a electron.manifest.beta.json file into your project with debug profile.

**You can start for debug your Electron.NET app with:**

`electronize start /manifest electron.manifest.beta.json`

**You can build your Electron.NET app with:**

`electronize build /target win /manifest electron.manifest.beta.json`

**Comment by ArunEdathadan** [comment]
There was a manifest error when used visual studio package manager console. but when run with visual studio code it worked.
