### ISSUE TITLE
Upgrade to Electron 7.0

### ISSUE THREAD

**Issue by robertmclaws** [ElectronNET/Electron.NET#341]
Electron has [shipped version 7.](https://electronjs.org/blog/electron-7-0)0, and support for Version 4.0 has ended. That means EOL for 5.0 is just around the corner.

Would be great if we could get the perf improvements of Microsoft's involvement with the Chromium project into our apps ASAP. Thanks!

**Comment by GregorBiswanger** [comment]
**Thank you for your donation!**

At the moment I am sick. If I am well again on the weekend, I will take care of your wishes as soon as possible .. at the latest next week ..

**Comment by robertmclaws** [comment]
No worries, please get some rest and feel better soon! :)

**Comment by GregorBiswanger** [comment]
Implemented! Available in Electron.NET version 7.30.2.
