### ISSUE TITLE
Unable to disable WebSecurity (or set any web preferences)

### ISSUE THREAD

**Issue by ddaspit** [ElectronNET/Electron.NET#344]
* **Version**: 5.30.1

* **Target**: Windows

When you create a browser window with `WebSecurity` set to `false`, it doesn't work. This seems to occur, because in `browserWindows.ts`, the `createBrowserWindow` handler only performs a shallow merge when merging the `options` parameter in order to set `nodeIntegration` to `true`. This results in the entire `webPreferences` object being overwritten.

Steps to Reproduce:
This can be reproduced using the [Electron.NET music player sample app](https://github.com/ElectronNET/electron.net-musicplayer-sample).
1. Start the music player app.
2. Play a music file.
3. Nothing happens. An error appears in the console.

**Comment by GregorBiswanger** [comment]
The music player app is still based on an old Electron.NET version. I have to update this somehow. I tried a new example with the current Electron.NET 7.30.2 version and it worked without problems. I have access to files and can play them.

I used the same code snippets from:
http://www.cross-platform-blog.com/electron.net/electron.net-musicplayer-app-with-asp.net-core/

**Comment by ddaspit** [comment]
I forked the [music player sample app](https://github.com/ddaspit/electron.net-musicplayer-sample) and updated it to 7.30.2. The master branch demonstrates the issue. When I click the play button, it does not play and I receive the following error in the console:
```
(index):1 Not allowed to load local resource: file:///C:/Users/user/Music/music.mp3
(index):1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
```
When I paste the file URL directly into Chrome, it plays correctly.

**Comment by jlcool** [comment]
Is there any progress on this issue

**Comment by duncanawoods** [comment]
This is also a problem for me. I've just had to rewrite a bunch of things to serve up local files via the http server as a work-around which shouldn't be necessary.

Possibly related to this?

https://github.com/electron/electron/issues/19846

**Comment by syedadeel2** [comment]
That is correct!! if I set the nodeIntegration = false its works

`                WebPreferences = new WebPreferences
                {
                    WebSecurity = false,
                    AllowRunningInsecureContent = true,
                    ExperimentalCanvasFeatures=true,
                    ScrollBounce=true,
                    NodeIntegration = false
                }`

**Comment by GregorBiswanger** [comment]
Works with the new Electron.NET 8.31.1.
