### ISSUE TITLE
getName function is deprecated

### ISSUE THREAD

**Issue by OmiCron07** [ElectronNET/Electron.NET#350]
* **Version**: 7.30.2

.Net Core 3.1

* **Target**: Windows

When using `Electron.App.GetNameAsync()`, there is a message into the console : `(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.`.

**Comment by icemaniceman** [comment]
Have you solve this problem yet?

**Comment by OmiCron07** [comment]
No, I'm just waiting because my project is on hold.

**Comment by GregorBiswanger** [comment]
Changed App.GetNameAsync and App.SetNameAsync to App.Name Property for Electron.NET Version 8.31.1.
