### ISSUE TITLE
Getting blazor error UI while using electron

### ISSUE THREAD

**Issue by MordechaiHadad** [ElectronNET/Electron.NET#353]
**Description:** Today I have decided to use electron.NET with blazor server, I have followed this [tutorial](https://maherjendoubi.io/blazor-electron/) and it worked fine.
Now when I started my app again to after some things I have added to my project and I got this issue in the console ``warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.`` I have decided to debug it IIS Express and I got no issues at all.
To try to fix I have tried to: 
* Remove things from the original project.
* Create a new project, follow the tutorial and without changing anything and adding any code to the project use ``electronize start``. 

* **Electron.NET Version:** Latest
* **.NET Core:** Latest
* **Node.js and npm Version:** Latest
* **Blazor Type:** Server

Steps to Reproduce:

1. Create new blazor server project.
2. Install and setup Electron.NET like in the tutorial.
3. Run ``electronize start``

**Comment by MordechaiHadad** [comment]
Okay a little update today it seems to work like it should but I didn't change or touch anything, you guys should look into it.
Maybe its a problem with blazor/.NET core itself?

**Comment by robertmclaws** [comment]
Yes this is a Blazor issue not an Electron issue. You should probably close it.

**Comment by MordechaiHadad** [comment]
> Yes this is a Blazor issue not an Electron issue. You should probably close it.

How is that a Blazor issue if when using Blazor normally I didn't get this problem?

**Comment by robertmclaws** [comment]
Because I believe that the HttpRedirectMiddleware is running inside your server project, in which case it is not specific to Electron.NET. It is indicating that your launchSettings.json file has incorrect settings.

**Comment by MordechaiHadad** [comment]
> Because I believe that the HttpRedirectMiddleware is running inside your server project, in which case it is not specific to Electron.NET. It is indicating that your launchSettings.json file has incorrect settings.

Hmm but now without changing anything it works fine for me no errors no something running smooth even as Electron window.
