### ISSUE TITLE
Time of starting app

### ISSUE THREAD

**Issue by hrishynpavlo** [ElectronNET/Electron.NET#356]
Hello,
Is it possible to improve the time of starting application?
It takes about 5-10 seconds, when app was builded

**Comment by dichaos** [comment]
I have the same issue, why does this happen ?

**Comment by GregorBiswanger** [comment]
If you add a splash screen you can see that Electron and Node.js behind it is very fast. The problem in the background is .NET Core. The starting process is usually slow. In the current 3.1 version, it has become even faster with the `PublishReadyToRun` option.

In the current Electron.NET version 8.31.1 - We used here .NET Core 3.1 and I activate the `PublishReadyToRun` option per default.. so we incease the startup time for ~25-36%.
Corresponding 2-4 seconds faster with some of hello world samples, that I tested.

Is not perfect yet but I hope you are happy :)
