### ISSUE TITLE
how to control local host port no

### ISSUE THREAD

**Issue by som-nitjsr** [ElectronNET/Electron.NET#359]
* **Version**: 
I am using latest with .net core 3.1 

* **Target**: 

Steps to Reproduce:
In my app i am using openid connection authentication. my issue is app every time use different port   my return url does not does not match. how can i use the fix url.

**Comment by GregorBiswanger** [comment]
You need an additional configuration in the **electron.manifest.json** file with the key **aspCoreBackendPort**:

```
{
  "executable": "ElectronNET.WebApp",
  "splashscreen": {
    "imageFile": "/wwwroot/assets/img/about@2x.png"
  },
  "singleInstance": false,
  "aspCoreBackendPort": 8080, <--- Your custom Port for ASP.NET Backend
  "build": {
    "appId": "com.electronnetapidemos.app",
...
```

The application then runs automatically as a single instance. I hope you like it that way.

**Comment by som-nitjsr** [comment]
Thanks i will try.

**Comment by nazar322** [comment]
`"aspCoreBackendPort": 8080, <--- Your custom Port for ASP.NET Backend`
 There is no such record in the default `electron.manifest.json`.
 It would be great if there was a doc about all possible options in `electron.manifest.json`.
