### ISSUE TITLE
Exception after dotnet electronize start

### ISSUE THREAD

**Issue by r105m** [ElectronNET/Electron.NET#36]
Linux, fedora 27
**$ dotnet --version**

	2.0.2

**$ node --version**

	v8.6.0

**$ which electron-packager** 

	/usr/bin/electron-packager

**$ touch ./Properties/launchSettings.json**
**$  dotnet electronize init**

	Adding our config file to your project...
	Search your .csproj to add the needed electron.manifest.json...
	Found your .csproj: /home/ilya/edn/edn.csproj - check for existing config or update it.
	electron.manifest.json will be added to csproj.
	electron.manifest.json added in csproj!
	Search your .launchSettings to add our electron debug profile...
	Debug profile added!
	Everything done - happy electronizing!

**$ dotnet electronize start**

	Start Electron Desktop Application...
	Microsoft (R) Build Engine версии 15.4.8.50001 для .NET Core
	(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

	  edn -> /home/ilya/edn/bin/Debug/netcoreapp2.0/win10-x64/edn.dll
	  edn -> /home/ilya/edn/obj/Host/bin/

	Start npm install...

	> uws@0.14.5 install /home/ilya/edn/obj/Host/node_modules/uws
	> node-gyp rebuild > build_log.txt 2>&1 || exit 0

	> electron@1.7.8 postinstall /home/ilya/edn/obj/Host/node_modules/electron
	> node install.js

	npm WARN ElectronNET.Host@1.0.0 No description
	npm WARN ElectronNET.Host@1.0.0 No repository field.

	added 195 packages in 5.628s

	Invoke electron.cmd - in dir: /home/ilya/edn/obj/Host/node_modules/.bin
	bash: строка 1: electron.cmd: команда не найдена

electron.cmd ? Is it a windows batch script?

**Comment by robertmuehsig** [comment]
Ah - this is indeed a bug. The start command ist in the current version Windows only. I try to fix it this weekend.
I only tried Ubuntu in a VM, cloud you maybe do a "dotnet electronize build" and check if you can start the application under /ElectronNET.WebApp/bin/desktop/..." ?

**Comment by fuyfuy** [comment]
dotnet electronize start fails on Ubuntu the same way that is shown above for Fedora.
I tried "sudo dotnet electronize build" and it fails with the log below.
FWIW, I have node 8.9.0, could it be a part of the problem?

  electron -> /home/fuy/learning/netcore/electron/bin/Debug/netcoreapp2.0/ubuntu-x64/electron.dll
  electron -> /home/fuy/learning/netcore/electron/obj/desktop/linux/bin/


Start npm install...

> uws@0.14.5 install /home/fuy/learning/netcore/electron/obj/desktop/linux/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

sh: 1: cannot create build_log.txt: Permission denied

> electron@1.7.8 postinstall /home/fuy/learning/netcore/electron/obj/desktop/linux/node_modules/electron
> node install.js

/home/fuy/learning/netcore/electron/obj/desktop/linux/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/home/fuy/learning/netcore/electron/obj/desktop/linux/node_modules/electron/dist'
npm WARN ElectronNET.Host@1.0.0 No description
npm WARN ElectronNET.Host@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fuy/.npm/_logs/2017-11-04T12_16_58_583Z-debug.log


Start npm install electron-packager...
Electron Packager - make sure you invoke 'sudo npm install electron-packager --global' at /home/fuy/learning/netcore/electron/obj/desktop/linux manually. Sry.
Build Electron Desktop Application...
Executing electron magic in this directory: /home/fuy/learning/netcore/electron/bin/desktop
Package Electron App for Platform linux...
Cannot find module 'electron' from '/home/fuy/learning/netcore/electron/obj/desktop/linux'

**Comment by robertmuehsig** [comment]
Be aweare that dotnet electonize build require that the electron packer is installed globally via npm.

**Comment by robertmuehsig** [comment]
Electron comes with this electron.cmd, unfortunately we forgot to invoke the "electron" bash script when we are not on Windows. My commit should resolve this and this will be part of v0.0.6.

**Comment by robertmuehsig** [comment]
Ups - the start command still has some windows specifics in it.

**Comment by robertmuehsig** [comment]
Ok - the same "logic" that I use in the build command is now part of the start command as well. With 0.0.6 you (or when you refresh your local sources and clean the NuGet cache (e.g. via th devCleanup inside the CLI project)) it should hopefully work.

**Comment by robertmuehsig** [comment]
I released Version 0.0.6.

**Comment by r105m** [comment]
You say 
>  "Be aweare that dotnet electonize build require that the electron packer is installed globally via npm."
Using of global node modules is not very good idea. User should not be able to run commands as root.   
For what purpose u use global node modules? Just because u can do it?
Can u just use node_modules folder from project?

**Comment by robertmuehsig** [comment]
I opened a new issue regarding the global electron packer - TBH: I don't know if it would also work without the globally installed package. If yes, then I would prefer it as well, but I tried it once and failed, but I can't remember why 😃
