### ISSUE TITLE
Electron.GlobalShortcut.Register // Disabled key, in other app

### ISSUE THREAD

**Issue by nurbat** [ElectronNET/Electron.NET#360]
NET.CORE

After the application starts, we go to another program. also we press the button.
Our program reads the key, but the focus in another program no longer sees this letter.. Even if you go to the notebook. The key is not fulfilled.

![изображение](https://user-images.githubusercontent.com/5789051/71197217-ccd3e180-2299-11ea-8dee-85a7dfac34f4.png)

**Comment by nurbat** [comment]
It 's not exactly a bug, but even some fiche. It wouldn 't be bad if you could turn off or turn on extra...
Whatever global key is disabled for other programs or not disabled

**Comment by GregorBiswanger** [comment]
Hi @nurbat, you can easily determine that yourself using program logic. 

Subscribe to the `App.OnBlur` event and deregister the global shortkey with `Electron.GlobalShortcut.Unregister`. 

With the `App.OnFocus` event you can register your shortcuts again.
