### ISSUE TITLE
Logging with Serilog File Sink does not work

### ISSUE THREAD

**Issue by srameh** [ElectronNET/Electron.NET#362]
I am using Serilog for logging to a file. It works when I run the site on the web. But when I run it as Electron NET app it does not write any log. When I change the Sink from File to Console it spits the logs on the console screen. 
Is anyone aware of this issue?

**Comment by robalexclark** [comment]
I'm not aware of any issue but I am using serilog to log to file using the following setup code in Program.cs:

```
  Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .WriteTo.File(Path.Combine(Path.GetTempPath(), AppName + "-" + DateTime.Now.ToString("yyyyMMddHHmmss")) + ".log")
                .CreateLogger();
```

**Comment by srameh** [comment]
I found out the issue. If the are stored inside the wwwroot then the app has the permission to write them. If they are anywhere outside of the wwwroot then it will not write the log nor it will give any errors.
