### ISSUE TITLE
problem with HostHook

### ISSUE THREAD

**Issue by speedi57** [ElectronNET/Electron.NET#367]
I want to use custom-electron-titlebar with electron.net 
so I have create an HostHook and i Have add the package :
```
"custom-electron-titlebar": "^3.2.1"
```
and I have edit the index.ts with this code :

```
import * as Electron from "electron";
import { Connector } from "./connector";
import { Titlebar, Color } from 'custom-electron-titlebar'
export class HookService extends Connector {
    constructor(socket: SocketIO.Socket, public app: Electron.App) {
        super(socket, app);
        let titlebar = new Titlebar({
            backgroundColor: Color.fromHex('#34495'),

        });
    }

    onHostReady(): void {
    }
}

```
In ElectronHostHook/node_modules I can see the node module but it doesn't wokr ( nothing append )

but if I manualy edit the package.json from obj/host/package.json for add my module it work,
the problem, when I use electronize start it overwrite my edit,
It's possible to create a custom package.json ?

**Comment by speedi57** [comment]
sorry my script need to be in front htlm not in Host hook

**Comment by Melethainiel** [comment]
Hi @speedi57,
I have the same problem, but I can't find how to do it... Can you explain a bit more please ?

**Comment by speedi57** [comment]
The easiest way I found was to use ElectronNET.CLI from source and modify the package.json of ElectronNET.Host to add the dependencies I needed, I don't know if since my problem another solution was found
