### ISSUE TITLE
Application crashes when window is hidden and then restored on Windows

### ISSUE THREAD

**Issue by Velorien** [ElectronNET/Electron.NET#372]
* **Version**: 7.30.2

* **Target**: .NET Core 3.1 on Windows x64

This is not really a bug in Electron.NET, but in Electron itself [[see the issue](https://github.com/electron/electron/issues/21614)]. The latest version of Electron.NET suffers from this bug, so I wanted to share this here, so that you won't need to get frustrated as I did and waste half the day in Google.

*Workaround*: use the previous version of Electron.NET which doesn't have this bug.

**Comment by GregorBiswanger** [comment]
Is it fixed with electron in version 8?

**Comment by Velorien** [comment]
@GregorBiswanger if I understood correctly, they fixed it in one of Electron 8 pre-releases and shipped the fix in 8.2.

**Comment by Velorien** [comment]
I've verified that it's fixed in the latest release 🎉
