### ISSUE TITLE
BrowserWindowOptions is not setting Width and Height properly

### ISSUE THREAD

**Issue by sachin-devitpl** [ElectronNET/Electron.NET#373]
I have tried to set the exact Width and Height of the window from BrowserWindowOptions in the Startup.cs but it is not setting it properly. I have set like this - 
```
            var options = new BrowserWindowOptions
            {
                Frame = false,
                Width = 1280,
                Height = 720
            };

```
but it is setting 1294 x 727 pixel
If I am not using `Frame = false` then it is generating proper output 1280 x 720 px but I think there is some issue with using both of this parameters.

**Comment by sachin-devitpl** [comment]
Temporary work around is setting Max Width & Max Height
```
            var options = new BrowserWindowOptions
            {
                Width = 1280,
                Height = 720,
                Frame = false,
                MaxWidth = 1280,
                MaxHeight = 720,
            }
```

**Comment by GregorBiswanger** [comment]
Fixed with the new Electron.NET Version 8.31.1.
