### ISSUE TITLE
there should be an option to provide custom package.json in electronize start also

### ISSUE THREAD

**Issue by Sachin4dotnet** [ElectronNET/Electron.NET#375]
There is an option to provide custom package.json in `electronize build` but not in `electronize start`.
It should be there also for development purpose.
For example 
`electronize start /package-json "mycustom-package.json" `

**Comment by GregorBiswanger** [comment]
What do you want to do with your package.json? Have you tried the Electron HostHook feature yet?

**Comment by Sachin4dotnet** [comment]
Yes, but sometime some packages are dependent on node and electron versions also which are added in package,json 
For example [iohook ](https://www.npmjs.com/package/iohook)

**Comment by GregorBiswanger** [comment]
Electron.NET is not compatible with lower versions of Electron. It all depends on the Electron.NET versioning. As an example the next version will be: 8.31.1 - 8 stands for the supported electron version. The 31 for .NET Core 3.1 - and the 1 for our release from the new Electron version.

Compatibility for an electron / node version can be introduced with the `electron-rebuild` super package.

Alternatively, you can manage the Electron HostHook manually different package.json files yourself.
