### ISSUE TITLE
SetTitle method Unable to display Chinese on mac

### ISSUE THREAD

**Issue by jlcool** [ElectronNET/Electron.NET#377]
* **Version**: 7.30.2

node v12.11.1
electron 5.0.8

* **Target**: mac 10.14

Steps to Reproduce:

browserWindow.SetTitle("中文");
Unable to display Chinese

**Comment by GregorBiswanger** [comment]
@robertmuehsig can you please test it with your mac.

**Comment by jlcool** [comment]
It's about the coding of the startup.cs. Just change it to utf8
