### ISSUE TITLE
Notarize app for MacOS Catalina

### ISSUE THREAD

**Issue by DevAsmob** [ElectronNET/Electron.NET#384]
Hello,

Notarize app for MacOS Catalina is planned ?

Like electron js
https://github.com/electron/electron-notarize

Thanks

**Comment by GregorBiswanger** [comment]
I don't have a Mac device, sorry ;)

Maybe someone from the community might build something for this?!

**Comment by GregorBiswanger** [comment]
You can use it yourself with our HostHook feature. See our API demo app at **"Execute your own TypeScript code"**

https://github.com/ElectronNET/electron.net-api-demos

**Comment by DevAsmob** [comment]
The **"Execute your own TypeScript code"** in your API demo app allow to execute HostHook feature inside app already launched.

Notarize app for MacOS Catalina must be executed during build, like signing in your build process.
![Capture d’écran 2020-05-11 à 14 41 53](https://user-images.githubusercontent.com/62430167/81563428-855c0800-9396-11ea-91e3-c180e4cdebcb.png)

Are you sure i can use your HostHook feature to notarize app for mac osx ?

**Comment by kristianklok** [comment]
For future reference, this helped us out a lot when facing the same issue:

https://david.dev/how-to-notarize-your-electron-app/
