### ISSUE TITLE
Expose Electron.NET IPC bridge  as dependency services

### ISSUE THREAD

**Issue by danielmeza** [ElectronNET/Electron.NET#385]
Expose Electron.NET IPC bridge  as dependency services so that they can be injected in the controller instead of access it statically.

**Comment by danielmeza** [comment]
We can create also an abstaction.

**Comment by GregorBiswanger** [comment]
That's a good idea! I'll go through that.

**Comment by GregorBiswanger** [comment]
Okay, in principle the current solution is easier. You don't need an injection. You can easily access the static functions. I would see no advantage behind it. Alternatively, you could write your own service as a facade.

**Comment by danielmeza** [comment]
Th utility of this is to unit test because we can remplace all parts, If we can provide this as services then we only need to do the fakes! and not the entire facade.

**Comment by GregorBiswanger** [comment]
You can already register the Electron class with Services ... that should work ...
