### ISSUE TITLE
ElectronNET initializing but not running app on Ubuntu 18 and Fedora 29

### ISSUE THREAD

**Issue by rakista112** [ElectronNET/Electron.NET#388]
* **Version**: 7.30.2

* **npm version**: 6.9.0
* **NET Core**: 3.1

* **Target**: Linux (Ubuntu 18, Fedora 29)

The dotnet app backend continues running in the background but the UI freezes.
The part of the screen where the app UI opened gets stuck on the UI. 
UI can't be interacted with

Steps to Reproduce:

1a. Make any basic Electron app in Linux and run via electronize start
1b. Package app via fpm option in the electron.manifest.json
   2b. Run application executable 

I made a basic Electron app. 
This was created from dotnet new mvc and I added the code from the repo README.
I tested with other applications that work on Mac and Windows and they still froze.
Here's the app I'm testing with right now. https://github.com/rakista112/electron-linux-error

Looking forward to hearing from you! 
Thanks

**Comment by rakista112** [comment]
I disabled GPU on the Parallel's Hardware configuration and it worked. 
Do we have an API for this in .NET? If not, I'll inject it in Host

**Comment by GregorBiswanger** [comment]
It sounds like a native electron problem. Have you checked for this yourself at Electron?
https://github.com/electron/electron

**Comment by rakista112** [comment]
I haven't checked yet, I'll try and ask them. Thanks
