### ISSUE TITLE
Unable to disable WebSecurity along with NodeIntegration enabled

### ISSUE THREAD

**Issue by drozdzamadeusz** [ElectronNET/Electron.NET#389]
* **Version**: 7.30.2

* **Target**: Windows

Setting <code>NodeIntegration</code> to <code>true</code> results in overwriting all other options in <code>WebPreferences</code> to its defaults. So it is impossible to use `NodeIntegration = true` along with `WebSecurity = false`, because  `WebSecurity` value will be ignored.

Steps to Reproduce:
This can be reproduced using simple new generated electron app

            await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions
            {
                Show = true,
                WebPreferences = new WebPreferences
                {
                    AllowRunningInsecureContent = true,
                    WebSecurity = false,
                    NodeIntegration = true,
                },
            });

**Comment by GregorBiswanger** [comment]
Fixed! Will be released with Electron.NET version 8.31.1.
