### ISSUE TITLE
Can't start my app

### ISSUE THREAD

**Issue by Petermarcu** [ElectronNET/Electron.NET#39]
I'm running `dotnet electronize start` and it stops at:

`stdout: Use Electron Port: 8002`

I'm using .NET Core 2.0 and Node 8.9. Is that going to work? Any ideas? What other info would be helpful? Should I expect my app to come up when I run start?

**Comment by robertmuehsig** [comment]
Does dotnet electronize build work on our machine and can you open the produced application in the /bin/desktop folder? 
The start command seems to have some problems unfortunately.

**Comment by Petermarcu** [comment]
Yes build worked and there was an 80MB exe in there but it wouldn't launch. I Also installed electron globally and tried `electron .` in /bin/desktop folder and it said it couldn't find an app.

**Comment by robertmuehsig** [comment]
Did you use a brand new ASP.NET Core application or the WebApp demo in this repo?

**Comment by Petermarcu** [comment]
I did a new one. I'll try the sample.

**Comment by Petermarcu** [comment]
Ok, after the fix with the PR I just made for the package version, I was able to `dotnet electronize start` the sample application.

I did `dotnet new web` to create the app and then copied in the content from the README.md instructions. I hit the launchSetting.json bug and copied that over. I wonder if there are other differences.

**Comment by robertmuehsig** [comment]
Mhh - if you are working with this repository you will need to make sure that under /artifacts are the "dev" NuGet packages (versioned with 1.0.0.0), otherwise it will fall back to the versions on NuGet.org and then it is chaos. 

Current approach:
Build the CLI & API, then you should see the NuGet packages under /artifacts. This directroy is configured as a NuGet source and will be consumed from the WebApp. Especially the CLI project is pretty weird, because NuGet is really aggressiv in caching dotnet CLI extensions. 
See https://github.com/ElectronNET/Electron.NET/wiki#dev-notes .

**Comment by Petermarcu** [comment]
Ok, do you think it would be worth having a sample that doesn't require knowing the dev workflow for the repository?

**Comment by robertmuehsig** [comment]
That's the idea behind those repos: https://github.com/ElectronNET/electron.net-api-demos & https://github.com/ElectronNET/electron.net-musicplayer-sample 
@GregorBiswanger created those and I think they only use the NuGet versions (but be aware to clean the NuGet cache, otherwise you might work with dev-bits)

**Comment by Petermarcu** [comment]
great. Didn't know about those. After building the repository, 0.0.5 resolved for me.

**Comment by robertmuehsig** [comment]
Great! We are working on better documentation & more demos. The "WebApp" project here is just our playground.

**Comment by Petermarcu** [comment]
Actually, I'm reopening this one. I meant to close the PR. I still haven't gotten my normal app working.

**Comment by Petermarcu** [comment]
What I have done is confirm that when I create the application in visual studio, it works. So there is a problem with the difference between the Visual Studio template and the dotnet new template.

**Comment by robertmuehsig** [comment]
Ah - via dotnet new it doesn't work? Mhh...

**Comment by Petermarcu** [comment]
Thats right. I'm diffing now.

**Comment by Petermarcu** [comment]
This was missing from the `dotnet new` template in Startup.cs.

```
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }
```

**Comment by robertmuehsig** [comment]
I thought those lines are more or less required to run a ASP.NET Core app or is this just a bug with the templates?

**Comment by Petermarcu** [comment]
They are required to run an MVC app. `dotnet new web` is supposed to just be a blank app. Does Electron.NET assume mvc?

**Comment by Petermarcu** [comment]
I'm guessing it would have worked fine if I did `dotnet new mvc`.

**Comment by robertmuehsig** [comment]
Ah - currently yes, because we use it to serve the HTML pages that the Electron part is showing.

**Comment by Petermarcu** [comment]
Looking at the getting started "configure method", my question is anwwered.

```
app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
    });
```

I'll close this issue unless you want to add a note to the readme to mention that mvc is required and to make sure those lines are in the Startup.cs.

**Comment by Petermarcu** [comment]
No problem.

**Comment by robertmuehsig** [comment]
I'm closing this one - ok?

**Comment by Petermarcu** [comment]
👍
