### ISSUE TITLE
Build fails for win-x64 under linux

### ISSUE THREAD

**Issue by ThuCommix** [ElectronNET/Electron.NET#395]
* **Version**: 
    * API: 8.31.1
    * CLI: 8.31.1

- dotnet core sdk 3.1
- nodejs 12.x

* **Target**: 
    * win-x64

I'm trying to setup a build for my electron app for multiple platforms: win-64x, linux-x64 and osx. After having giant trouble even with the linux build I rolled my own image and got it working. For example I needed to install the electron-builder globally because when just running electronize build I had got an error claiming that the post install of ejs failed. 

However: Building for win-x64 in a docker container is currently not possible:

```
Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false
```

I think the flag was introduced a couple of commits ago. Is this expected behaviour or should the build work for win-x64 under linux?

Steps to Reproduce:

1. Pull thucommix/dotnetsdk-electron:3.1_12 (for example or setup node in a dotnet sdk image yourself)
2. Try to build any blazor starter project using: electronize /target win

**Comment by GregorBiswanger** [comment]
I activated `PublishReadyToRun` by default because it had improved the startup speed enormously. I will build a command to disable it for the next version 8.31.2.

**Comment by ThuCommix** [comment]
If you're busy I can help you out with a pull request.

**Comment by GregorBiswanger** [comment]
Thanks for your offer! We can always use reinforcements :) 
Trigger me on gitter, if you want to participate.

I have already implemented this feature. With the next update **8.31.2** you can use the following command:
`electronize build /target win /PublishReadyToRun false`

or

`electronize start /PublishReadyToRun false`

Alternatively, it is active by default.
