### ISSUE TITLE
Blank WebApp fails to start

### ISSUE THREAD

**Issue by robertmuehsig** [ElectronNET/Electron.NET#4]
Repo:
Create new ASP.NET Core 2.0 webapp
Install API & CLI Package
dotnet initialize init 
dotnet initalize build

=> open ElectronNET.Host.exe

Nothing happens :(

**Comment by GregorBiswanger** [comment]
Do you add the UseElectron extension in Program.cs?

`public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                **.UseElectron(args)**
                .Build();`

And open a Window in Startup.cs?

`Electron.WindowManager.CreateWindowAsync();`

**Comment by robertmuehsig** [comment]
Works!

But: We need to add the UseElectron(args) method in your readme @GregorBiswanger (currently it is missing and without it, it doesn't work)
```
  public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseElectron(args)
                .Build();
```
