### ISSUE TITLE
Not working Dropdown and Popup (bootstrap)

### ISSUE THREAD

**Issue by graylobo** [ElectronNET/Electron.NET#400]
* **Version**:  8.31.2

* **Target**: window

I make some Blazor page. github code link is below
https://github.com/graylobo/BlazorElectron
![20200514_181350](https://user-images.githubusercontent.com/37823841/81916423-c2323400-960e-11ea-9344-09f4c90f48e3.png)

If I run it in browser, dropdown effect and popup effect work's good,
but if I run it in Electron.net, it doesn't work 
![20200514_181903](https://user-images.githubusercontent.com/37823841/81916891-69af6680-960f-11ea-9019-03f4609602cb.png)

Can I fix this problem?

**Comment by GregorBiswanger** [comment]
Electron cannot find your jQuery instance. 

![image](https://user-images.githubusercontent.com/7336300/82092146-fda92d00-96f8-11ea-8966-5bc59ab4f734.png)

To do this, you have to deactivate the node integration. This automatically changes everything to CommonJS. **Important!** If it is deactivated, you cannot use Electron.NET IPC communication. Then please use the standard communication from Blazor with your C# code.

**Start without node integration:**

```
Task.Run(async () => {
    var browserWindowOptions = new BrowserWindowOptions
    {
        WebPreferences = new WebPreferences
        {
            NodeIntegration = false
        }
    };
    await Electron.WindowManager.CreateWindowAsync(browserWindowOptions);
});
```
**Then it works:**

![electron-net-blazor-jquery](https://user-images.githubusercontent.com/7336300/82092349-67293b80-96f9-11ea-88de-081e5f0479f7.gif)

**Comment by romuloteixeira** [comment]
Hi,
I used this solution and worked for me.
[https://github.com/ElectronNET/Electron.NET/issues/329#issuecomment-546612899](url)

Example:
![image](https://user-images.githubusercontent.com/40904138/117655311-ce53c180-b18e-11eb-8697-58458ebc7509.png)
