### ISSUE TITLE
Submenu not shown

### ISSUE THREAD

**Issue by graylobo** [ElectronNET/Electron.NET#401]
* **Version**: 8.31.2

* **Target**: 

I'm trying to make 'One' menu, and 'Two' submenu.
my code is below 

`
Task.Run(async () => {
                var options = new BrowserWindowOptions { Show = true };
                Electron.Menu.SetApplicationMenu(new MenuItem[] { new MenuItem { Label = "One" ,Submenu = new MenuItem[] { new MenuItem {Label="Two" } } } });
                await Electron.WindowManager.CreateWindowAsync();
            });
`

It makes 'One' menu, but nothing happen when i click it.
![20200514_183345](https://user-images.githubusercontent.com/37823841/81919252-90bb6780-9612-11ea-9f92-2be8dcb1b5d3.png)
And this github demo also does not display submenu.
https://github.com/ElectronNET/electron.net-api-demos
Can i know what am I missing?

**Comment by GregorBiswanger** [comment]
You forgot to set the type for it as a submenu:

```
Task.Run(async () =>
{
    var menu = new MenuItem[]
    {
            new MenuItem
            {
                Label = "One",
                Type = MenuType.submenu,
                Submenu = new MenuItem[]
                {
                    new MenuItem
                    {
                        Label = "Two"
                    },
                    new MenuItem
                    {
                        Label = "Three"
                    }
                }
            }
    };

    Electron.Menu.SetApplicationMenu(menu);

    await Electron.WindowManager.CreateWindowAsync();
});
```

![electron-net-submenu-problem](https://user-images.githubusercontent.com/7336300/82088750-9b4d2e00-96f2-11ea-80b9-9996674ad5be.gif)
