### ISSUE TITLE
Not calling RestAPI 

### ISSUE THREAD

**Issue by graylobo** [ElectronNET/Electron.NET#403]
* **Version**: 8.31.2

* **Target**:  

<img width="911" alt="20200517_203428" src="https://user-images.githubusercontent.com/37823841/82143714-eeed8200-9880-11ea-9207-749135ec2c33.png">
I'm trying to call RestAPI data, using httpclient library in nuget.

<img width="1917" alt="20200517_205822" src="https://user-images.githubusercontent.com/37823841/82146507-cc119c80-9885-11ea-9519-305e6c2ab290.png">
<img width="1385" alt="20200517_213450" src="https://user-images.githubusercontent.com/37823841/82146582-46422100-9886-11ea-8220-b41e2f613bb9.png">

It works fine in the browser, but if I build it with electron.net in the same environment and click it, 
there is no response.
github code link is below
https://github.com/graylobo/BlazorTron
Can I fix this issue? thanks in advance

**Comment by konstantingross** [comment]
Your ElectronNET port does not match the port of the RestAPI call.

Add following line to your Program.cs:
webBuilder.UseStartup<Startup>();
webBuilder.UseUrls("http://*:8001"); //e.g. 8001

RestAPI.razor:
Students = await http.GetJsonAsync<List<Student>>("http://localhost:8001/api/students");

![image](https://user-images.githubusercontent.com/6459825/82153392-70381b00-9867-11ea-8825-2c4e89965a42.png)

**Comment by graylobo** [comment]
Thank you. It works well thanks to your advice.
![20200518_100119](https://user-images.githubusercontent.com/37823841/82165174-f3e91a80-98ee-11ea-8ec1-3aca01f87d7a.png)
However, it does not move to the json page when i click the button

**Comment by konstantingross** [comment]
Try this but I don't know if this is best practice:
`new MenuItem { Label = "Home", Click = () => Electron.WindowManager.BrowserWindows.First().LoadURL("http://localhost:8001/")`

**Comment by GregorBiswanger** [comment]
The safest way would be:
`new MenuItem { Label = "Home", Click = () => Electron.WindowManager.BrowserWindows.First().LoadURL($"http://localhost:{BridgeSettings.WebPort}/")`

Did we solve your problem?

**Comment by graylobo** [comment]
Yes, it works perfect. Thanks a bunch!
