### ISSUE TITLE
Pass configuration profile to electronize

### ISSUE THREAD

**Issue by nazar322** [ElectronNET/Electron.NET#407]
I work on a cross-platform project that supposes to run on both Mac and Windows. To avoid code duplicates I have classes that mostly share the same code but might have platform-specific areas that I distinct from the rest of the code with `#if WINDOWS` for instance. Then I have created configuration profiles for each Windows and Mac builds that define symbols I need to compile my project for the platform I need.
The problem with `electronize` is that I cannot pass my configuration profile and therefore, because my code dependent on predefined symbols, `dotnet publish` fails to build my project.
Please add a command argument to pass the configuration profile to both `electronize build` and `electronize start` commands.

**Comment by GregorBiswanger** [comment]
Have you tried the following command?
`electronize start /args ASPNETCORE_ENVIRONMENT="Development"`

**Comment by GregorBiswanger** [comment]
With .NET Core you can use native methods:
`bool isWindows = System.Runtime.InteropServices.RuntimeInformation
                                               .IsOSPlatform(OSPlatform.Windows);`

**Comment by GregorBiswanger** [comment]
I see, we have already the following command:
`electronize start /dotnet-configuration development`

Works?

**Comment by nazar322** [comment]
> With .NET Core you can use native methods:
> `bool isWindows = System.Runtime.InteropServices.RuntimeInformation .IsOSPlatform(OSPlatform.Windows);`

It's an option to check for the platform in the runtime, but I also have executables embedded as a resource both for Mac and Windows and in order to embed a correct resource I use confitional including in csproj, like in the example below.
```
<Choose>
	<When Condition="'$(Configuration)' == 'Debug (Windows)' or '$(Configuration)' == 'Release (Windows)'">
	  <ItemGroup>
		<EmbeddedResource Include="ffmpeg.exe.gz" />
	  </ItemGroup>
	</When>
  </Choose>
  <Choose>
	<When Condition="'$(Configuration)' == 'Debug (OSX)' or '$(Configuration)' == 'Release (OSX)'">
	  <ItemGroup>
		<EmbeddedResource Include="ffmpeg.gz" />
	  </ItemGroup>
	</When>
  </Choose>
```
So I still need to pass the configuration needed.

**Comment by nazar322** [comment]
> I see, we have already the following command:
> `electronize start /dotnet-configuration development`
> 
> Works?

Unfortunately, it didn't work.
The following `dotnet publish` command does not contain `--configuration` argument. It is the same as when not passing `/dotnet-configuration` argument.
However, when I use the same `dotnet publish` command `electronize start` produces but just append `--configuration MYCONFIGURATION` it builds well.
I also have not found any references to `/dotnet-configuration`  in StartElectronCommand.cs.
By the way, here is my version of Electron.NET CLI
`ElectronNET.CLI Version: 8.31.2.0`

**Comment by konstantingross** [comment]
#409
