### ISSUE TITLE
Missing NotificationOptions Option

### ISSUE THREAD

**Issue by AykutToprak** [ElectronNET/Electron.NET#408]
* **Version**:  8.31.1

* **Target**: .NET Core 3.1

timeoutType option configuration is missing. Notifications are closed a few second later automatically. Is there any workaround to make notification permanent?

[https://www.electronjs.org/docs/api/notification#notificationtimeouttype-linux-windows](url)

**Comment by konstantingross** [comment]
No not without the timeoutType parameter. When I get home later, I'll take a look at it.
