### ISSUE TITLE
Customize author/description is still broken

### ISSUE THREAD

**Issue by AykutToprak** [ElectronNET/Electron.NET#419]
* **Version**: v8.31.2

* **Target**: .NET Core 3.1

try to customize author and description as below (as mentioned in #310 )

"executable": "Test",
  "splashscreen": {
    "imageFile": ""
  },
  "author": "Test author",
  "description": "Test description"

But author is still "Gregor Biswanger" and description is still "Electron-Host for Electron.NET."

**Comment by GregorBiswanger** [comment]
I tested it again and it works for me?!
What operating system do you have and where do you read other information?

`
{
  "executable": "ElectronNETIssue419",  
  "splashscreen": {  
    "imageFile": ""  
  },  
  "name": "ElectronNETIssue419",  
  "author": "Max Mustermann",  
  "description": "Only a test description.",  
  "singleInstance": false,  
 ...  
`

![image](https://user-images.githubusercontent.com/7336300/83207202-dd468d00-a152-11ea-92d0-09ff6daf09b6.png)

**Comment by MarkBQE** [comment]
Greg,

I have the same issue. manifest file has no affect, I am using Windows 10.
![image](https://user-images.githubusercontent.com/23547957/83209882-3dffa680-a10e-11ea-85a1-bed06421da4b.png)

**Comment by AykutToprak** [comment]
My  operating system is Windows 10. as @MarkBQE said manifest file has no affect. i used custom package.json for work around as `electronize build /target win /package-json "./package.json"` to solve problem.

**Comment by GregorBiswanger** [comment]
@MarkBQE Is this the build version? Or with electronize start?

Which version of Node.js and Electron.NET do you have?

**Comment by MarkBQE** [comment]
This is electronize start, in build it works as expected.

**Comment by GregorBiswanger** [comment]
ahh okay, that explains a lot :) it only works with the finished build version...

Isn't that really relevant during development?!

**Comment by MarkBQE** [comment]
I realized that it works in build after I posted this. I am OK with it the way it is as of now. I appreciate you looking into this. Keep up with the good work.
