### ISSUE TITLE
Cannot "electronize init" without following Error

### ISSUE THREAD

**Issue by Nydery** [ElectronNET/Electron.NET#424]
* **Version**: API and CLI 8.31.2 on .NET Core 3.1

* **Target**: Windows 10

Description: I can't "electronize init" my project without getting the error shown in the picture provided.
![electron_error](https://user-images.githubusercontent.com/45046492/83537699-3288f280-a4f5-11ea-85b8-f2af1faa7f3f.jpg)

Steps to Reproduce:
1. Create a new Project
2. Do what is described in README.md
3. run "electronize init"
and I get the mentioned error.

**Comment by jackcaldwell** [comment]
I'm currently having the same issue.

**Comment by Nydery** [comment]
in my case, i was a folder before the right one, so maybe you have to move on one folder.
