### ISSUE TITLE
Blazor WebAssembly Support

### ISSUE THREAD

**Issue by IRHM** [ElectronNET/Electron.NET#426]
I have used Blazor Server with ElectronNET and it has worked perfectly, but it doesn't seem to work with Blazor WASM.

**Comment by Anseltis** [comment]
It would be better than awkward Blazor Server

**Comment by GregorBiswanger** [comment]
I'm currently not fit in Blazor Server.. maybe my **[Electron.NET - Contributing Getting Started
](https://youtu.be/Po-saU_Z6Ws)** video on YouTube will help you to test it yourself, where there is the problem?!

**Comment by sbondo1234** [comment]
@GregorBiswanger I can take a gander, but no promises.

**Comment by sbondo1234** [comment]
`electronize start` causes this error:

https://i.vgy.me/ddA4bP.png

It's not showing the full path to the `.exe` so maybe it is wrong, I don't know how I would check or change the path that it is looking for.

**Comment by Delpire** [comment]
@IRHM I am getting a similar issue, but I am using Blazor Server, so I don't think its related to WASM. It works when I use `electronize start /watch` but I error when I use the command as you have.

**Comment by ekuchynski** [comment]
> `electronize start` causes this error:
> 
> It's not showing the full path to the `.exe` so maybe it is wrong, I don't know how I would check or change the path that it is looking for.

Getting the same error. Did you managed to find a solution?

**Comment by IRHM** [comment]
@ekuchynski Nope, I'm just waiting for an expert.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
