### ISSUE TITLE
Hosthook.CallAsync<T> blocks execution when exception occurs inside

### ISSUE THREAD

**Issue by freosc** [ElectronNET/Electron.NET#427]
API and CLI 8.31.2

* **Version**: 8.31.2

.net core 3.1, node 12.16.3

* **Target**: Windows 10

When using HostHook.CallAsync<T>(), my call is blocked when an exception occurs inside the CallAsync method, and code after my CallAsync doesn't get executed.
I updated the on complete handler in your HostHook.CallAsync<T>() code like this:
```
...
catch (Exception exception)
                {
                    taskCompletionSource.SetException(exception);
                    //Don't use the following line, as it blocks execution in the calling method
                    //throw new InvalidCastException("Return value does not match with the generic type.", exception);
                }
...
```
Which redirects the exception to the calling code, where I can catch it, and resolves this issue.
I guess the same "SetException" code should be used in the on error handler, to be sure that the code doesn't block the caller.

Steps to Reproduce:

1. Inside ElectronHostHook/index.ts i have this test code:
```
...
onHostReady(): void
    {
        // execute your own JavaScript Host logic here
        this.on('test', async (id, done) =>
        {
            try
            {
                console.log("test called", id);
                done(id);
                console.log("test end");
            } catch (ex)
            {
                console.log("ex occurred in test", ex);
            }
        });
    }
...
```
2. Inside my electron.net calling logic in .net:
```
...
 _mainWindow.OnReadyToShow += async () =>
                {
                    _logger.LogInformation("Browser ready to show");
                    _mainWindow.Show();
                    _logger.LogInformation("test");
                    int test = -1;
                    try
                    {
                        //code execution will block here
                        test = await Electron.HostHook.CallAsync<int>("test", 132);
                    }
                    catch (Exception ex) {
                        _logger.LogError(ex, "Error in test in OnReadyToShow");
                    }
                    _logger.LogInformation("get test {id}", test);
                };
...
```
The code above will block, unless the "taskCompletionSource.SetException(exception);" is used in the CallAsync<T>() code.
In that case, I can catch the Exception that occurs (System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.). There's no issue with the exception though, that's clear, I have to use a long instead of an int.

**Comment by GregorBiswanger** [comment]
Would you like to submit a pull request to us? [Electron.NET - Contributing Getting Started](https://youtu.be/Po-saU_Z6Ws)

**Comment by freosc** [comment]
Sure
