### ISSUE TITLE
Add Node Packages to solution

### ISSUE THREAD

**Issue by newblord** [ElectronNET/Electron.NET#43]
Is it possible to add other node packages to be used with Electron.

For instance i wanted to add NodeGit.

**Comment by robertmuehsig** [comment]
Oh - great question! @GregorBiswanger, any ideas? Maybe users could add additional npm packages in the electron.manifest.json and we install them and to invoke them we would need a more generic API, something like Electron.Invoke(...)?

**Comment by tebeco** [comment]
i'm not a maintener here, but it might be a good idea to think OPT-IN for few feature in order to decouple stuff and avoid a monolith effect on init and code ;)

**Comment by GregorBiswanger** [comment]
It´s a good idea.. I marked it as a feature request.. We can implement it..

**Comment by GregorBiswanger** [comment]
@newblord & community: How do you like to use the integration feature? To include a npm package is one part.. but how do you like to integrate own node code? I think to use **electron-edge** is here a good solution.. but I have not tried it before..

Or should we execute a own javascript file in electrons node container? 
As example: 

1. You have a JS-File with your logic in node. 
2. In Electron.NET call `Electron.Invoke("myLogic.js");`

Do you like the second one? It´s easy for me to implement it..

**Comment by yoDon** [comment]
@GregorBiswanger did you guys remove the stock node backend when you added the dotnet backend? If not, couldn't we just run the JS in the node backend (where it would behave the way one would expect). If the stock node backend was removed, would it be possible to have a config setting that adds it back in when desired?

**Comment by thEpisode** [comment]
Hi, I'm interested on this feature to add code in startup, @GregorBiswanger I see you working on it, could you give me any way to use?

**Comment by GregorBiswanger** [comment]
Hi @thEpisode 
yes, we are working on it right now. The next release will bring some exciting features:
https://github.com/ElectronNET/Electron.NET/milestone/5

If you're interested, you can test the new feature for us today. Just let me know.

Best,
Gregor
