### ISSUE TITLE
Get properties that use Task.Run().Result seem to block execution

### ISSUE THREAD

**Issue by freosc** [ElectronNET/Electron.NET#431]
* **Version**: latest from github 9.31.1 

.net core 3.1 node 12.16.3

* **Target**: win

Steps to Reproduce:

1. In the demo Electron.Net WebApp, in ElectronBootstrap, I added these lines of code
```
Console.WriteLine("set AllowDowngrade");
Electron.AutoUpdater.AllowDowngrade = true;
Console.WriteLine("get AllowDowngrade");
//Code execution blocks on the following line
bool allowDowngrade = Electron.AutoUpdater.AllowDowngrade;
Console.WriteLine("AllowDowngrade: " + allowDowngrade);
```
2. The set property works fine, but I noticed that the get property blocks execution, so the console won't show the last line in the code block above.
Inside the property getter code I see that the code is executed correctly, but the socket.on "autoUpdater-allowDowngrade-get-reply" event is never fired.

This bug occurs for all property getters in the electron.net code that use the Task.Run().Result pattern

(Sidenote: a few seconds after the code execution is blocked, the socket also disconnects)

**Comment by freosc** [comment]
I discovered that it does work in sync methods, and doesn't work in async methods.
If you put the example lines of code inside the Program.CreateWebHostBuilder, like this:
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            var x = WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, logging) => { logging.AddConsole(); })
                .UseElectron(args)
                .UseStartup<Startup>();

            Console.WriteLine("set AllowDowngrade");
            Electron.AutoUpdater.AllowDowngrade = true;
            Console.WriteLine("get AllowDowngrade");
            //Code execution blocks on the following line
            bool allowDowngrade = Electron.AutoUpdater.AllowDowngrade;
            Console.WriteLine("AllowDowngrade: " + allowDowngrade);

            return x;
        }
```
This will work. But it'll fail when ran from an async method such as the 
`public async void ElectronBootstrap()`
in your demo webapp, or in case somewhere upstream an async method is used.

I guess we're looking at the infamous async deadlock issue, described here.
[](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html)

**Comment by theolivenbaum** [comment]
Is there anyone working on the remaining .Result uses? Happy to jump with a PR if not...
