### ISSUE TITLE
Error accessing local resources

### ISSUE THREAD

**Issue by SimonSchoeni** [ElectronNET/Electron.NET#436]
Hello!

I'm currenlty using to Electron.NET to host an ASP MVC application. This application should be capable of displaying videos.

The videos are imported using the `file:///c:/local.../` format.
Whenever I try to access the video chromium tells me that it is not able to load the local resource: "Not allowed to load local resource: file///c:/local.../"...

When starting up electron, it uses the following options:
` var options = new BrowserWindowOptions()
            {
                WebPreferences = new WebPreferences()
                {
                    WebSecurity = false
                }
            };
            await Electron.WindowManager.CreateWindowAsync(options);`
As far as I understand this, the turned off WebSecurity feature should allow the underlying chromium to load local resources.... Is there anything else I may have forgotten to check?

**Comment by GregorBiswanger** [comment]
It should normally be sufficient to just deactivate WebSecurity. Possibly. do you want to access a directory without direct access? Have you already run the Electron app as admin? For test only? Did you test the path without an electron? 

I would always have the path put together by tools so that it remains a cross-platform.. Use `Path.Combine`..

**Comment by SimonSchoeni** [comment]
Hi!

I have access to the directories since I used Electron to save data in the same directory. 

I didn't really bother to run electron as admin since it should not be required since I'm able to store data to the directory.

I opened the file:/// link in chrome and I saw the file.

Thanks for the advice, I already use Path.Combine etc. :)

BR Simon

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
