### ISSUE TITLE
Dotnet Tool Manifest File Support

### ISSUE THREAD

**Issue by jacobestell** [ElectronNET/Electron.NET#437]
I don't like installing dotnet tools globally and with the new tools manifest file, it is no longer necessary.

It'd be great if you supported the manifest file for the debugging profile you add and updated the documentation to use the manifest file.

Thanks!

**Comment by GregorBiswanger** [comment]
You need the dotnet tools to start and create an Electron.NET app..

What is meant by new tools manifest file?

**Comment by cosmo0** [comment]
> What is meant by new tools manifest file?

I guess he refers to this: https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use

**Comment by jacobestell** [comment]
> You need the dotnet tools to start and create an Electron.NET app..
> 
> What is meant by new tools manifest file?

yes, what @cosmo0 said is correct!
Sorry I did not provide a link, I left this as a comment as I was checking out a few different options for electron in dotnet.

`dotnet tool update ElectronNET.CLI -g`
The idea here would be to include a dotnet cli tool manifest file in local repos instead of globally requiring the tool on the devs machine.
Similar to dev-includes in node modules vs global installed tooling.
