### ISSUE TITLE
Speech Recognition does not working in ElectronNET

### ISSUE THREAD

**Issue by ionutmihai1995** [ElectronNET/Electron.NET#438]
I have a Blazor application using Speech Recognition.

After using ElectronNET, the speech recognition does not working. In the logs it appears that microphone is ok, but I don't know why speech recognition does not work

**Comment by GregorBiswanger** [comment]
Do you have a small demo app for me?

Possibly. have you already tried it in the browser? Without Electron.NET?

**Comment by vinaykulkarni89** [comment]
Hi @GregorBiswanger  I am facing a similar issue with annyang (https://github.com/TalAter/annyang) library, works well in chrome

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
