### ISSUE TITLE
how to open only single instance of electronnet exe

### ISSUE THREAD

**Issue by jadhavrani123** [ElectronNET/Electron.NET#440]
Hello Sir,
I am trying to  open only one instance of app window.I am setting option in electron.manifest.json file singleinstance=true,
It works but when my exe is in system tray it doesnt get open when click on exe icon.I want your help  for that problem.Means when I click on exe icon the same window should get open which is in system tray.

**Comment by ThuCommix** [comment]
You can pass a delegate to Electron.App.RequestSingleInstanceLockAsync which will get called with the arguments (if any) of the new opened instance. In that delegate you need to restore the focus & visibility of your desired window.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
