### ISSUE TITLE
electron-builder | Unknown argument: .

### ISSUE THREAD

**Issue by JakStark** [ElectronNET/Electron.NET#444]
Electron.NET CLI: 9.31.1
Node.js: 12.18.2
.NET Core: 3.1
Target: win

When I launch command "electronize build /target win" I receive following error:
**Unknown argument: .**

I found that this error is throwed from file ElectronNET.CLI/Commands/BuildCommand.cs at line 189, after launched command "npx electron-builder . --config=./bin/electron-builder.json --win --x64 -c.electronVersion=9.0.3".

I saw that @rbaker26 fix this bug by removing extra dot so I tried to clone repo, build solution and replace electron dotnet-electronize.dll. In this way, now electron build successfully but when I launch the app, process is visible only in background.

**Comment by vituthanh** [comment]
me too

**Comment by hojlind** [comment]
This is a known issue, and is a duplicate of #441 
A PR (#443) has been created and should be up during today according to @GregorBiswanger

**Comment by HaydnDias** [comment]
This has been fixed in #443 as raised in #441 , I think the plan was to release it today. @JakStark @vituthanh

**Comment by vituthanh** [comment]
I hope Electron NET.CLI will be updated soon.

**Comment by vituthanh** [comment]
After replace dotnet-electronize.dll file from git source at folder
C:\Users\{username}\.dotnet\tools\.store\electronnet.cli\9.31.1\electronnet.cli\9.31.1\tools\netcoreapp3.1\any
My project was built successfully.

**Comment by rbaker26** [comment]
@vituthanh @JakStark 
Make sure you update the dotnet tooling (not automatic)
```bash
dotnet tool update --global ElectronNET.CLI
```
**On Windows**
![image](https://user-images.githubusercontent.com/31376573/86628570-ef4ff280-bf7e-11ea-9fb2-cf8b394739cc.png)
**On Linux**
![image](https://user-images.githubusercontent.com/31376573/86628737-2a522600-bf7f-11ea-8fde-97d3790fea48.png)

**Comment by rbaker26** [comment]
This is also noted in the README.md under **Important Notes** 
See #445 for up to date version numbers.

**Comment by GregorBiswanger** [comment]
Hey Community, we have released version 9.31.2 with the electron-builder fix! In addition, I have improved the socket problems again and updated to Electron 9.0.5.

**Comment by MarkBQE** [comment]
dotnet tool update --global ElectronNET.CLI command is not updating to version 9.31.2.0. Any help will be appreciated
