### ISSUE TITLE
X-Platform Building Broken - R2R

### ISSUE THREAD

**Issue by rbaker26** [ElectronNET/Electron.NET#446]
X-Platform Building does not work.  Seems to be a problem with Ready2Run (R2R).
This problem occurred for me after updating to 9.31.2.
For debugging, I tired the following test of both [My Project](https://github.com/rbaker26/SAP1EMU/) and the [Demo Project](https://github.com/ElectronNET/electron.net-api-demos)

* **Version**:  9.31.2.0

* **.NET Core**:  3.1.301

* **Target**: See Table

**Before 9.31.2**

| Build Platform | Target Win         | Target Linux       | Target OSX      |  
|----------------|--------------------|--------------------|-----------------| 
| Windows        | :heavy_check_mark: |:heavy_check_mark:          | :x:   *          |  
| Linux          | :heavy_check_mark:           | :heavy_check_mark: | :heavy_check_mark:            |  
| OSX            | :grey_question:    | :grey_question:    | :grey_question: |  

_* Windows to OSX was never supported due to symlinks_

**As of 9.31.2**

| Build Platform | Target Win         | Target Linux       | Target OSX      |  
|----------------|--------------------|--------------------|-----------------| 
| Windows        | :heavy_check_mark: | :x:                | :x: *           |  
| Linux          | :x:                | :heavy_check_mark: | :x:             |  
| OSX            | :grey_question:    | :grey_question:    | :grey_question: |  

_* Windows to OSX was never supported due to symlinks_

Now when building cross-platform targets, I get the following message:
> error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. 

**Note**: I will include the full error messages for the different platforms below.

According to [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#readytorun-images), 

> The ReadyToRun compiler doesn't currently support cross-targeting. You must compile on a given target. For example, if you want R2R images for Windows x64, you need to run the publish command on that environment.

Before updating to 9.31.2, I was able to build targets for other systems.

| Build Platform | Target Win         | Target Linux       | Target OSX      |  
|----------------|--------------------|--------------------|-----------------| 
| Windows        | :heavy_check_mark: | [win-to-linux-r2r.txt](https://github.com/ElectronNET/Electron.NET/files/4881912/win-to-linux-r2r.txt)            | :x: *           |  
| Linux          | [linux-to-win-r2r.txt](https://github.com/ElectronNET/Electron.NET/files/4881908/linux-to-win-r2r.txt)            | :heavy_check_mark: | [linux-to-osx-r2r.txt](https://github.com/ElectronNET/Electron.NET/files/4881900/linux-to-osx-r2r.txt)        |  
| OSX            | :grey_question:    | :grey_question:    | :grey_question: |  

_* Windows to OSX was never supported due to symlinks_

### Turning off R2R
To turn off R2R, the /PublishReadyToRun flag was set to false:
```bash
rbaker@DESKTOP-EUK8SOJ:***/ElectronNET-API-Demos$ electronize build /target win /PublishReadyToRun false
```
This caused a new set of errors:

| Build Platform | Target Win         | Target Linux       | Target OSX      |  
|----------------|--------------------|--------------------|-----------------| 
| Windows        | :heavy_check_mark: |[win-to-linux.txt](https://github.com/ElectronNET/Electron.NET/files/4881797/win-to-linux.txt)             | :x: *           |  
| Linux          |[linux-to-win.txt](https://github.com/ElectronNET/Electron.NET/files/4881786/linux-to-win.txt)               | :heavy_check_mark: | [linux-to-osx.txt](https://github.com/ElectronNET/Electron.NET/files/4881882/linux-to-osx.txt)      |  
| OSX            | :grey_question:    | :grey_question:    | :grey_question: |  

### Summery 
I don't have access to an OSX box, so I cannot test that aspect. Maybe someone here can?

I don't know what to make of these error messages.  I will continue to try to decipher them, but there is a lot of "terminal vomit" involved with this.

**Comment by GregorBiswanger** [comment]
Fixed in the new version from Electron.NET 9.31.3.

**Comment by younglip** [comment]
@GregorBiswanger i've same issue, but only 9.31.2 available on nuget. Can you say when 9.31.3 will be publish?
