### ISSUE TITLE
The buildCommand of electronize should allow passing build parameters for dotnet publish

### ISSUE THREAD

**Issue by bravecobra** [ElectronNET/Electron.NET#447]
When publishing a dotnet project you're allowed to pass extra parameters to the msbuild process, like '/p:SemVer=1.2.3', that you can reference in the csproj. However the electronize forces you to publish the dotnet project without these. Just as you can pass extra parameters to the electron-builder, you should be able to pass extra parameters to the dotnet process.

Implementing this would be fairly easy. Just append extra arguments to this line.
https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.CLI/Commands/BuildCommand.cs#L108

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Comment by Thokerb** [comment]
It seems like this option no longer exists @GregorBiswanger or has been removed again 
https://github.com/ElectronNET/Electron.NET/blob/main/src/ElectronNET.CLI/Commands/BuildCommand.cs
