### ISSUE TITLE
Handling custom (MyApp://) protocol on MacOS

### ISSUE THREAD

**Issue by oliexe** [ElectronNET/Electron.NET#451]
**Electron.NET version:** 9.31.2
**Target platform:** MacOS

I need to handle the login token from the custom protocol (MyApp://) but I am unable to handle the passed arguments to the app. I have successfully registered the application as a protocol hander and it gets launched/opened in the app directly from safari by using : 
`await Electron.App.SetAsDefaultProtocolClientAsync("MyApp"); `
and setting it in-app plist (As documented).

But I don't know how to handle the passed URL. I can't do that by listening to IRC event (as documented in Electron documentation in handling the custom protocol on MacOS): 
`Electron.IpcMain.On("open-url", Handleprotocol());`
The app gets opened/resumed when requested in safari but nothing happens. The IPC message is not published.

 Is that a bug or am I doing something wrong ? cant seem to find anything similar in samples or around the net specifically for Electron.NET.

**Comment by ThrDev** [comment]
Hey @olirehacek!

At a quick glance, it doesn't appear that 'open-file' or 'open-url' is implemented in Electron.NET.

https://github.com/ElectronNET/Electron.NET/search?q=open-file&type=Code

**Comment by olirehacek** [comment]
> Hey @olirehacek!
> 
> At a quick glance, it doesn't appear that 'open-file' or 'open-url' is implemented in Electron.NET.
> 
> https://github.com/ElectronNET/Electron.NET/search?q=open-file&type=Code

Thanks @ThrDev ,
Are you aware of any way/workaround I can handle the custom URL in Electron.NET. We have app that cannot be flipped into production because we can't log in to our service while using the oauth window. It's actually pretty serious.

**Comment by DavidNorena** [comment]
Same here, we are dealing with the same issue :(

**Comment by Elimil** [comment]
Same problem here, would really require this to work.

**Comment by olirehacek** [comment]
Any news on this ?

**Comment by rakista112** [comment]
They seem to have implemented open-url and open-file recently. #478 
@olirehacek @Elimil @DavidNorena

**Comment by DavidNorena** [comment]
Does it work for windows as well ?

**Comment by rakista112** [comment]
@DavidNorena  for Windows you might need to parse process.argv to get the file.
Seems like [open-url](https://www.electronjs.org/docs/api/app#event-open-url-macos) and [open-file](https://www.electronjs.org/docs/api/app#event-open-file-macos) only work on macOS.

**Comment by QaisAlkhateeb** [comment]
i tried  process.argv but not working, anyone have fix for this on Windows ?
