### ISSUE TITLE
Reoccurred Issue #288 now with electron-builder version 22.7.0

### ISSUE THREAD

**Issue by marlonrodriguezpinto** [ElectronNET/Electron.NET#454]
Version: 22.7.0
Target: Windows

Steps to Reproduce:
Performing a regular build with
`electronize build /target win`
fails since the Build Command seems to pass invalid CLI arguments to electron-builder with 
`Unknown argument: .`

electron-builder  version=22.7.0 
electron  version=8.2.3

**Comment by Delpire** [comment]
I am running into this issue as well. @marlonrodriguezpinto were you able to find a way around this issue?

**Comment by Delpire** [comment]
It seems the solution is to uninstall the ElectronNET-CLI tool and reinstall it.

@marlonrodriguezpinto fyi

**Comment by rakista112** [comment]
This issue has been fixed in #443 and has been release in ElectronNET 9.31.2
Just update the ElectronNET-CLI tool to at least 9.31.2 or better yet 9.31.3 (latest version)
Run the following from your terminal

`dotnet tool update electronnet.cli -g`
