### ISSUE TITLE
Can't change the bounds on a BrowserView before calling browserWindow.SetBrowserView

### ISSUE THREAD

**Issue by MopsieX** [ElectronNET/Electron.NET#458]
* **Version**: 9.31.2

Steps to Reproduce:

1. Create a BrowserWindow

```
BrowserWindow browserWindow = await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions
            {
                Width = 500,
                Height = 500,
                Frame = false,
                Transparent = true
            });
```
2. Create a BrowserView(`BrowserView bv = await Electron.WindowManager.CreateBrowserViewAsync();`)
3. Set the Bounds of the BrowserView

```
var bounds = await browserWindow.GetBoundsAsync(); 
bv.Bounds = new Rectangle() { Height = bounds.Height, Width = bounds.Width, X = 0, Y = 0};
```

4. Set the BrowserView(`browserWindow.SetBrowserView(bv)`)

If you set the bounds of the BrowserView before you call SetBrowserView the BrowserView's bounds will be {0,0,0,0}. Once you call SetBrowserView you can then set its bounds.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
