### ISSUE TITLE
Browser Windows created too close together have the same Id

### ISSUE THREAD

**Issue by danatcofo** [ElectronNET/Electron.NET#460]
I've opened multiple new windows via `Electron.WindowManager.CreateWindowAsync(options, url)` and the resulting windows all share the same Id value if they are opened close enough together. If they are created with enough time separating the creations the id's increment as expected.

**Comment by GregorBiswanger** [comment]
I couldn't recreate the problem. Do you have a sample project? Possibly. find the problem and could submit a pull request. However, an example project would be useful for testing.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
