### ISSUE TITLE
File protocol fails with ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by duncanawoods** [ElectronNET/Electron.NET#466]
This can be seen on the music player sample with the latest source versions when it tries to play a file using an url like:

    `file://somepath/music.mp3`

Its an electron issue: https://github.com/electron/electron/issues/23757 with some workarounds. 

I'll submit a pull-request.

**Comment by GregorBiswanger** [comment]
Thank you very much for your pull request. Will be released with the next update.
