### ISSUE TITLE
Ipc is not working with a Blazor Server project

### ISSUE THREAD

**Issue by aksoftware98** [ElectronNET/Electron.NET#469]
* **Version**: 

Currently using the latest version of Electron.NET with Blazor Server & .NET Core 3.1 
And building the project for Windows 

I have multiple razor pages but I cannot have the communicate works between them via Ipc

Steps to Reproduce:

1. Created a razor page and with button and having a handler so when I click the button I send the following message like that 
 `var window = Elelctron.WindowManager.BrowserWindows.FirstOrDefault();`
 `Electron.IpcMain.Send(window, "message", "Hello");`

2. In another razor page I'm calling the on Method to listen to the 'message' channel and respond by showing an alert 
But when I click the button nothing is happening 

Thanks

**Comment by Xarkam** [comment]
I understand better why my code is not working:
```
 Electron.IpcMain.On("show-app-menu-btn", (args) =>
      {
          var mainWindow = Electron.WindowManager.BrowserWindows.FirstOrDefault();
          Electron.Menu.ContextMenuPopup(mainWindow);
      });
```
Inside my blazor page.

**Comment by GregorBiswanger** [comment]
With Blazor server-side, IPC communication should not be necessary. 
On the server side, client + server merge.

Could i help?

**Comment by Gaulomatic** [comment]
@GregorBiswanger That's correct, but the buggy IPC leads to the app not being able to close itself gracefully.

**Comment by GregorBiswanger** [comment]
i am currently working on improving communication.

**Comment by Gaulomatic** [comment]
That's great news, thank you.
