### ISSUE TITLE
Add the ability to skip running dotnet publish so that we can call that in our build scripts.

### ISSUE THREAD

**Issue by Delpire** [ElectronNET/Electron.NET#479]
We have the need to do some things to our assemblies before we want to packaged them up in an Electron app. For example, digitally signing the files.

It would be nice if we could tell `electronize build` to skip running `dotnet publish` and do the rest. This way I can run `dotnet publish` myself, with all the necessary arguments, then do my post build/publish work to my files, then call `electronize build` to build the Electron application.

Looking at the Electron CLI, it looks like there is no way to skip the publish step, so I believe all of my assemblies will get overwritten.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Comment by ayeshap20** [comment]
@GregorBiswanger  @Delpire I am using ElectronNET.API v23.6.2.0 and trying to skip **dotnet publish** in **electronize build** but I'm not sure how to do this. The code here does not seem to skip over the dotnet publish step ever: https://github.com/ElectronNET/Electron.NET/blob/21c17dc82ba6c416871d139f20df6ea3b0fc022c/src/ElectronNET.CLI/Commands/BuildCommand.cs#L142
