### ISSUE TITLE
Is there a way to use the Electron.NET with javascript, html and css rather than cshtml?

### ISSUE THREAD

**Issue by sporebean22** [ElectronNET/Electron.NET#481]
I would personally prefer using Javascript, HTML and css rather than cshtml, is there a way to implement that? what would i need to change roughly speaking? Thanks

**Comment by GregorBiswanger** [comment]
Sure, why not?

Create a new empty ASP.NET web project.. create a `wwwroot` folder and bring in your static files... just don't forget the `UseStatic `middleware...

**Comment by sporebean22** [comment]
Awesome, Thanks Friend i Love You.
