### ISSUE TITLE
Unable to run on Ubuntu

### ISSUE THREAD

**Issue by arijit-code** [ElectronNET/Electron.NET#482]
I am opening the issue as a question as I am not sure if this is a bug.

I am new to Electron.NET. I am trying to run a Electron.NET app on Ubuntu 20.04(64-bit).

I created the build with "electronize build /target linux". I am not sure if this is the correct procedure to create a build for Ubuntu.

I am however, able to run the app using "electronize start" or from the AppImage. 

However, when I try to run it from "../electron.net-api-demos/ElectronNET-API-Demos/bin/Desktop/linux-unpacked/resources/bin" I get the following error
<img width="978" alt="2020-09-18 12_48_42-Ubuntu_20 04_LinuxVMImages com  Running  - Oracle VM VirtualBox" src="https://user-images.githubusercontent.com/59074787/93639209-7cff8380-f9ad-11ea-8639-ed485fbccb3f.png">

I also wrote a small app using Electron.NET on my own listening on port 50,000.  I get the same error
<img width="966" alt="2020-09-18 12_54_04-Ubuntu_20 04_LinuxVMImages com  Running  - Oracle VM VirtualBox" src="https://user-images.githubusercontent.com/59074787/93639588-1b8be480-f9ae-11ea-9479-7d10025a5c3a.png">

If this is a bug hopefully this will help the project.  If this is not a bug any help will be much appreciated.

**Comment by ericfelipe99** [comment]
i have the same question. 
on windows 10 and vs2019, both with lastest updates 

i build the app with command: 
electronize build /target linux 

but generate an error that says to me add the parameter /PublishReadyToRun false. 
Error: 
"não há suporte para otimizar assemblies para desempenho na arquitetura ou plataforma de destino selecionada....."
something like... "optimizing assemblies for performance on the selected target architecture or platform is not supported. Make sure you are using a supported runtime identifier or set the PublishReadyToRun property to false"

with command 
electronize build /target linux /PublishReadyToRun false
it generated an *.asar file. so... what i have to do with this file to run in linux? there's no way to generate an executable ?

**Comment by GregorBiswanger** [comment]
Electron.NET uses electron builder under the hood. You can configure this in the `electron.manifest.json` file in the build part.

The electron-builder documentation shows a target property:
https://www.electron.build/configuration/linux

Could I help you?

**Comment by arijit-code** [comment]
Hi Gregor,

 

Thanks for your reply.  Unfortunately the project for which I was working on this got cancelled. But I would like to thank you very much for taking the time to reply to my email.  

 

Best Regards,

Arijit

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
