### ISSUE TITLE
electronize start and electronize build producing 2 totally different apps

### ISSUE THREAD

**Issue by SolarIceMedia** [ElectronNET/Electron.NET#484]
not sure if this is a bug or what, but I had built another app using the api and now I'm working on a different app and I have manually deleted all ./bin and ./obj folders but when I type:
electronize start in the console it loads up an old app
if I run
electronize build and go to the Desktop folder, its the correct app.

this is really wierd and not sure if its a bug or me doing something wrong.

**Comment by SolarIceMedia** [comment]
ok so I found the problem and to me it seems like a bug. the electron browser was not clearin out the local storage and it was caching the old blazor app. after going into the developer console -> Application -> Clear Storage and clicking the clear site data with all options checked, it started loading the right one. Ironically the one it was loading had even been deleted from my repos completely and drove me insane for almost 4 hours. why this thing is not clearing the site data on start is beyond me but it should be.

**Comment by GregorBiswanger** [comment]
For this problem we have an `electronize start /clear-cache` command.

could i help?

**Comment by SolarIceMedia** [comment]
ok thank you
