### ISSUE TITLE
Keeping size down by putting electron binaries in a common folder that multiple applications can use

### ISSUE THREAD

**Issue by ingrown** [ElectronNET/Electron.NET#488]
Hello!

Electron.NET is really cool but I have a silly question. Whenever I build my application is about 200mb. Is there a way to not bundle the electron api inside the application so I can put it in a separate directory? My reasoning is that building small 5 applications would equal 1gb, but I can keep the size down if I put all the electron binaries it in a common directory, keeping the size down.

Hope to hear back!

**Comment by GregorBiswanger** [comment]
Hi @ingrown,

you can also build and use your project without Electron.NET. The binaries, however, do not. Electron.NET doesn't use much either, but the native Electron with Chromium.

The created installer should be significantly smaller.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
