### ISSUE TITLE
fail to build linux on windows

### ISSUE THREAD

**Issue by ZHHHHH** [ElectronNET/Electron.NET#489]
ElectronNET.API  Version：v9.31.2
ElectronNET.CLI   Version：v9.31.2

i type the build command

`electronize build /target linux`

then occur following error

`C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(270,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false. [F:\Program Files (x86)\GitHub仓库\WebApplication1\WebApplication1.csproj]`

![A2_80UC 7@IC9{9W7I)} H](https://user-images.githubusercontent.com/22629571/96367232-17a2dc00-117f-11eb-93b2-1e8f43a23160.png)

**Comment by GregorBiswanger** [comment]
Please use the following command:
`electronize build /target linux /PublishReadyToRun false`

**Comment by ZHHHHH** [comment]
i have try the command:
`electronize build /target linux /PublishReadyToRun false`

and i got another problem like this:
https://github.com/ElectronNET/Electron.NET/issues/482#issuecomment-699161802

**Comment by GregorBiswanger** [comment]
Electron.NET uses electron builder under the hood. You can configure this in the `electron.manifest.json` file in the build part.

The electron-builder documentation shows a target property:
https://www.electron.build/configuration/linux

Could I help you?

**Comment by ZHHHHH** [comment]
OK，I will try it, thanks for reply
