### ISSUE TITLE
White screen in chromium, no any request from browser

### ISSUE THREAD

**Issue by ViacheslavUKR** [ElectronNET/Electron.NET#492]
I have workable Blazor server side project and try to electronize it. There are no error, no any mistakes, but only white screen in chromium. Do you have any idea to detect and fix this issue?

![Blazor-T222020_122629](https://user-images.githubusercontent.com/20413407/96852682-182ec180-1462-11eb-9dcd-2c6649eefcfa.png)

**Comment by GregorBiswanger** [comment]
Hey, I can't say why that is.

In this video you can see how to debug under the hood: [Electron.NET - Contributing Getting Started](https://youtu.be/Po-saU_Z6Ws)
If there is a mistake on our part, you are welcome to submit a pull request.

**Comment by ViacheslavUKR** [comment]
Hi, Gregor. Simplest application is working in my developer computer as desktop, but real application is no. This real commercial application and I'm not ready to publish it. Do you want to remote access to my computer and check your package?  But it's possible to give you access by Anydesk. If you want to check your package in real environment I'm ready to connect with you by Telegram or Discord and give you full access to my developer computer. Call me AlexEv1337 in telegram or AlexEv#1247 in Discord, and I give you full access to my computer with Anydesk.

**Comment by danatcofo** [comment]
In these cases you might check what location is loading in the window.  I've found if I have a whitescreen its for one of the following reasons

* I'm not loading the correct location or...
* My vue didn't build the interface (whatever you interface generator of choice may be)

though honestly I usually have a js error if its the vue issue.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
