### ISSUE TITLE
Socket disconnects when sending large data?

### ISSUE THREAD

**Issue by nekiro** [ElectronNET/Electron.NET#494]
Electron version latest from nuget.
Net Core 3.1
NodeJs v12.19.0

Debug

When sending larger data through socket (Electron.IpcMain.Send), in my case array with 100 indexes every index has Item object in it, item object has like 20 properties. I think it also happens if I send small array or long string

It even happens for single string atm, what's the problem?

Steps to Reproduce:

1. Electron.IpcMain.Send(mainWindow, "any", new string[] array { "?", "lol"});
2. 
![image](https://user-images.githubusercontent.com/14142246/97103926-f0cd3400-16af-11eb-8788-848da617118a.png)

**Comment by GregorBiswanger** [comment]
The socket connection is then restored normally. 

I'm currently working on better communication in the background.

**Comment by nekiro** [comment]
@GregorBiswanger that's great, could you point me to the code, which is resposnible for these disconnects? I would maybe try to contribute too.
