### ISSUE TITLE
Create deb application

### ISSUE THREAD

**Issue by scherenhaenden** [ElectronNET/Electron.NET#495]
I need a mutable application but on linux electron.NET creates only appimages.

is there anyway to create a deb app?

thanks.

**Comment by GregorBiswanger** [comment]
Hey @scherenhaenden, 

Electron.NET uses electron builder under the hood. You can configure this in the `electron.manifest.json` file in the build part.

The electron-builder documentation shows a target property:
https://www.electron.build/configuration/linux

Could I help you?

**Comment by scherenhaenden** [comment]
@GregorBiswanger 

ok, that is embarassing, I was trully hunting such information on the internet but I did not find it. 

thanks a lot mate.

**Comment by scherenhaenden** [comment]
@GregorBiswanger sadly, it is buggy.

**Comment by k-karuna** [comment]
@scherenhaenden can you let know if you will succeed in this issue?

**Comment by scherenhaenden** [comment]
it did not, but the error appears to be releated with the packes used in my system in combination with the electron builder.

everything works, except when I build the zip/deb files... 

I'm trying to get a release using github actions

**Comment by scherenhaenden** [comment]
@k-karuna 

https://github.com/ElectronNET/Electron.NET/issues/495

**Comment by danatcofo** [comment]
Late to the party @scherenhaenden, but this is an example of our manifest sections for linux, hopefully it helps you
```json
"build" : {
    ...
    "linux": {
      "icon": "../../../../../build/assets/Prefix_256.png",
      "maintainer": "Stackify",
      "executableName": "Prefix",
      "target": [ "deb", "rpm" ]
    },
    "deb": {
      "depends": [ "libnss3" ],
      "fpm": [
        "--name=Prefix",
        "--after-install=../../../../../build/linux/postinst",
        "--after-remove=../../../../../build/linux/postrm"
      ]
    },
    "rpm": {
      "depends": [ "libXScrnSaver", "libnss3" ],
      "fpm": [
        "--name=Prefix",
        "--after-install=../../../../../build/linux/postinst",
        "--after-remove=../../../../../build/linux/postrm",
        "--iteration=1.0.0"
      ]
    }
}
```

**Comment by schaveyt** [comment]
@danatcofo for the linux icon path `../../../../../build/assets/Prefix_256.png` what is this location relative to. I am struggling to line mine up.

**Comment by danatcofo** [comment]
Build is under solution root. Electron manifest is under ~/arc/prefix-app.  So all the extra ../s are accounting for the building directory that is somewhere under bin I think.  Basically add ../../../ to get relative location of electron manifest

**Comment by scherenhaenden** [comment]
I have not kept trying cuz I did not have the time, But I would try to find some free time to try it again

**Comment by schaveyt** [comment]
I ended up just use bailing on the .png and instead installed [make-Icns](https://www.npmjs.com/package/make-icns) and converted my 1024x1024 png to the .icns format. I was able reference it in both the Linux and Mac sections...and it all worked on the first try 👍
