### ISSUE TITLE
exceptions are not shown in the console

### ISSUE THREAD

**Issue by FadyQJ** [ElectronNET/Electron.NET#497]
I am not sure if this is a bug but under Ubuntu I am using:
`app.UseDeveloperExceptionPage();` even outside if (env.IsDevelopment())

I am not seeing any exceptions thrown in the console. I only get:
Got disconnect! Reason: transport close

When I'm using windows it works correctly

**Comment by FadyQJ** [comment]
I noticed that what is causing this is the throw is being called in the async Task.Run(async () => { }) function
So there is some detachment going on once a new thread is created.

If I throw e.g. `throw new System.ArgumentException("A", "B");` outside the Task.Run I get the error.
This is my first project using linux for C# as well as ASP.Net so this may be normal behavior for ASP

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
