### ISSUE TITLE
Support app.setLocale() or --lang switch

### ISSUE THREAD

**Issue by lukasportal** [ElectronNET/Electron.NET#502]
I want to manually set the locale of the app, instead of using the default one.

From here, we can see that the electron team have added `app.setLocale()` successfully
https://github.com/electron/electron/pull/26185

A quick workaround could be adding the switch `--lang=XYZ` on chromium launch.

How possible would it be to add support for any of these 2? Or is there an existing workaround for this?

**Comment by danatcofo** [comment]
You can use the HostHook feature to do this as well.  It runs in the main thread and has access to the App module.

**index.ts**
```typescript
export class HookService extends Connector {
    constructor(socket: SocketIO.Socket, public app: Electron.App) {
        super(socket, app);
    }

    onHostReady(): void {
        this.app.setLocale('locale');
    }
}
```
