### ISSUE TITLE
SQLite database access with EFCore from Electron.NET ASP NET Core does not work

### ISSUE THREAD

**Issue by abrasat** [ElectronNET/Electron.NET#503]
Which version of Electron.NET CLI and API are you using? 
* **Latest** 

Which version of .NET Core and Node.js are you using (if applicable)?
* **Latest**

What target are you building for?
* **Windows**:

Steps to Reproduce:

1. Add this entry to appsettings.json
```
"ConnectionStrings": {
   "SQLiteConnection": "DataSource=mysqlite.db"
}
```
2. Add to ConfigureServices() in Startup.cs
```
services.AddDbContext<ContactsDbContext>(options =>
     options.UseSqlite(Configuration.GetConnectionString("SQLiteConnection")));
```
3. Create ContactsDbContext class and pass it to controller constructor
```
private readonly ContactsDbContext _context;
public ContactsController(ContactsDbContext context)
{       
    _context = context;
}
```
4. Prepare HttpGet REST API in controller
```
[HttpGet]
public async Task<ActionResult<IEnumerable<Contact>>> Get()
{
    var contacts = await _context.Contacts.ToListAsync();
    return contacts;
}
```
5. Perform migrations, mysqlite.db file is created in the solution root. Set "Copy Always" option for it. Add manually 2 records into SQLite database.

6. Prepare menu in Angular code to call HttpGet API.

7. Start Electron App. Debug with VS2019, attach to application.

8. Click on menu that triggers HttpGet call. The Get() REST API in ASP .NET Core controller is triggered. No exception is thrown, but the Contacts list is empty (0 records)

The same code works when using it directly in a ASP NET Core application

**Comment by abrasat** [comment]
Update: Yesterday I tested directly from VS 2019 by starting the Electron App with F5.
Today I performed an "electronize build". After that the electron app works correctly now, also when started from VS 2019....

**Comment by keesjan-bagtag** [comment]
I think SQLite connection string has a space in datasource eg: "Data Source=mysqlite.db"

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
