### ISSUE TITLE
Configurable Default Electron Port

### ISSUE THREAD

**Issue by aarong-av** [ElectronNET/Electron.NET#504]
In many environments developers are not permitted to find available port. We must use specified ports allotted. Can we change the main.js file to include the following (~ line 66):
```
    let defaultElectronPort = 8000;
    if (manifestJsonFile.electronPort) {
        defaultElectronPort = (manifestJsonFile.aspCoreBackendPort)
    } 
    // hostname needs to belocalhost, otherwise Windows Firewall will be triggered.
    portscanner.findAPortNotInUse(defaultElectronPort, 65535, 'localhost', function (error, port) {
        console.log('Electron Socket IO Port: ' + port);
        startSocketApiBridge(port);
    });
```

This will allow users to explicitly set the port just as you can do with the aspNetCore port.

**Comment by GregorBiswanger** [comment]
You need an additional configuration in the **electron.manifest.json** file with the key **aspCoreBackendPort**:

```
{
  "executable": "ElectronNET.WebApp",
  "splashscreen": {
    "imageFile": "/wwwroot/assets/img/about@2x.png"
  },
  "singleInstance": false,
  "aspCoreBackendPort": 8080, <--- Your custom Port for ASP.NET Backend
  "build": {
    "appId": "com.electronnetapidemos.app",
...
```

The application then runs automatically as a single instance. I hope you like it that way.

**Comment by aarong-av** [comment]
I have the aspCoreBackendPort accounted for. I need the electronPort changed from its default of 8000 and then searching for whatever is available if 8000 is taken. 

Ultimately I need the electron port to behave exactly like what was already done with aspCoreBackendPort.

Thanks for the quick reply!

**Comment by aarong-av** [comment]
Thanks for putting it on a milestone. I have a local branch. I don’t think I have permission to push. 

Are there any other steps to implementing this other than what I have above?

Also how can I workaround this for now?

**Comment by GregorBiswanger** [comment]
In this video I show, how you can work with the repository:
https://youtu.be/Po-saU_Z6Ws

Your pull request is very welcome to us :)

**Comment by aarong-av** [comment]
I put in the PR. Let me know if it is wrong.

**Comment by skarin** [comment]
I'd love to see this get In ASAP.  Low risk, big impact.    Thanks guys!

**Comment by GregorBiswanger** [comment]
At the moment I'm still a bit busy - I don't think I'll have time for Electron until December - but a lot will happen that really rocks!

**Comment by aarong-av** [comment]
Is there some guidance on the electron.manifest.json “files” section? I think I can work around this problem by making my own main.js but I can’t find any docs on how it works and copying an example ElectronHostHook does seem to overwrite the main.js.

**Comment by nazar322** [comment]
So is there a way to set a default electron port for 23.6.1?

**Comment by nazar322** [comment]
Sadly but in 4 years this feature seems has not been added.

**Comment by nazar322** [comment]
https://i.imgur.com/JmGPKOu.png
https://i.imgur.com/e3ATeQS.png

**Comment by nazar322** [comment]
`"electronPort": 7777`
Electron.NET needs a wiki on `electron.manifest.json`
