### ISSUE TITLE
Reconnection error when overwriting configureSignalR (Blazor)

### ISSUE THREAD

**Issue by noelroehrig** [ElectronNET/Electron.NET#507]
* **Version**: Electron.NET API/ Electron.NET CLI: 9.31.2; net core: 3.1

Hey!
We are using a setup of Electron.NET and Blazor (Server) which is working great in general. Recently we made adjustments to the Blazor circuit / reconnection logic to sustain states more reliantly.
Afterwards we noticed that the Electron App loses it's connection after 2-4 minutes of inactivity. This doesn't happen in the browser version.

The following adjustment causes this issue (https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#logging):
```
<script autostart="false" src="_framework/blazor.server.js"></script>
<script>
        Blazor.start({
            configureSignalR: function (builder) {
                builder.configureLogging("trace");
            }
        });
</script>
```

Any idea on why this only occurs in Electron?

Thanks!

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
