### ISSUE TITLE
Windows publish failing with white space on the user profile path.

### ISSUE THREAD

**Issue by VPKSoft** [ElectronNET/Electron.NET#508]
ElectronNET.API: 9.31.2
ElectronNET.CLI Version: 9.31.2.0

Node.js version: v12.18.3

* **Target**: 
Windows x64.

The release build fails with the following message on a Windows computer with a white space on the user profile folder:
![image](https://user-images.githubusercontent.com/40712699/99268055-5cc53700-282d-11eb-802b-5ad4c7fdd188.png)

Steps to Reproduce:
1. Have a user profile with a white space character (`%USERPROFILE%`) in Windows
2. Run `electronize build /target win` in your project folder.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
