### ISSUE TITLE
dotnet electronize build should not npm install

### ISSUE THREAD

**Issue by yoDon** [ElectronNET/Electron.NET#51]
Building and Starting are currently much slower than necessary because every build and every start does a bunch of npm install like tasks that take much longer than the actual build. 

The install steps should be handled by a restore or install command, so we don't need to wait for them to complete each time we build/start (or alternatively could we have rebuild/restart commands that are lighter-weight than the full build/start commands, if you want to keep the installs in place?)

**Comment by robertmuehsig** [comment]
At least the start is "faster", because if start detects the node_modules folder it doesn't do a npm install, maybe build should to the same. Good feedback - will consider it for the next drop 👍

**Comment by robertmuehsig** [comment]
Works like the start enhancement - if we detect the node_modules folder, we skip npm install. 

Maybe we need a --force command later on to reinstall npm packages if needed.

**Comment by damikun** [comment]
Is there a proper way to pass --force? because some of my packages need to run npm install with force without there is npm checks applyed force skip this checks(validation)...
