### ISSUE TITLE
download bug

### ISSUE THREAD

**Issue by 312977** [ElectronNET/Electron.NET#514]
9.0.5

9.0.5

* **Version**: 
9.0.5

* **Target**: windows x86  64

 error info 
              
Steps to Reproduce:
   
1.  excuute cmd   electronize build /target win
2.  cant not  download https://github.com/electron/electron/releases/download/v9.0.5/electron-v9.0.5-win32-x64.zip
    error ECTRON_BUILDER_CANNOT_EXECUTE
3. i download this electron-v9.0.5-win32-x64.zip in chrom,  i put this rar to ToolCabinet\bin\Desktop\win-unpacked   
but  this  rar will remove  when i retry excute cmd electronize build /target win  . 
canyou help me ? if exsit /electron-v9.0.5-win32-x64.zip   dont download agin ,
![image](https://user-images.githubusercontent.com/3642374/99966876-f1054000-2dd1-11eb-9044-60b157ce9dc3.png)

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
