### ISSUE TITLE
./electron:" Permission denied

### ISSUE THREAD

**Issue by devtag** [ElectronNET/Electron.NET#518]
How can I avoid this error on MacOS:

After I ran "electronize start" the system tried to "start npm install" then this error came up:
"./electron:" Permission denied

I even tried:
sudo -s electronize start

Result:
./electron: Permission denied

System:
macOS Catalina 10.15.7
User has administration permissions

**Comment by GregorBiswanger** [comment]
try to use the "sudo" command with the electronize commands.

**Comment by devtag** [comment]
I even tried:
sudo -s electronize start

Result:
./electron: Permission denied

**Comment by GregorBiswanger** [comment]
and "sudo dotnet -s electronize start"? 🤔

**Comment by devtag** [comment]
"sudo dotnet -s electronize start" produces this error:
Unknown option: -s

At the end I tried this command and it works now:
sudo -s electronize build /target macos
