### ISSUE TITLE
dotnet electronize start should abort if build fails

### ISSUE THREAD

**Issue by yoDon** [ElectronNET/Electron.NET#52]
Hi guys, at least in VS Code if there is a compiler error during the dotnet electronize start's build step, there are still enough old built *.exe's lying around that the electron app will appear to launch and run, but it's running the last successful build not the current code. Definitely a recipe for burning a ton of extra time debugging the wrong exe, and trying to remember to either manually clean bin and obj before each build or manually doing an explicit build step (which spews less into the terminal window) before running start. Having start abort if the build fails would be a huge help.

**Comment by robertmuehsig** [comment]
The build/start command will now stop if the publish command fails (e.g. compilation error occured) - maybe not perfect, but should be better then now.

**Comment by robertmuehsig** [comment]
mhh... i broke it...

**Comment by robertmuehsig** [comment]
Not perfect, but could work. The code now searchs for "error". It would be way cleaner to get the exit code of the actual cmd.exe/bash, but I couldn't get it and the actual cmd.exe runs fine...
