### ISSUE TITLE
electronize start /target custom not working

### ISSUE THREAD

**Issue by Bmooij** [ElectronNET/Electron.NET#521]
* **Version**:  9.31.2
* **.NET Core**: 3.1
* **Node.js**: v12.13.0
* **Target**: x68

With the command `electronize start /target custom "win7-x68;win32"`, it always publish with x64: `dotnet publish -r win-x64`

**Comment by Bmooij** [comment]
I've forked the project and ran "BuildAll.cmd". It replaced "electronize" executable in the .dotnet/tools folder. It works now

**Comment by bravecobra** [comment]
> With the command `electronize start /target custom "win7-x68;win32"`, it always publish with x64: `dotnet publish -r win-x64`

I think you needed win7-x86, or was that just a typo?

**Comment by GregorBiswanger** [comment]
You also need the `electron-arch` parameter for the processor architecture.

This command does what you want:
`electronize build /target custom "win7-x86;win" /electron-arch ia32`

**Comment by GregorBiswanger** [comment]
And for the start command you only had one typo.

This command does what you want:
`electronize start /target custom "win7-x86;win32"`
