### ISSUE TITLE
Multi-target frameworks netcoreapp3.1 and net5

### ISSUE THREAD

**Issue by danatcofo** [ElectronNET/Electron.NET#525]
While it is nice that you have pushed the framework version to `net5`, being so aggressive is detrimental to many of us. Other than the latest and greatest sentiment is there an overwhelming reason not to support multiple frameworks?  From my limited testing the only real code change you have to do is inside the CLI such that it can support either framework.

I was able to build the api and and cli with dual frameworks successfully but running the new cli assumed using the net5 runtimes.  That looks like what would have to be fixed to support both.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
