### ISSUE TITLE
OnFocus + OnBlur stops firing after you leave application ideal for 30 min and then reuse.

### ISSUE THREAD

**Issue by singh7sarb** [ElectronNET/Electron.NET#534]
* **Version**: **9.31.2**

* **Target**: **.net core 3.1**

Steps to Reproduce:

1. make demo application with OnFocus, OnBlur and Type log on both
2. start application
3. minimize and maximize you will see log will print.
4. keep your application ideal for 30 to 40 min ideal(or leave your application on standby)
5. do Step 3. **log will not print**.

**Comment by GregorBiswanger** [comment]
Please use the latest Electron.NET version 11.5.1. This bug should be fixed there.

Also think about an update of the CLI: `dotnet tool update ElectronNET.CLI -g`
