### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by MuteebAhmad148** [ElectronNET/Electron.NET#535]
Hello,
I'm having compatibility issues on installing the package. My project runs on .Net 5 .
Here is the error I'm getting.
_Install-Package : NU1202: Package ElectronNET.API 11.5.1 is not compatible with net50 (.NETFramework,Version=v5.0). Package ElectronNET.API 11.5.1 supports: net5.0 (.NETCoreApp,Version=v5.0)_

**Comment by ppostman** [comment]
i'm having this issue as well.. @MuteebAhmad148 how'd you fix?
