### ISSUE TITLE
Interacting with the Splash Screen causes WebApp to exit before reaching main browser window

### ISSUE THREAD

**Issue by MiniguyBrendan** [ElectronNET/Electron.NET#539]
* **Version**: 11.5.1

.NET 5, Nodejs v14.15.4

* **Target**: Windows x64

Interacting with the splash screen - particularly by clicking on a different window, then clicking back to the splash screen - often causes the entire WebApp to close before launching the main browser window. This issue showed up in the discussion of #357 but wasn't resolved.

Further, the splash screen acts as a normal browser window, and its contents can be dragged (i.e. dragging the splash image to your desktop, creating a .png copy), and can be resized, causing odd behavior.

Steps to Reproduce:

1. Set a splash image in `electron.manifest.json`
2. Interact (click, drag, etc) with it before the main window has loaded/rendered

**Comment by dbphoton** [comment]
Still experiencing the same issue, after update, clean and fully rebiuld app.
When I click on splash,  Electron stops at 
```
"Invoke electron.cmd - in dir: C:\Users\dawid\Documents\flowgres-time-tracking\sources\TimeTracking\obj\Host\node_modules\.bin
Microsoft Windows [Version 10.0.19041.1083]
(c) Microsoft Corporation. Wszelkie prawa zastrzeżone.
C:\Users\dawid\Documents\flowgres-time-tracking\sources\TimeTracking\obj\Host\node_modules\.bin>electron.cmd "..\..\main.js"
(node:22368) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Electron Socket IO Port: 8000
Electron Socket started on port 8000 at 127.0.0.1
ASP.NET Core Port: 8001"
```

and WebApp close before launching the main browser window.
