### ISSUE TITLE
electronize doesn't add `version` or `description` to the package.json it uses in a build.

### ISSUE THREAD

**Issue by danatcofo** [ElectronNET/Electron.NET#541]
Using the latest version (11.5.1) 

This is causing a build error for linux targets with a message of `Please specify 'version' in the package.json` and also causes a warning with message of `description is missed in the package.json`

Steps to Reproduce:

1. add a version and description to the package.json in the application
2. execute `electronize /target linux` on a linux system (other steps may need to be done here to get linux building correctly)
3. look at the package.json used during electronize call and notice its not there.

the file used during the electronize call is put in this general location `~/obj/desktop/-encodedCommand/package.json`

**Comment by GregorBiswanger** [comment]
Since version 8.31.1 we have a feature to set the name and author of the app in `electron.manifest.json`.

Already tried?

**Comment by danatcofo** [comment]
that is set just fine, its not the name and the author that is causing any issues, its version/description.  

I noticed that name/author was in the output package.json already but didn't comment on it.  Honestly I think something changed upstream of us that is now causing electronize to fail on a linux target where it did not before.  It exposed something electronize should probably do but isn't.

**Comment by BenjaminVettori** [comment]
It seems that name, author and version are only written to package.json and package.lock.json, if the "buildVersion" value is set: https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.Host/build-helper.js

**Comment by 3xp3rT** [comment]
I need to add build version like "1.0.0.9"
but shows 'Invalid version: "1.0.0.9"  failedTask=build stackTrace=Error: Invalid version: "1.0.0.9"'
But when i try "1.0.9" it's works fine

**Comment by BenjaminVettori** [comment]
> I need to add build version like "1.0.0.9" but shows 'Invalid version: "1.0.0.9" failedTask=build stackTrace=Error: Invalid version: "1.0.0.9"' But when i try "1.0.9" it's works fine

That error appears probably because the package.json version which is set by electron.net needs to be in semantic version format. You can find more about semantic versioning at [semver](https://semver.org) and [npmjs](https://docs.npmjs.com/about-semantic-versioning)

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
