### ISSUE TITLE
Electron-Updater broken - please update to latest Electron version

### ISSUE THREAD

**Issue by dev-gear** [ElectronNET/Electron.NET#542]
@GregorBiswanger @robertmuehsig   A regression was introduced in electron-updater since 7.1.3+ where clients are stuck at the old version and never receive updates.

Here is the link with full details: https://github.com/electron/electron/pull/21630

Would be great if we could fast-track the update to the latest Electron version, please.

**Comment by GregorBiswanger** [comment]
Which version of Electron.NET do you use? With the current version (11.5.1), it works wonderfully for me.

**Comment by dev-gear** [comment]
Apologies @GregorBiswanger . It was my one past version installed app which was throwin this error. My app with the latest version from Electron.Net works well and does not throw this error. Thanks for looking into this!
