### ISSUE TITLE
JavaScript error ，After closing the new window

### ISSUE THREAD

**Issue by sFireFrog** [ElectronNET/Electron.NET#551]
Electron.NET CLI and API ：11.5.1
.NET Version：.net 5.0
Node.js  Version: 14.16.0
* **Target**: win

I already have the main window and create a new window. If I close the new window and then call up the development tool, an error will be reported.
![image](https://user-images.githubusercontent.com/32626364/112306231-8f4ed700-8cda-11eb-9fb2-ac1607f9d697.png)

Steps to Reproduce:

1. Create a main window during initialization
2. Use a button to create a new window
3. Close the new window to call up the development tool
4. If there is a jump page in the main window, an error will be reported every time you jump

**Comment by aschaefer94** [comment]
I am seeing this as well, but I'm seeing it when I reload the main window after closing the second window.

**Comment by ortrails** [comment]
Some info that might help https://stackoverflow.com/questions/44258831/only-hide-the-window-when-closing-it-electron
