### ISSUE TITLE
ShowOpenDialogAsync doesn't return when `openDirectory` is used on Mac

### ISSUE THREAD

**Issue by gbreen12** [ElectronNET/Electron.NET#563]
Electron.NET Version: 11.5.1
Electron.NET CLI Version: 11.5.1
.NET Version: .NET 5.0.202
NodeJS Version: 14.16.1

Using Visual Studio Code on Mac

A dialog opens and I select a directory but it never returns any results. If I use `openFile` instead I get a file directory but `openDirectory` never works.

```
@page "/"

@using ElectronNET.API;
@using ElectronNET.API.Entities;

<h1>Fix Exif Data</h1>

<div>
    <div>SELECTED FOLDER: @folder</div>
    <button @onclick="GetFolder" class="btn btn-primary">Select Image Folder Location</button>    
</div>

@code {
    string folder = "";

    private async void GetFolder()
    {
        var mainWindow = Electron.WindowManager.BrowserWindows.First();
        var options = new OpenDialogOptions() {
            Properties = new OpenDialogProperty[] { OpenDialogProperty.openDirectory }
        };
        
        var results = await Electron.Dialog.ShowOpenDialogAsync(mainWindow, options);
        if (results.Any())
            folder = results.First();
    }
}
```

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
