### ISSUE TITLE
[Help Me] Run Second Application When Running First Application

### ISSUE THREAD

**Issue by semihkiroglu** [ElectronNET/Electron.NET#574]
* **Electron.NET CLI & API versions:** 9.31.2 & 11.5.1
* **.NET Core version:** 3.1 LTS
* **Node.js version:** 14.16.0
* **Target**: Windows 10 x64

Hello there. When I try to run the application I compiled for the second time (second instance), I get an EADDRINUSE error. I want the second application to run and see the first application running and close by doing some operations. I've been searching for 3 days but couldn't find any results. Can you help me?

![image](https://user-images.githubusercontent.com/10871284/122203923-3640aa80-cea7-11eb-9576-378a39668b54.png)

Steps to Reproduce:

1. Build with command: electronize build /target win
2. Run exe from win-unpacked folder (or ElectronNET-API-Demos). Successfully runs.
3. Run again same exe (or ElectronNET-API-Demos) when running first instance, getting error.

**Comment by semihkiroglu** [comment]
I have determined that the Trend Micro Apex One Security Agent is the cause. After add my app to whitelist, problem solved. But I can't ask users to do that. What is your suggested solution? Can we handle this situation as a bug and have a chance to fix it?

**Comment by tub5** [comment]
Is your app digitally signed?
