### ISSUE TITLE
Error in publish

### ISSUE THREAD

**Issue by Nafhaa** [ElectronNET/Electron.NET#575]

**Comment by Nafhaa** [comment]
.csproj file 

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Nafhaa.Web</AssemblyName>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <SerenitySrc>..\..\Serenity\src\</SerenitySrc>
    <DotNetSergenExe>$(SerenitySrc)Serenity.Net.CodeGenerator\bin\sergen.exe</DotNetSergenExe>
    <DotNetSergen>dotnet sergen</DotNetSergen>
    <DotNetSergen Condition="Exists('$(DotNetSergenExe)')">$(DotNetSergenExe)</DotNetSergen>
    <CommonSrc>..\..\common-features\src\</CommonSrc>
    <ProSrc>..\..\pro-features\src\</ProSrc>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\**\*.sql" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
    <None Update="wwwroot\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="Modules\**\*.Template.html;Modules\**\*.ts.html">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ElectronNET.API" Version="11.5.1" />
    <PackageReference Include="EPPlus" Version="5.7.0" />
    <PackageReference Include="FastMember" Version="1.5.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="3.2.17" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.7" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="5.0.7" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serenity.Assets" Version="5.0.44" />
    <PackageReference Include="Serenity.CodeGenerator" Version="3.14.5" />
    <PackageReference Include="Serenity.Scripts" Version="5.0.43" />
    <PackageReference Include="Serenity.Net.Web" Version="5.0.43" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serenity.Extensions" Version="5.0.43" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serenity.Pro.Extensions" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.UI" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.DataAuditLog" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.DataExplorer" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.EmailClient" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.EmailQueue" Version="5.0.41" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
  </ItemGroup>
  <Import Project="$(SolutionDir)Serenity\build\submodule.targets" Condition="Exists('$(SolutionDir)Serenity\build\submodule.targets')" />
  <Target Name="CreateInputsOutputs" BeforeTargets="BeforeBuild">
    <CreateItem Include="Modules\**\*.ts;Imports\**\*.ts;tsconfig.json">
      <Output TaskParameter="Include" ItemName="CompileTSCInputs" />
    </CreateItem>
    <CreateItem Include="wwwroot\Content\site\**\*.less">
      <Output TaskParameter="Include" ItemName="CompileSiteLessInputs" />
    </CreateItem>
  </Target>
  <Target Name="NpmInstall" BeforeTargets="BeforeBuild" Condition="!Exists('node_modules\@types\jquery\index.d.ts')">
    <Message Text="Installing NPM packages..." Importance="high"></Message>
    <Exec Command="npm install" />
  </Target>
  <Target Name="TransformMvcClientTypes" BeforeTargets="BeforeBuild">
    <Exec Command="dotnet tool restore" ContinueOnError="true" />
    <Exec Command="$(DotNetSergen) restore" ContinueOnError="true" />
    <Exec Command="$(DotNetSergen) mvct" ContinueOnError="true" />
  </Target>
  <Target Name="CompileSiteLess" AfterTargets="AfterBuild" Inputs="@(CompileSiteLessInputs)" Outputs="wwwroot\Content\site\site.css">
    <Message Text="Compiling site.less..." Importance="high"></Message>
    <Exec Command="node_modules/.bin/lessc ./wwwroot/Content/site/site.less ./wwwroot/Content/site/site.css" ContinueOnError="true" />
  </Target>
  <Target Name="TransformServerTypings" AfterTargets="AfterBuild">
    <Exec Command="$(DotNetSergen) servertypings" ContinueOnError="true" />
  </Target>
  <Target Name="CompileTSC" AfterTargets="AfterBuild" Inputs="@(CompileTSCInputs)" Outputs="wwwroot\Scripts\site\Nafhaa.Web.js">
    <Message Text="Executing TypeScript compiler..." Importance="high"></Message>
    <Exec Command="node &quot;$(TSJavaScriptFile.Replace('build\\..\tools\', 'tools\'))&quot; -p ./tsconfig.json" ContinueOnError="true" />
  </Target>
  <ItemGroup>
    <Content Update="electron.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

**Comment by Nafhaa** [comment]
CSPROJ file:

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Nafhaa.Web</AssemblyName>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <SerenitySrc>..\..\Serenity\src\</SerenitySrc>
    <DotNetSergenExe>$(SerenitySrc)Serenity.Net.CodeGenerator\bin\sergen.exe</DotNetSergenExe>
    <DotNetSergen>dotnet sergen</DotNetSergen>
    <DotNetSergen Condition="Exists('$(DotNetSergenExe)')">$(DotNetSergenExe)</DotNetSergen>
    <CommonSrc>..\..\common-features\src\</CommonSrc>
    <ProSrc>..\..\pro-features\src\</ProSrc>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\**\*.sql" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
    <None Update="wwwroot\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="Modules\**\*.Template.html;Modules\**\*.ts.html">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ElectronNET.API" Version="11.5.1" />
    <PackageReference Include="EPPlus" Version="5.7.0" />
    <PackageReference Include="FastMember" Version="1.5.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="3.2.17" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.7" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="5.0.7" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serenity.Assets" Version="5.0.44" />
    <PackageReference Include="Serenity.CodeGenerator" Version="3.14.5" />
    <PackageReference Include="Serenity.Scripts" Version="5.0.43" />
    <PackageReference Include="Serenity.Net.Web" Version="5.0.43" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serenity.Extensions" Version="5.0.43" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serenity.Pro.Extensions" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.UI" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.DataAuditLog" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.DataExplorer" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.EmailClient" Version="5.0.41" />
    <PackageReference Include="Serenity.Pro.EmailQueue" Version="5.0.41" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
  </ItemGroup>
  <Import Project="$(SolutionDir)Serenity\build\submodule.targets" Condition="Exists('$(SolutionDir)Serenity\build\submodule.targets')" />
  <Target Name="CreateInputsOutputs" BeforeTargets="BeforeBuild">
    <CreateItem Include="Modules\**\*.ts;Imports\**\*.ts;tsconfig.json">
      <Output TaskParameter="Include" ItemName="CompileTSCInputs" />
    </CreateItem>
    <CreateItem Include="wwwroot\Content\site\**\*.less">
      <Output TaskParameter="Include" ItemName="CompileSiteLessInputs" />
    </CreateItem>
  </Target>
  <Target Name="NpmInstall" BeforeTargets="BeforeBuild" Condition="!Exists('node_modules\@types\jquery\index.d.ts')">
    <Message Text="Installing NPM packages..." Importance="high"></Message>
    <Exec Command="npm install" />
  </Target>
  <Target Name="TransformMvcClientTypes" BeforeTargets="BeforeBuild">
    <Exec Command="dotnet tool restore" ContinueOnError="true" />
    <Exec Command="$(DotNetSergen) restore" ContinueOnError="true" />
    <Exec Command="$(DotNetSergen) mvct" ContinueOnError="true" />
  </Target>
  <Target Name="CompileSiteLess" AfterTargets="AfterBuild" Inputs="@(CompileSiteLessInputs)" Outputs="wwwroot\Content\site\site.css">
    <Message Text="Compiling site.less..." Importance="high"></Message>
    <Exec Command="node_modules/.bin/lessc ./wwwroot/Content/site/site.less ./wwwroot/Content/site/site.css" ContinueOnError="true" />
  </Target>
  <Target Name="TransformServerTypings" AfterTargets="AfterBuild">
    <Exec Command="$(DotNetSergen) servertypings" ContinueOnError="true" />
  </Target>
  <Target Name="CompileTSC" AfterTargets="AfterBuild" Inputs="@(CompileTSCInputs)" Outputs="wwwroot\Scripts\site\Nafhaa.Web.js">
    <Message Text="Executing TypeScript compiler..." Importance="high"></Message>
    <Exec Command="node &quot;$(TSJavaScriptFile.Replace('build\\..\tools\', 'tools\'))&quot; -p ./tsconfig.json" ContinueOnError="true" />
  </Target>
  <ItemGroup>
    <Content Update="electron.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

**Comment by Nafhaa** [comment]
CSPROJ file
[TestProject.Web.csproj.txt](https://github.com/ElectronNET/Electron.NET/files/6676791/TestProject.Web.csproj.txt)

**Comment by Nafhaa** [comment]
Build is actually successful:

C:\Users\Sandbox\source\repos\TestProject\TestProject\TestProject.Web>dotnet build
Microsoft (R) Build Engine version 16.11.0-preview-21254-21+e73d08c28 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\Sandbox\source\repos\TestProject\TestProject\TestProject.Web\TestProject.Web.csproj (in 765 ms).
  Tool 'sergen' (version '5.0.41') was restored. Available commands: sergen

  Restore was successful.
  Processing: ElectronNET.API
  Processing: Serenity.Assets
  Processing: Serenity.CodeGenerator
  Processing: Serenity.Scripts
  Processing: Serenity.Extensions
  Processing: Serenity.Pro.Extensions
  Processing: Serenity.Pro.UI
  Processing: Serenity.Pro.DataAuditLog
  Processing: Serenity.Pro.DataExplorer
  Processing: Serenity.Pro.EmailClient
  Processing: Serenity.Pro.EmailQueue
  Processing: SocketIoClientDotNet
  Processing: WebSocket4Net
  System.NullReferenceException: Object reference not set to an instance of an object.
     at Serenity.CodeGenerator.RestoreCommand.Run(String csproj)
     at Serenity.CodeGenerator.Program.Run(String[] args, IFileSystem fileSystem, Func`1 projectSystemFactory) in C:\Sandbox\StartSharp\Serenity\src\Serenity.Net.CodeGenerator\Program.cs:line 77
C:\Users\Sandbox\source\repos\TestProject\TestProject\TestProject.Web\TestProject.Web.csproj(70,5): warning MSB3073: The command "dotnet sergen restore" exited with code 1.
C:\Users\Sandbox\source\repos\TestProject\TestProject\TestProject.Web\TestProject.Web.csproj(70,5): warning MSB4181: The "Exec" task returned false but did not log an error.
  Transforming MVC at: .\Imports\MVC
  Transforming ClientTypes at: .\Imports\ClientTypes
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  TestProject.Web -> C:\Users\Sandbox\source\repos\TestProject\TestProject\TestProject.Web\bin\Debug\net5.0\TestProject.Web.dll
  TestProject.Web -> C:\Users\Sandbox\source\repos\TestProject\TestProject\TestProject.Web\bin\Debug\net5.0\TestProject.Web.Views.dll
  Transforming ServerTypings at: .\Imports\ServerTypings

Build succeeded.

C:\Users\Sandbox\source\repos\TestProject\TestProject\TestProject.Web\TestProject.Web.csproj(70,5): warning MSB3073: The command "dotnet sergen restore" exited with code 1.
C:\Users\Sandbox\source\repos\TestProject\TestProject\TestProject.Web\TestProject.Web.csproj(70,5): warning MSB4181: The "Exec" task returned false but did not log an error.
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:25.51

**Comment by robalexclark** [comment]
Yep, I have this issue too - builds were fine until recently - has something changed in the dotnet tool?

**Comment by Nafhaa** [comment]
@GregorBiswanger your guidance will be helpful here

**Comment by robalexclark** [comment]
Not entirely sure how/why but I fixed this by upgrading to latest stable version of node (14.x)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Nafhaa** [comment]
Ohh, thanks for the suggestion will try with the stable update of node then

**Comment by Nafhaa** [comment]
No luck, the node version installed in this project is latest stable - 14.17.0
