### ISSUE TITLE
Breaking change in electron-updater caused by using Electron 11

### ISSUE THREAD

**Issue by tub5** [ElectronNET/Electron.NET#578]
CLI: 11.5.1.0
NuGet: 11.5.1

* **Target**: win-x64

As per [the ticket open for electron-updater](https://github.com/electron-userland/electron-builder/issues/6000) all auto update applications will break. As this appears to be the route the developers of the package are heading, the Electron version used in this package should be updated to at least Electron 12.

Steps to Reproduce:

1. Create a project with auto-updater enabled and properly set up
2. See the application throw stating that `Error: Cannot find module 'fs/promises'`

**Comment by ekuchynski** [comment]
Also got this surprise today. Built and deployed updates refused to start on many user machines.. :( Please help.

**Comment by lanluu** [comment]
We are suffering the same issue :-(. Any fix / hint is really appreciated.

**Comment by tub5** [comment]
> We are suffering the same issue :-(. Any fix / hint is really appreciated.

They have reverted to put the affected build of 4.0.9 of electron-updater as latest so you shouldn't have this issue for now. PR is in to upgrade our Electron version anyway and they will be reviewed tomorrow evening.

**Comment by lanluu** [comment]
> > We are suffering the same issue :-(. Any fix / hint is really appreciated.
> 
> They have reverted to put the affected build of 4.0.9 of electron-updater as latest so you shouldn't have this issue for now. PR is in to upgrade our Electron version anyway and they will be reviewed tomorrow evening.

Thank you for your information!
