### ISSUE TITLE
How to raise events for dom nodes in the back end of the application?

### ISSUE THREAD

**Issue by NMSLanX** [ElectronNET/Electron.NET#58]
And there is no a property named session in the webcontents. 
But have to say It's a very good project, thanks.

**Comment by GregorBiswanger** [comment]
Do you mean invoke a html click event as example?

Currently is only a communication with the backend and own JavaScript code possible with our IPC.

**Comment by yoDon** [comment]
If you run the Electron.Net demo app and click on Communicate between the two processes there are some good examples of how to do this.

In a nutshell, you assign an onclick function or similar to your DOM object as you normally would in javascript. Inside that javascript function, call ipcRenderer.send("my-message", myValue); to call the backend C# method registered for "my-message" and pass it myValue as an argument. You can use a similar pattern to send messages from the backend to frontend javascript.
