### ISSUE TITLE
Version flag not persisting with the referenced executable

### ISSUE THREAD

**Issue by tub5** [ElectronNET/Electron.NET#584]
When using the new Version flag, this is not being persisted to the dotnet command (I'm not sure why this wasn't in the PR).
You can bypass this by using `electronize build /target win /Version 2.0.13 /p:Version=2.0.13 /p:ProductVersion=2.0.13` however, this should not have to be the case.

* **Version**: 13.5.1

* **Target**: Windows

Steps to Reproduce:

1. use the `/Version` flag when building the `electronize build` command

**Comment by GregorBiswanger** [comment]
Would you like to quickly submit a pull request? :)

Then it should still be fixed for the 13.5.1 release.

**Comment by tub5** [comment]
@GregorBiswanger I'm just testing it now. Will submit within half an hour.

**Comment by tub5** [comment]
@GregorBiswanger PR in

**Comment by tub5** [comment]
Permission to stop hyperventilating now 😂

**Comment by GregorBiswanger** [comment]
yes you can run down the adrenaline now... 😂😂😂🥳

Thank you for your support!
