### ISSUE TITLE
Node Module is not working after packaging the application

### ISSUE THREAD

**Issue by leoubaid** [ElectronNET/Electron.NET#586]
Hi,  I install node module with NPM and its working fine in development environment, but getting " Cannot find module"  error in application after packaging it.

**Comment by melvin78** [comment]
Found any fix getting same issues?

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Comment by Yuvix25** [comment]
Same issue here, 23.6.1.
