### ISSUE TITLE
Election.net with custom web service

### ISSUE THREAD

**Issue by Jennal** [ElectronNET/Electron.NET#587]
Hi, thanks for this great job for C# users to use electron.

But ASP.NET/Blazor or something like that from Microsoft are too slow on startup, even on empty/simple project. It would takes more than 10s to start the app. The time is close to power on my computer till I see the windows login page.

I don't need features in ASP.NET or Blazor, I only need logic codes written by C#.

I find a much faster web service called [WatsonWebserver](https://github.com/jchristn/WatsonWebserver). It cost almost zero time to startup on an empty/simple project.

Is there a way to use WatsonWebserver or custom web service written by myself?

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
