### ISSUE TITLE
Redundant PublishReadyToRun parameters sent to dotnet if PublishReadyToRunShowWarning is used

### ISSUE THREAD

**Issue by denniskrq** [ElectronNET/Electron.NET#589]
* **Version**: 13.5.1

* **Target**: win7-x64;win

Steps to Reproduce:

1. Run `electronize build /dotnet-configuration Debug /target custom "win7-x64;win" /p:PublishSingleFile=false /p:PublishReadyToRunShowWarning=true`
2. Observe the printed `dotnet` command as: `dotnet publish -r win7-x64 -c "Debug" --output "C:\TestProject\obj\desktop\custom\bin" /p:PublishReadyToRun=true /p:PublishSingleFile=false /p:PublishReadyToRunShowWarning=true --self-contained`. Note the duplicated parameters for `PublishReadyToRun`

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
