### ISSUE TITLE
Lots of bogus intellisense errors

### ISSUE THREAD

**Issue by yoDon** [ElectronNET/Electron.NET#59]
I'm not sure whether I have something misconfigured or if this is a "known issue" but when I open any of the C# files in either Visual Studio or VS Code I get tons of intellisense errors, including complaints about things like System.String and void not being found (screenshot below). I've mainly been working in https://github.com/yoDon/Electron.NET-React-Typescript-MobX but I also get the same errors when looking at the main Electron.NET repo.

![image](https://user-images.githubusercontent.com/1760705/32859768-4d55062c-ca04-11e7-934b-fd6afbd47635.png)

**Comment by GregorBiswanger** [comment]
Mhh.. **Electron.NET-React-Typescript-MobX** works on my system...

When does the mistake come?

**Comment by yoDon** [comment]
So no intellisense errors when you open one of the C# files in Visual Studio to look at it? (like the above image)

**Comment by GregorBiswanger** [comment]
No I get no intellisense errors.. I used your currently master sources:

![image](https://user-images.githubusercontent.com/7336300/32863128-be532484-ca5a-11e7-91a5-490ae50a6e23.png)

**Comment by yoDon** [comment]
Drat. I'll spend some time deleting my visual studio prefs and hope for the best. Close this as no repro or leave it open for a bit in case others have similar reports?
