### ISSUE TITLE
Cannot Access being used by another process

### ISSUE THREAD

**Issue by raizpvp** [ElectronNET/Electron.NET#591]
* **Version**: 13.5.1.0 

* **Target**: .Net Core 5.0 & Node 15.10.0

* **Problem**: I have created an empty ASP.Net project. Performed all steps as described to install Electron.NET and include it in the project. Now when I enter "electronize start" I get this error:

* **Error**:
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018: Unerwarteter Fehler bei der GenerateBundle-Aufgabe. [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018: System.IO.IOException: The process cannot access the file 'C:\dev\HelloElectron\HelloElectron\obj\Host\bin\HelloElectron.exe' because it is being used by another process. [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite) [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.BinaryUtils.CopyFile(String sourcePath, String destinationPath) [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]
C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\dev\HelloElectron\HelloElectron\HelloElectron.csproj]

Steps to Reproduce:
Follow the install instruction.

**Comment by GregorBiswanger** [comment]
I created a new .NET 5 project and followed the setup steps. There's no problem.

Try deleting the obj\Host\-folder and try again. If necessary, try a project again in a different directory?

**Comment by PeterKnealeCMRI** [comment]
I get the same, .net 8 project. It runs once but after that the files remain locked and I cannot rebuild or rerun the application.
Cant remove the files either
```
$ rm -rf obj/
rm: cannot remove 'obj/Host/bin': Device or resource busy
rm: cannot remove 'obj/Host/node_modules/.bin': Device or resource busy
rm: cannot remove 'obj/Host/node_modules/electron/dist/icudtl.dat': Device or resource busy
rm: cannot remove 'obj/Host/node_modules/electron/dist/resources/default_app.asar': Device or resource busy
rm: cannot remove 'obj/Host/node_modules/electron/dist/v8_context_snapshot.bin': Device or resource busy
```
