### ISSUE TITLE
build linux failed on window

### ISSUE THREAD

**Issue by ghost** [ElectronNET/Electron.NET#597]
Package Electron App for Platform linux...
npx electron-builder --config=./bin/electron-builder.json --linux --x64 -c.elect
ronVersion=13.1.5
  鈥?electron-builder  version=22.11.7 os=6.3.9600
  鈥?loaded configuration  file=D:\CodeSpace\dotnet\Electron.NET API瀛︿範\Elect
ronNetCoreMvcDemos\ElectronNetCoreMvcDemos\obj\desktop\linux\bin\electron-builde
r.json
  鈥?description is missed in the package.json  appPackageFile=D:\CodeSpace\dotn
et\Electron.NET API瀛︿範\ElectronNetCoreMvcDemos\ElectronNetCoreMvcDemos\obj\de
sktop\linux\package.json
  鈥?packaging       platform=linux arch=x64 electron=13.1.5 appOutDir=D:\CodeSp
ace\dotnet\Electron.NET API瀛︿範\ElectronNetCoreMvcDemos\ElectronNetCoreMvcDemo
s\bin\Desktop\linux-unpacked
  鈥?scheduling remote build  target=snap arch=x64
  鈥?scheduling remote build  target=appImage arch=x64
  鈥?cannot get, wait  error=Get "https://service.electron.build/find-build-agen
t?no-cache=1gi6396": dial tcp 51.15.76.176:443: connectex: No connection could b
e made because the target machine actively refused it.

 my PC firewall is off.

**Comment by towerbit** [comment]
You can not build the linux version on windows at all since "https://service.electron.build/find-build-agent" is out of service.
Try to build the linux version on linux or WSL.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
