### ISSUE TITLE
[Bug] can't install on balzor webassembly

### ISSUE THREAD

**Issue by nguyentuan3691** [ElectronNET/Electron.NET#599]
* **version**:
 13.5.1

.NET Core version
* **5.0, visual studio 2019 16.11.0**

* **blazor webassembly**: 

Steps to Reproduce:

1. Create a new blazor webassembly
2. Attempt to install latest Electron.NET nuget package

when install on in blarzor webassembly then window error show message "The project references the ASP.NET Core shared framework, which is not supported by Blazor WebAssembly apps. Remove the framework reference if directly referenced, or the package reference that adds the framework reference."

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
