### ISSUE TITLE
Build command: Better platform target support 

### ISSUE THREAD

**Issue by robertmuehsig** [ElectronNET/Electron.NET#6]
Currently win means Win10, but electron can produce apps for Win8 and 7 as well. 
The same is for Linux (which is just ubuntu for us) and mac...

**Comment by Petermarcu** [comment]
This PR may address building apps for Win7 as well as OSX and Linux so apps built for each of them will run on any of the platforms supported by .NET Core 2.0. https://github.com/ElectronNET/Electron.NET/pull/38.

**Comment by robertmuehsig** [comment]
With the PR of @Petermarcu it should be working fine. Before the PR only the Electron Packer did produce "neutral" OS builds, now the .NET Core side should work on all supported OSs. 

Thanks @Petermarcu!

**Comment by cosminpopescu14** [comment]
hello !

I have the following issue in trying to instal the CLI package:
` Package 'ElectronNET.CLI 0.0.5' has a package type 'DotnetCliTool' that is not supported by project 'MyElectronMusicPlayer'
`
I mention I have 
```
  <ItemGroup>
    <DotNetCliToolReference Include="ElectronNET.CLI" Version="*" />
  </ItemGroup>
```
im my csproj file

**Comment by robertmuehsig** [comment]
Then it should be fine - CLI extensions are a bit different then normal packages.
