### ISSUE TITLE
How can i disable the error window?

### ISSUE THREAD

**Issue by yoxking** [ElectronNET/Electron.NET#608]
when load  url  frequently will be show error window.
c#:  mainWindow.LoadURL(url); 
![image](https://user-images.githubusercontent.com/28953145/135209132-ba185bee-a8e4-42da-8098-2b16e4e9feec.png)

how can i disable the error window?

**Comment by yoxking** [comment]
solved :  https://www.youtube.com/watch?v=-JV0MJdwT9k

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
