### ISSUE TITLE
Error trying to restore packages through command console

### ISSUE THREAD

**Issue by luisgal93** [ElectronNET/Electron.NET#61]
dotnet restore
  Restoring packages for C:\Users\MASTER\source\Workspaces\Quantica\Quantica.Apps\Quantica.Web.Dashboard\Quantica.Web.Dashboard.csproj...
  Restore completed in 11,91 ms for C:\Users\MASTER\source\Workspaces\Quantica\Quantica.Apps\Quantica.Common.Models\Quantica.Common.Models.csproj.
  Restore completed in 11,91 ms for C:\Users\MASTER\source\Workspaces\Quantica\Quantica\Quantica.Utilities.WebDavClient\Quantica.Utilities.WebDavClient.csproj.
  Restore completed in 26,44 ms for C:\Users\MASTER\source\Workspaces\Quantica\Quantica.Web\Quantica.Utilities.PdfToDocConverter\Quantica.Utilities.PdfToDocConverter.csproj.
  Restore completed in 29,62 ms for C:\Users\MASTER\source\Workspaces\Quantica\Quantica.Apps\Quantica.Common.DataAccess\Quantica.Common.DataAccess.csproj.
  Restore completed in 69,59 ms for C:\Users\MASTER\source\Workspaces\Quantica\Quantica.Apps\Quantica.Web.Dashboard\Quantica.Web.Dashboard.csproj.
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/javascript/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/windowsphone/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/silverlight/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/universal/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/lightswitch/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/wpf/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/winrt/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/windowsphone/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/silverlight/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/universal/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/lightswitch/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/wpf/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/windows-forms/FindPackagesById()?id='ElectronNET.CLI''.
  Response status code does not indicate success: 500 (Internal Server Error).
C:\Program Files\dotnet\sdk\2.0.3\NuGet.targets(102,5): error : Failed to retrieve information about 'ElectronNET.CLI' from remote source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='ElectronNET.CLI''. [C:\Users\MASTER\source\Workspaces\Quantica\Quantica.Web\Quantica.Web.sln]
C:\Program Files\dotnet\sdk\2.0.3\NuGet.targets(102,5): error :   Response status code does not indicate success: 500 (Internal Server Error). [C:\Users\MASTER\source\Workspaces\Quantica\Quantica.Web\Quantica.Web.sln]

**Comment by GregorBiswanger** [comment]
Do you use a local NuGet server?

**Comment by luisgal93** [comment]
No, I use the default NuGet Server, but additionally I use the NuGet Package Server from Syncfusion. Could this be causing a problem?

**Comment by robertmuehsig** [comment]
At least it is a 500 from their NuGet server. The NuGet Team has changed the server implementation (v3-endpoint)  for the "new" .net core NuGet packages.

**Comment by luisgal93** [comment]
What need I to do?

**Comment by GregorBiswanger** [comment]
Do you can try the Electron.NET-API Demos App on your system? 
[https://github.com/ElectronNET/electron.net-api-demos](https://github.com/ElectronNET/electron.net-api-demos)

**Comment by luisgal93** [comment]
I will do it.

**Comment by robertmuehsig** [comment]
Please comment on this issue if you still have problems to download our NuGet package.
