### ISSUE TITLE
Failed to build for target win or linux on macOS

### ISSUE THREAD

**Issue by aguang-xyz** [ElectronNET/Electron.NET#611]
### **Version**: 

* ElectronNET.CLI: `13.5.1.0`
* ElectronNET.API: `13.5.1`
* Dotnet: `5.0.401`
* Node: `14.17.3`

### **Target**: 

* `win` or `linux`

Steps to Reproduce:

1. Open a Electron.NET project on macOS
2. Run `electronize build /target win` or `electronize build /target linux`
3. Then I got the following error.

```
/usr/local/share/dotnet/sdk/5.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(316,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are using a supported runtime identifier, or set the PublishReadyToRun property to false.
```

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
