### ISSUE TITLE
AutoUpdater.ChannelAsync_set

### ISSUE THREAD

**Issue by richardhauer** [ElectronNET/Electron.NET#620]
I'm using the AutoUpdater from a static HTTP source (Azure Blob storage) using the `generic` provider.
I have updated the `electron.manifest.json` as directed in the Electron docs, adding `build.generateUpdatesFilesForAllChannels: true` and then set the `build.buildVersion: 1.1.1-alpha`.

There is also a 'win' section...
```
    "win": {
      "publish": {
        "provider": "generic",
        "url":  "https://azure-storage-url.z8.web.core.windows.net/pos/",
        "channel": "alpha"
      }
    }
```
I have noticed that setting the `channel` above when doing a build controls whether all three YML files ( `latest.yml`, `alpha.yml` and `beta.yml`) are produced or just `alpha` or `alpha` and `beta`.
So all that seems to be what I'd have expected.

In the Electron documentation it says that to set the "appUpdater.channel" property to the channel that you want the updater to check. (https://www.electron.build/auto-update#module_electron-updater.AppUpdater+channel)

The [AutoUpdater::ChannelAsync](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.API/AutoUpdater.cs#L229) has a getter, but no setter for this purpose.  [AutoUpdater::AllowPrerelease](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.API/AutoUpdater.cs#L80) is marked for the Github provider only.

Is there a reason there is no setter for the `ChannelAsync` property? Is there another way to use the Channel system?
I have workarounds but I'd rather use the standard features where possible.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
