### ISSUE TITLE
Need help with hosting the Electron app under an existing IIS website as an application

### ISSUE THREAD

**Issue by Karan-gathani** [ElectronNET/Electron.NET#627]
I am a newbie to Electron and trying to figure out how to host the application built using Electron.NET using .Net5 framework. Any kind of documents or youtube link or steps would help out in this regard.

**Comment by Karan-gathani** [comment]
CLosed it bymistakely. Looking forward for any possible solutions in this regard.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
