### ISSUE TITLE
Stuck on splashscreen on non-english Windows (Italian)

### ISSUE THREAD

**Issue by danatcofo** [ElectronNET/Electron.NET#630]
* **Version**: 13.5.1
* CORE: v5
* NodeJs: 14.5.*
* **Target**: Windows

Splashscreen fails to clear and continue on to main window

Steps to Reproduce:

1. Setup an **Italian** based language windows machine
2. Do the standard setup for default Electron.NET repo
3. Run the application. `./start.sh`
4. Observe that the splashscreen is never cleared and the application hangs in that state.

**Comment by danatcofo** [comment]
After adding some more logging inside main.js I received this message.

```
Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
```

added this on ln 286 of main.js
```JS
        apiProcess.stderr.on('data', (data) => console.error(`stderr: ${data}`));
        apiProcess.on('close', (code) => console.log(`ASP.NET Core Application: exited with code ${code}`));
```

**Comment by danatcofo** [comment]
and the source of the issue....

oh god

![image](https://user-images.githubusercontent.com/418147/144643222-b5561b58-6f54-46f7-a8fa-b77e8373256f.png)

**Comment by danatcofo** [comment]
Working solution

When publishing or running the applicaiton add the `/PublishReadyToRun true` argument to the command line.

i.e.

```
electronize start /target win /PublishReadyToRun true
electronize build /target win /PublishReadyToRun true
```

**Comment by schaveyt** [comment]
@danatcofo How were you able to hack the main.js without it being overwritten. I fine the the main.js that is created in my obj/ folder but don't know where the source of that is found.

**Comment by danatcofo** [comment]
It's inside electronnet.host/main.js 

There is a pr open that does basically what I did which was add logging of the process error output.

**Comment by schaveyt** [comment]
Where can find this on my development PC? Or do I need to pull down the repo and do things that way?

**Comment by danatcofo** [comment]
Yah pull the repo and reference a local nugget package.

**Comment by HeroinGyrl** [comment]
@danatcofo I downloaded your PR for .net 6 > https://github.com/ElectronNET/Electron.NET/pull/636  but I'm stuck on the splashscreen, do you know how I can fix this?

I tried to add the code snippet from you into the main.js but the log is not saying anything about a error.

```
stdout: info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:8003

stdout: ASP.NET Core host has fully started.

stdout: info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.

stdout: info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
```

**Comment by danatcofo** [comment]
My .net 6 PR doesn't include the logging that is mentioned prior.  Are you trying to build in Italian?  if so did you see the note about the workaround...

```
electronize start /target win /PublishReadyToRun true
electronize build /target win /PublishReadyToRun true
```

**Comment by HeroinGyrl** [comment]
> My .net 6 PR doesn't include the logging that is mentioned prior. Are you trying to build in Italian? if so did you see the note about the workaround...
> 
> ```
> electronize start /target win /PublishReadyToRun true
> electronize build /target win /PublishReadyToRun true
> ```

hey, I'm trying to run Electron.NET in .NET 6 but somehow I'm stuck at the SpashScreen, I cant find any workaround.

**Comment by HeroinGyrl** [comment]
I installed the h5 https://www.nuget.org/packages/h5.ElectronNET.API/16.0.4.23941 version which supports .NET 6

somehow only this version works for me all other version dont want to connect to Electron Socket
this message dont displays in your .NET 6 PR. maybe you know why it's the problem?
```
.NET Application connected... global.electronsocket -3vHwKDZjFt0QRJOAAAA 2022-03-03T16:03:44.868Z
stdout: ElectronNET socket connected on port 8000!
```

should someone has problems with that too, here is a working .net 6 for electron
```
Install-Package h5.ElectronNET.API -version 16.0.4.23941
```
```
dotnet tool install -g h5.ElectronNET.CLI -version 16.0.4.23941
```

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Comment by gsobrinhodev** [comment]
Friends, webapp is running normally when we check in browser, but the Electron App is not being initiated.

![image](https://github.com/ElectronNET/Electron.NET/assets/36978714/e17ae266-66e8-449d-ba49-e4fefbcd3ebc)

I'm on .net 6 and my Electron was updated.
