### ISSUE TITLE
Update to latest Electron version 16

### ISSUE THREAD

**Issue by lukasportal** [ElectronNET/Electron.NET#638]
Is there a plan on how often this project will update electron's version?
we're currently sitting at 13.1.5 for a good while now, and electronjs is already at 16.
What's needed to upgrade it or have some sort of ongoing release cycle with upgrades?

**Comment by GregorBiswanger** [comment]
I'm on vacation soon and will have a lot of time to really freshen up Electron.NET again.. Check PR and bring it in with .NET 6 support.. Electron 16.. WSL2 support and much more...

**Comment by danatcofo** [comment]
You do realize that 13.1.5 was only release 6 months ago... 

I know... thats ancient in javascript land /s

**Comment by GregorBiswanger** [comment]
@danatcofo Yes, the Electron team is very sporty :)

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
