### ISSUE TITLE
ElectronNET.CLI does not contain an inclusive lower bound

### ISSUE THREAD

**Issue by pandazzurro** [ElectronNET/Electron.NET#64]
This is my .csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElectronNET.API" Version="0.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="ElectronNET.CLI" Version="*" />
  </ItemGroup>

</Project>
```
My error:

NU1604: Project dependency ElectronNET.CLI does not contain an inclusive lower bound. **Include a lower bound** in the dependency version to ensure consistent restore results.

What dependency do I have to upgrade? I do not understand

I follow readme installation guide and I got stuck when I added this piece of code to .csproj
```
<ItemGroup>
         <DotNetCliToolReference Include="ElectronNET.CLI" Version="*" />
</ItemGroup>
```

Thanks 
Andrea

**Comment by GregorBiswanger** [comment]
Hi Andrea,
did you type the "dotnet restore" command after you edited the .csproj file?
When and where did you get the error message?

**Comment by pandazzurro** [comment]
I create new project in another machine.
After execute:
`dotnet electronize start`
There is an error:
![image](https://user-images.githubusercontent.com/7531792/34224328-cd29a5fe-e5c2-11e7-944c-9f921fd77b5b.png)

After that I clear .\obj folder but without success.


This [example](https://github.com/ElectronNET/electron.net-api-demos) work very well.

**Comment by GregorBiswanger** [comment]
Do you use first the `dotnet electronize init` command?

**Comment by pandazzurro** [comment]
Yep

**Comment by robertmuehsig** [comment]
Can you share your project?

**Comment by pandazzurro** [comment]
[Project](https://github.com/pandazzurro/Electron)

**Comment by robertmuehsig** [comment]
I will update the documentation - thanks for sharing!

**Comment by hard-rox** [comment]
My .csproj file contents are these.

![image](https://user-images.githubusercontent.com/20935652/42055336-a7cc8748-7b38-11e8-868f-a4b3206e70fd.png)
But when I enter this command-
`dotnet electronize start`
Then I got this error. What is the solution?
![image](https://user-images.githubusercontent.com/20935652/42055495-23960d4a-7b39-11e8-8b1f-49751ea01d57.png)
