### ISSUE TITLE
.Net 6 support.

### ISSUE THREAD

**Issue by sudongg** [ElectronNET/Electron.NET#640]
Hi,
The startup speed of .Net 6 applications has been greatly improved. Is it possible to add support for .Net 6 to solve the problem of slow startup speed?

**Comment by danatcofo** [comment]
There is an open pr for .net 6.  How about you go take a look.

**Comment by sudongg** [comment]
@danatcofo 
I tried .Net 6 branch, open project prompt, cannot find ElectronNET.WebApp.NET6.csproj，
I tried to manually add and run ElectronNET.CLI project, stuck on the startup page.
ElectronNET.WebApp project run error.

**Comment by GregorBiswanger** [comment]
PR are still being checked and the official support will come with the next big update.. but got it to work with the current version without any problems..

**Comment by sirkadirov** [comment]
@GregorBiswanger Thank you! Can't wait to try out my Electron.NET-powered apps over .NET 6 😃!

**Comment by vinaykulkarni89** [comment]
Hi @GregorBiswanger  really appreciate your efforts
We are eagerly waiting for the new big update

**Comment by szymonsmykala1** [comment]
I think it is ready

**Comment by Bhargavi-Gowri** [comment]
Hi @GregorBiswanger , 

Could you kindly share if there is any tentative timeline by when Electron.NET with .NET 6.0 support is planned to be publicly available?  

Thanks,
Bhargavi Gowri.

**Comment by mu88** [comment]
Hi @GregorBiswanger - what is the current state of this issue?

Thx for your work!

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
