### ISSUE TITLE
How can I communicate with the existing Vue cli project

### ISSUE THREAD

**Issue by lzb949838390** [ElectronNET/Electron.NET#642]
How can I communicate with the existing Vue cli project

demo-listens：
Electron.IpcMain.On("testOn", (data) =>
            {

            });

demo-send:
Electron.IpcMain.Send(browserWindow, "test", new { });

It doesn't seem to work.

and  It doesn't seem to work.

**Comment by danatcofo** [comment]
Those are sending and receiving from the browser window.  You will need to write some JavaScript in the browser window to listens for those commands or send them respectively.  It's not in internal communication path between parts of the aspnet app.

Look at the sample project in the repo, it will give you an start of how to do this.
