### ISSUE TITLE
Splashscreen transparency does not work on Linux

### ISSUE THREAD

**Issue by jeffdod** [ElectronNET/Electron.NET#644]
I'm building an Electron.NET app for Windows, Mac, and Linux. On Windows and the Mac, my .png file with transparency works fine as a splashscreen when specified in the electron.manifest.json file under the "splashscreen" : "imageFile" option.

However, on Linux (specifically, Ubuntu 21.04), although the splashscreen displays, the transparency in the .png file is not observed, and instead I see a black background where the transparency should be.

I looked at other splashscreen examples on the internet, and I also looked at the various options in the electron-builder documentation, but didn't see any way to tweak this for Linux.

Are transparent .png files allowed on Linux as the splashscreen images?

**Comment by danatcofo** [comment]
This is an electron issue.  Not sure if this is the original link when I found it last year or not but don't see it being fixed soon.

https://github.com/electron/electron/issues/15947

**Comment by jeffdod** [comment]
Thanks. Yeah, I'm not going to hold my breath waiting for this one to be fixed, based on what I saw in that thread.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
