### ISSUE TITLE
error NETSDK1095:The selected target platform or architecture does not support optimizing the performance of the assembly.

### ISSUE THREAD

**Issue by lzb949838390** [ElectronNET/Electron.NET#652]
🚨 The issue tracker is not for questions 🚨

Release Linux
I tried to execute the command `electronize build /target linux /p:publishSingleFile=false`
An error occurred.
Message: 
error NETSDK1095:The selected target platform or architecture does not support optimizing the performance of the assembly.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
