### ISSUE TITLE
Why does electron is so bad?

### ISSUE THREAD

**Issue by HeroinGyrl** [ElectronNET/Electron.NET#653]
1. my electron application takes very long until it actually starts, 
2. whenever i publish my application the splashscreen does not show up anymore. but on debug it shows?

I like Electron:NET I think you guys actually cant do something there.
and no its not because of my project. I created a whole new project without any changes and electron still takes long to start.

I mean why not moving to neutralinoJS there is acutally no one who made a .net support from it.

regarding

**Comment by GregorBiswanger** [comment]
Electron is a powerful and sophisticated solution.

Unfortunately, malware developers use Electron too. So that under Windows the Windows Defender slows down the start. The only solution here would be to exclude realtime for your own app or to buy a certificate.

As a great comparison, open Visual Studio Code... and open a new, unknown electron app.. four seconds are only slowed down by windows defender.. a shame, because electron is based on the image, although electron is extremely powerful..

**Comment by HeroinGyrl** [comment]
> Electron is a powerful and sophisticated solution.
> 
> Unfortunately, malware developers use Electron too. So that under Windows the Windows Defender slows down the start. The only solution here would be to exclude realtime for your own app or to buy a certificate.
> 
> As a great comparison, open Visual Studio Code... and open a new, unknown electron app.. four seconds are only slowed down by windows defender.. a shame, because electron is based on the image, although electron is extremely powerful..

I mean discord uses electron too and its really good actually. maybe its also because of .net. well lets see the future.
I think MAUI will probally replace Electron.NET but I cant customize the window there so I will stay at electron.

do you have a solution to make images in electron like in firefox? currently chromium makes it blur but on firefox not.

regarding

**Comment by GregorBiswanger** [comment]
MAUI is XAML based if I remember correctly. MAUI is only interesting for .NET devs and therefore a much smaller community. If it's more suitable for you, then have fun with MAUI!

Are you using a zoom level? Try turning off FXAA from your GPU...

**Comment by HeroinGyrl** [comment]
> MAUI is XAML based if I remember correctly. MAUI is only interesting for .NET devs and therefore a much smaller community. If it's more suitable for you, then have fun with MAUI!
> 
MAUI has also support for blazor. currently I didnt found a way to customize the window of MAUI 

![vs22_p4_new_project](https://user-images.githubusercontent.com/33988671/148297357-437d7147-231d-4b2b-8bb0-e55c200bb9fe.jpg)

![Screenshot 2022-01-05 231932](https://user-images.githubusercontent.com/33988671/148297795-dbc36b1c-0288-48ee-8cd6-60006d701679.png)

> Are you using a zoom level? Try turning off FXAA from your GPU...

I will look at this thankxs!
