### ISSUE TITLE
Failed to set icon for linux build in Visual studio code

### ISSUE THREAD

**Issue by mazm786** [ElectronNET/Electron.NET#659]
Failed to set icon for linux build in Visual studio code. Even default electron icon is not displayed. 
OS: Ubuntu 18.04.6 LTS

* **5.30.1**: 

* **.net5.0**

* **linux**: 

### **_Procedure 1 Used_**
**.csproj file**
`
﻿<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Description>Proj Server</Description>
    <IsPackable>true</IsPackable>
<ApplicationIcon>build/icons/linux_256x256.png</ApplicationIcon>
  </PropertyGroup>
<ItemGroup>
   <Content Include="build/icons/linux_256x256.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
   </Content>
</ItemGroup>
<ItemGroup>
<EmbeddedResource Include="build/icons/linux_256x256.png" />
</ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ElectronNET.API" Version="5.30.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="electron.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>`

### **Procedure 2 used**

**electron.manifest.json file** where icon file actual path: in build/icons/linux_256x256.png.
Note: **I have tried both paths as without directory names and with directory name but no success.**
`{
  "executable": "MyElectronMusicPlayer",
  "build": {
    "appId": "com.friasoftit.electron-auto-update",
    "productName": "Electron Auto Update",
    "linux": {
      "category":"Utility",
      "icon": "linux_256x256.png"
    }
}`

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
