### ISSUE TITLE
Closing Application over Console

### ISSUE THREAD

**Issue by bulllox** [ElectronNET/Electron.NET#661]
Don't know if its a Bug or something!

Right now i programming a App that sould be able to run on a Server and Pc what means you don't have a Window on the Server.
Now i found out that when you close the App with crtl+C Electron will still be running.

Expected behavior:
Electron process will stop when pressing strg+c in console

Well and here a litte Question :)

I know there is Electron.App.Exit() but how do u call it on crtl+c?

Edit: changed strg to ctrl XD did just read the keyboard withozt translating Xd

**Comment by danatcofo** [comment]
What is strg+c?  is that the same as ctrl+c?  Probably my lack of command line usage but I've never heard of that combo.

On a tangent note... Why would you run electron on a server?  I would expect that if you have a server (command line only) and a desktop (gui) deployments that you would structure your projects to output 2 different applications that consume shared projects/packages.

As a side note, this may be the inappropriate place to bring the issue up as a bug as your trying to act against the electron application itself and not the core app that the electron app spins up.  You might be better served to research this over in the  electron channels.  The project covers linking the two technologies together, not solving all the issues inherited from them.
