### ISSUE TITLE
Setting Modal = true in BrowserOptions does not work

### ISSUE THREAD

**Issue by MutatedGamer** [ElectronNET/Electron.NET#666]
* **Version**: 13.5.1

* **Target**:  windows

If you set `BrowserWindowOptions.Modal = true` when creating a new `BrowserWindow`, the created window will not be a modal window even after setting the parent.

Consider this code:

```cs
var parent = Electron.WindowManager.BrowserWindows.First(); // assume a main window exists and this returns it
var child = await Electron.WindowManager.CreateWindowAsync(
            new BrowserWindowOptions
            {
                Show = false,
                Modal = true
            });
child.SetParentWindow(parent);

child.OnReadyToShow += () =>
{
    child.Show();
}

child.OnShow += async () =>
{
    var isModal = await child.IsModalAsync();
}
```

The observed behavior of the child window is that it is NOT a modal window, and you can still interact with the main window (`parent`). The value of `isModal` in the `OnShow` handler is `false`, too.

I haven't investigated this, but it's possible that for modal windows to work the `parent` must be set inside the `BrowserWindowOptions`: https://www.electronjs.org/docs/latest/api/browser-window/#modal-windows

**Comment by MutatedGamer** [comment]
Update: I tested some changes locally and can confirm that setting a `parent` in the `BrowserWindowOptions` fixes the issue. Would you like me to make a PR with my test changes?

**Comment by danatcofo** [comment]
Interesting... id be interested to see if the javascript version of the add parent works or not.  If it does work, sounds like a bug in the implementation of that function.

**Comment by danatcofo** [comment]
Well if thats the case then this is less a bug and more of a documentation issue.  You might add to the readme.

I think more and more we need a howto or faq or something about some of these common issues.

**Comment by MutatedGamer** [comment]
@danatcofo unfortunately it's not just a documentation issue. To create a modal window, ElectronNET needs to add the `Parent` property to `BrowserWindowOptions`. It's currently impossible to create a modal window in C#.

**Comment by MonishaMaryA** [comment]
Hi @MutatedGamer 

 We are facing the same issue. We would like to try out the fix you have made locally. Is it possible for you to share the updated code for us to try out? If sharing the code is not possible by any chance please let us know the list of changes to try out the fix. 

Also, please let us know if there is any plan to release the fix anytime soon

**Comment by MutatedGamer** [comment]
@MonishaMaryA I'll submit a pull request this weekend with the changes I made to get it working

**Comment by MonishaMaryA** [comment]
@MutatedGamer 

Thanks for the update. Let us know once you submit a pull request. Do you have any idea on when the pull request will be merged and released?

**Comment by MutatedGamer** [comment]
@MonishaMaryA I created PR https://github.com/ElectronNET/Electron.NET/pull/673

I cannot speak for when it would likely get merged or released. I've been working off a local build of the library that I push to a local filesystem nuget feed.

**Comment by MonishaMaryA** [comment]
Sure @MutatedGamer

Thank you so much for updating the fix and sharing the PR. We will also try to build locally and work.

**Comment by MonishaMaryA** [comment]
@robertmuehsig , @GregorBiswanger 

Could you please let us know when the pull request #673 will be merged and released?

**Comment by MonishaMaryA** [comment]
Hi @GregorBiswanger ,

In the latest release 23.6.1, this fix is not reflected. Could you please check on this issue again?

**Comment by MonishaMaryA** [comment]
Hi @GregorBiswanger and @FlorianRappl 

I see that the PR **673** was merged to master branch which is now stale. We need this to be fixed as soon as possible. Could you please let us know if there is any possibility for fixing this and release  the update any time sooner
