### ISSUE TITLE
OSX processes fail to shut down on close

### ISSUE THREAD

**Issue by yoDon** [ElectronNET/Electron.NET#68]
In both dev and packaged builds, closing the macOS application window kills the Host process but leaves the inner application process running as a high-cpu-consuming zombie that needs to be manually killed via the Activity Monitor.

**Comment by BrianAllred** [comment]
This can happen if you use invisible windows (for background processes) and don't close them out or an error occurs before they close. I was experiencing the same thing on Windows until I added a try-catch-finally where the finally called the close all windows method.

Might try that and see if it helps.

**Comment by GregorBiswanger** [comment]
@yoDon do you try out the newest version of API and CLI (0.0.9)?

**Comment by netpoetica** [comment]
Two things: 1) I am still seeing this issue on Mac OSX for sure. Electron window will close, but background process remains relentlessly. And 2) I do not see a CloseAllWindows method anywhere - is there one? I have confirmed in the WillQuit event that there is only 1 window in my application, yet when closed, background process remains.

Additionally, the .Quit() function says "It is possible that a window cancels the quitting by returning false in the beforeunload event handler." however, there is no BeforeUnload event handler on Electron.App. Is there supposed to be?
