### ISSUE TITLE
Can we make deb installer ?

### ISSUE THREAD

**Issue by mazm786** [ElectronNET/Electron.NET#684]
Can we make deb installer ?
What changes in json file and which?

**Comment by danatcofo** [comment]
Yes, look up the json structure in the electron-builder documentation.  I can post an example later.

**Comment by danatcofo** [comment]
https://www.electron.build/configuration/linux.html

```
{
  "build": {
     "linux": {
        ... other linux generic properties
        "target": [ "deb", "rpm", "snap", "etc..."],
     },
    "deb": {
        ... deb specific properties
    }
  }
}
```

**Comment by mazm786** [comment]
> https://www.electron.build/configuration/linux.html
> 
> ```
> {
>   "build": {
>      "linux": {
>         ... other linux generic properties
>         "target": [ "deb", "rpm", "snap", "etc..."],
>      },
>     "deb": {
>         ... deb specific properties
>     }
>   }
> }
> ```

1. What are deb specific properties. Please Describe.
2. From which version of Electron.Net version, Deb installer making feature is available ?
