### ISSUE TITLE
Electronize start command throws unhandled exception

### ISSUE THREAD

**Issue by GevorDanielyan** [ElectronNET/Electron.NET#688]
Hello everyone.  I'm created Blazor Server App in .NET 6, and when I want to start simple Electron application I'm getting the following error:

![image](https://user-images.githubusercontent.com/10724174/165752596-9bd5e787-3b29-44c1-b5ad-3c078d57a916.png)

What would be a reason? Can you help me? 
Thanks in advance

**Comment by mbielski** [comment]
Getting the exact same thing. Init threw an error too, but at least it created the manifest file. VS2022 Community, W11, tried both .Net 5 and .Net 6 and got the same error.

**Comment by GevorDanielyan** [comment]
> Getting the exact same thing. Init threw an error too, but at least it created the manifest file. VS2022 Community, W11, tried both .Net 5 and .Net 6 and got the same error.

@mbielski , in .NET 6 don't have support, Electronize NET works up to .NET 5. For my side, this issue solved, it can be network issue, please check your firewall, maybe it blocks.

**Comment by GevorDanielyan** [comment]
@mbielski using Electron, you are supposed to have installed NodeJs before using Electron NET.

**Comment by mbielski** [comment]
@GevorDanielyan yes, I know that. You generally expect something to be installed when you check the box for it. I still have a problem with electronize init but am pursuing that in the appropriate issue. Thanks.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
