### ISSUE TITLE
Merge conflict tag detected in ElectronNET.API\BridgeConnector.cs

### ISSUE THREAD

**Issue by minyuanchen** [ElectronNET/Electron.NET#693]
* **Version**: 

* **Target**: Windows

Steps to Reproduce:

1. Get the latest code
2. Run "electronize start"
![螢幕截圖 2022-05-11 11 59 47](https://user-images.githubusercontent.com/23494376/167766964-e06571dd-12e0-4803-8598-e6a650d300bf.png)

**Comment by mz-celldom** [comment]
Also in StartElectronCommand.cs and in BuildCommand.cs
```
grep '>>>>>' -rn --include *.cs
ElectronNET.API/BridgeConnector.cs:423:>>>>>>> 64e058b0b59a4fbbd6c0ec9de2ee1850a66684c4
ElectronNET.CLI/Commands/StartElectronCommand.cs:125:>>>>>>> 2331ef43b4c2028c57564f3a8c885555c81661d4
ElectronNET.CLI/Commands/BuildCommand.cs:127:>>>>>>> 5338749e4d2b0fcd9c46bad1a61e5c7d7d0f18cc
ElectronNET.CLI/Commands/BuildCommand.cs:285:>>>>>>> 5338749e4d2b0fcd9c46bad1a61e5c7d7d0f18cc
```

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
