### ISSUE TITLE
Current master has unresolved merge conflicts.

### ISSUE THREAD

**Issue by danatcofo** [ElectronNET/Electron.NET#697]
There wasn't due diligence in reviewing some changes or testing the code.  These 3 areas have unresolved conflicts baked into the files.  This also indicates that there might be some other logic conflicts as well baked into the files given that BridgeConnector is used heavily in many areas.

* [ElectronNet.API/BridgeConnector.cs](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.API/BridgeConnector.cs#L301)
* [ElectronNet.CLI/Commands/BuildCommand.cs](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.CLI/Commands/BuildCommand.cs#L123)
* [ElectronNet.CLI/Commands/StartElectronCommand.cs](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.CLI/Commands/StartElectronCommand.cs#L101)

**Comment by danatcofo** [comment]
inside BuildCommand.cs we have these lines where `defaultReadyToRun` & `defaultSingleFile` are undefined

```csharp
            var dotNetPublishFlags = new Dictionary<string, string>
            {
                {"/p:PublishReadyToRun", parser.TryGet(_paramPublishReadyToRun, out var rtr) ? rtr[0] : defaultReadyToRun},
                {"/p:PublishSingleFile", parser.TryGet(_paramPublishSingleFile, out var psf) ? psf[0] : defaultSingleFile},
            };
```

**Comment by danatcofo** [comment]
Looking at the changes... seems like the build/start command updates were both my commits, however looks like they conflicted and were not resolved as part of a merge by Gregor... I'm working on a fix, just documenting the issue here right now.

**Comment by theolivenbaum** [comment]
@danatcofo did you check against the PR or my fork? Just because there's plenty that has happened there after the original PR

**Comment by danatcofo** [comment]
@theolivenbaum I did a blame on the BridgeConnector inside master branch.  The changes appear to be from a merge of one of your other pr's that wasn't properly tested prior to commit of the merge.  This is leaving master branch in a non-working state.  This is totally not your doing as there was a slew of merges at that time and you were not the only one's who got sideswiped here.  However there is enough going on with your changes that I don't feel comfortable fixing it without messing something up.  Its a fairly broad scope of changes to ensure works correctly.  

Yes you have another PR open now of ongoing changes but that doesn't resolve whats going on with current master.

**Comment by bigredhdl** [comment]
@danatcofo , @GregorBiswanger or @theolivenbaum Can any of you recommend a way forward on this?

**Comment by GregorBiswanger** [comment]
@bigredhdl I'm currently waiting for @theolivenbaum to check the current branch again. Code is otherwise compatible. only an error message comes up during the build. If the error is fixed, we can publish a new release as soon as possible.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
