### ISSUE TITLE
How to change the default icon inside of application?

### ISSUE THREAD

**Issue by ZedZipDev** [ElectronNET/Electron.NET#700]
I'd like to change the default Electron.NET icon with my own. How can I do it?
I have tried in _Host.cshtml
```
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Database App</title>
    <base href="~/" />
   <link rel="icon" type="image/x-icon" href="favicon2.ico" />

```

It does not work.

Ok, then I did it in the Startup.cs
```
       private async void CreateWindow()
        {
            // - original 
            //var window = await Electron.WindowManager.CreateWindowAsync();

            //window.OnClosed += () => {
            //    Electron.App.Quit();
            //};

            // -----------new

            string icon = "favicon2.ico";
			var window = await Electron.WindowManager.CreateWindowAsync(
				new BrowserWindowOptions
				{
					Icon = icon
				});

			window.OnClosed += () => {
				Electron.App.Quit();
			};
        }

```

Again: does not work.
What I do wrong? How to change the default icon?

**Comment by ggomarighetti** [comment]
#### Resume
The configuration to establish which will be the icon of your application as well as its relative location, is in electron.manifest.json.

In a default configuration you must go to line 18 of your configuration, position yourself at the end of the configuration and paste the attached code.

There you will have an idea to establish the relative directory of the icon that you want to use, in case of linux and mac I believe that it should be .png and in case of windows .ico.

#### Code
```
    "win": {
      "icon": "../../../Build/alphagob.ico"
    },
```

**Comment by Taster-git** [comment]
> #### Resume
> The configuration to establish which will be the icon of your application as well as its relative location, is in electron.manifest.json.
> 
> In a default configuration you must go to line 18 of your configuration, position yourself at the end of the configuration and paste the attached code.
> 
> There you will have an idea to establish the relative directory of the icon that you want to use, in case of linux and mac I believe that it should be .png and in case of windows .ico.
> 
> #### Code
> ```
>     "win": {
>       "icon": "../../../Build/alphagob.ico"
>     },
> ```

How to do it for Linux ?????

**Comment by Jamie-Cappel-Chiron** [comment]
```
    "win": {
      "icon": "../../../Build/alphagob.ico"
    },
```

Hmm.. Have tried the following above solution to no effect.

**Comment by jamieyello** [comment]
I've tried fixing this for several days straight, I've tried putting the icon everywhere and I'm certain this must be some kind of bug.

I've tried the recommended

```
  "win": {
    "icon": "../../../build/icon.ico"
  }
```

Then this (which worked for someone)

```
  "win": {
    "icon": "bin/build/icon.png"
  }
```

Still "application icon not set". I've tried converting it to a PNG as well. As a last-ditch effort, I have edited the compiled exe to swap out the icon, but I worry that may set off security warnings when deployed.

I've double, triple, and quadruple-checked to ensure that the path names are valid relative to the directory the console says it's running from. I've compared my project to the SilverR one as well, and I can't tell any difference.

So I guess my last ditch effort should be replacing the default ElectronNET builder icon in the builder program files themselves.

**Comment by jamieyello** [comment]
Ok, so I found out that the "win" json object was in the wrong place in my manifest file.

In the above .json file, after moving the "win" section to be right after the "build" object it finally used the icon I wanted. So it was my fault, after all. No bug.
