### ISSUE TITLE
How to hide standard Electron Menu ?

### ISSUE THREAD

**Issue by ZedZipDev** [ElectronNET/Electron.NET#701]
How to hide the standard Menu : File, Edit, View .... ? I do in Startup:

```
var window = await Electron.WindowManager.CreateWindowAsync();
window.RemoveMenu(); // <-------------
window.OnClosed += () => {
Electron.App.Quit();
};

```It works but: the app starts, the menu appears(!) for 2-3 secs and then disappeared. Is it possible to hide it at all?

**Comment by ggomarighetti** [comment]
#### Resume
You can try passing as a parameter to the window manager the configuration to hide it automatically.
I attach an example.

#### Code
`
var browserWindowOptions = new BrowserWindowOptions
            {
                Title = "Electron.NET",
                Width = 1024,
                Height = 768,
                MinWidth = 800,
                MinHeight = 600,

                // Recommended configuration
                AutoHideMenuBar = true,

                Show = false,
                Frame = false,
                WebPreferences = new WebPreferences
                {
                    WebSecurity = false
                }
            };

            var browserWindow = await Electron.WindowManager.CreateWindowAsync(browserWindowOptions);
`
