### ISSUE TITLE
The framework version '5.0.0' (x64) was not found. But 6.0.6 is installed

### ISSUE THREAD

**Issue by f4n0** [ElectronNET/Electron.NET#704]
Hi,
I've created a pipeline for my project. 
I've installed Electron.Net and Electron.Net.CLI but when I try to Electronize it throws me:

Tool 'electronnet.cli' (version '13.5.1') was successfully installed.
Executing Electronize
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.6 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

My project is NET6, locally I can build it without any problem, is there something I can do?

**Comment by f4n0** [comment]
I hope it will be merged soon!

**Comment by brandochn** [comment]
Hi Guys,

Here the same issue.

**Comment by Mr-Technician** [comment]
> The latest version of the `electronnet.cli` published to nuget doesn't work with net6.0, it is only built for net5.0. You have to build in the `ElectronNET.CLI` directory from master in this repo.

What do you mean by this? That I need to build my code within this existing repository?

**Comment by delasource** [comment]
.net5 is [out of support since May 10](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). 

The CLI should be updated to .net6 asap!

**Comment by GregorBiswanger** [comment]
Currently there are still errors when running from the current status. We had a major PR #681 and need to find out what the problem is. Maybe one of you will find something.

**Comment by bigredhdl** [comment]
Just checking in here.  I see PR #681 is merged, but is there still an outstanding issue before a .net 6 CLI can be published to nuget?  I'm trying to get a blazor app we upgraded to .net 6 working again, but my app is failing to launch.  I also tried a quick:

> dotnet new blazorserver
> electronize init
> electronize start

using my own build of the CLI, but that didn't work either.

**Comment by dnviti** [comment]
Today still this error occurs...

**Comment by Jinjinov** [comment]
I would like to use ElectronNET with .NET 7 when it comes out this Tuesday (November 8th, 2022)

**Comment by rthm93** [comment]
I am using electronnet.cli 13.5.1, still having the same issue.

**Comment by retvari** [comment]
Same issue here... please publish to nuget!

**Comment by theolivenbaum** [comment]
Meanwhile you can use this package, it is built targeting net70: https://www.nuget.org/packages/h5.ElectronNET.CLI/

**Comment by GregorBiswanger** [comment]
@theolivenbaum Can you please check the repository, after your pr we got another error. When that is fixed, we can finally publish the new release with .net 7 support in general

**Comment by theolivenbaum** [comment]
Hi @GregorBiswanger, which error you mean?

**Comment by brandochn** [comment]
Hi @theolivenbaum, I think the error @GregorBiswanger mentionded is this #681

**Comment by yuriiproniuk** [comment]
Hello @GregorBiswanger @theolivenbaum , do I understand correctly that for apps targeting .NET 6 and higher from now on should be used https://github.com/theolivenbaum/electron-sharp and Electron.NET is not going to support targeting .NET 6?

**Comment by GregorBiswanger** [comment]
@yuriiproniuk A new Electron.NET Update with .NET 7 Support is coming the next days

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
