### ISSUE TITLE
Mac desktop builds can only be run once

### ISSUE THREAD

**Issue by yoDon** [ElectronNET/Electron.NET#71]
It looks like running OSX builds of the app causes the app to modify itself and breaking itself somehow.

Here's what I'm seeing:

1. build full desktop OSX app
2. before running the app, make a copy of the app
3. run the app, close it, kill the zombie child process ([per this issue](https://github.com/ElectronNET/Electron.NET/issues/68)), and run the app a 2nd time
- Expected behavior: App runs the same both times
- Actual behavior: App runs normally the first time, fails to show or populate window the 2nd time
- Additional info: If you run the app from the commandline, you can see that the initial host processes are dumping less info to the command line on the 2nd run than on the first run but not reporting errors
4. if needed, kill zombie child process
5. run the copy of the app
- Expected behavior: Running the app shouldn't mutate the app, so the original and copied versions of the app should behave the same (eg. the copy shouldn't run if the original app no longer runs)
- Actual behavior: The copy of the app runs once, then fails to run, demonstrating that running the app modifies the app

**Comment by BrianAllred** [comment]
Seeing the same behavior on Linux (although no zombie process for me).

**Comment by aguedob** [comment]
Same issue here

**Comment by GregorBiswanger** [comment]
Fixed with the new version of Electron.NET.
