### ISSUE TITLE
Version 18.6.1

### ISSUE THREAD

**Issue by vinaykulkarni89** [ElectronNET/Electron.NET#710]
Hi,
When we can expect the release of version 18.6.1
Waiting for this update from long, this will be really helpful update

**Comment by GregorBiswanger** [comment]
Currently, an important pull request (https://github.com/ElectronNET/Electron.NET/pull/681) cannot be merged. That would be important for the next big release. As soon as the project can be built again, the next version will be available. I'm really busy right now and could use some help here.

**Comment by vinaykulkarni89** [comment]
Hi @GregorBiswanger I am not much experienced with git as being on architecture side mostly.  If I can get guidance I would love to help here

**Comment by duncanawoods** [comment]
@GregorBiswanger I'm quite desperate for the update to net6 - running elecronize from the stable and git head both require net5 to run and net5 is now obsolete. This means it's not provided in apt or the ppas by Microsoft for Ubuntu 22.

Let me know if there is something I can do to help or if there is a quick fix I could apply to let it run on with only net6. Thanks!

**Comment by GregorBiswanger** [comment]
We will bring an update to .NET 7 as soon as possible. We are just waiting for a bug fix from @theolivenbaum from his pull request (#681).

**Comment by duncanawoods** [comment]
@theolivenbaum hey Rafael - how's it for making progress on the pull request? Anything we can do to help you out?

**Comment by liebki** [comment]
Can't wait too 🥹

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Comment by vinaykulkarni89** [comment]
Thanks and congratulation @GregorBiswanger
