### ISSUE TITLE
Version 13.1.5 --no-self-contained does not work

### ISSUE THREAD

**Issue by drowhunter** [ElectronNET/Electron.NET#712]
Electron Version 13.5.1

 
.Net Core 6
NodeJS 16.16.1

* **Target**: 
windows

runs with --self-contained

Steps to Reproduce:

```
dotnet tool run electronize build /target win /dotnet-publish --no-self-contained
```

Produces the following output

```
Build Electron Application...
Arguments:
        target = win
        dotnet-publish = --no-self-contained
Build ASP.NET Core App for win-x64...
Executing dotnet publish in this directory: C:\_src\myapp\obj\desktop\win
Build ASP.NET Core App for win-x64 under Release-Configuration...
dotnet publish -r win-x64 -c "Release" --output "C:\_src\myapp\obj\desktop\win\bin" /p:PublishReadyToRun=true /p:PublishSingleFile=true --self-contained

```

**Comment by drowhunter** [comment]
I just noticed what is going on.  By downloading the source code and building myself, it seems that it works.  The latest release that is installed when running `dotnet tool install electronnet.cli`  installs 13.5.1  which is before `/dotnet-publsh` was added.

when will a new build be released?

**Comment by m3nax** [comment]
Hi @drowhunter, here is the issue that talks about the new version -> #710

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Comment by tomshane** [comment]
I'm using the latest version and no matter what arguments I add in the command line, I can't get rid of automatically added --self-contained parameter.

I tried:  
```
* electronize build /target win /dotnet-publish --no-self-contained
* electronize build /target win /dotnet-publish --self-contained false
* electronize build /target win /PublishSingleFile false /PublishReadyToRun false /dotnet-publish --self-contained false
* electronize build /target win /PublishSingleFile false /PublishReadyToRun false /dotnet-publish --no-self-contained
```

Everytime --self-contained is added to the command:

`dotnet publish -r win-x64 -c "Release" --output "C:\Downloads\ReactApp2\ReactApp2.Server\obj\desktop\win\bin" /p:PublishReadyToRun=true /p:PublishSingleFile=true --self-contained`
