### ISSUE TITLE
Satellite assemblies are not packaged for OSX and Linux

### ISSUE THREAD

**Issue by tonsnoei** [ElectronNET/Electron.NET#722]
* **Version**: 13.5.1.0

.NET 6.0 / Node 18.7.0

* **Target**: OSX / Linux

I made a donation today (snoei.net) to support this great initiative.

Steps to Reproduce (osx):

1. I have a project with satellite assemblies from a third party (DevExpress)
2. I put the Dutch satellite assemblies within the `bin/release/osx-64/nl` directory
3. I ran `electronize build /target osx /PublishSingleFile false`
4. After starting the app, the language is not available.
5. Same for linux builds
6. However, when I do the same on Windows machine, the Dutch language is showing up and working correctly.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
