### ISSUE TITLE
Custom

### ISSUE THREAD

**Issue by Cav-jj** [ElectronNET/Electron.NET#723]
Hello I'm using h5.ElectronNET latest on arm64

and when I use 

'electronize-h5 build /target custom "linux-arm64;linux"'

it build as "amd64" and not as "arm64"

anny ides why???

**Comment by riboyama** [comment]
Use /target custom "linux-arm64;" /electron-arch arm64

**Comment by Cav-jj** [comment]
okej tryd it but snapp package wont buld

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
