### ISSUE TITLE
Publis current main

### ISSUE THREAD

**Issue by damikun** [ElectronNET/Electron.NET#730]
Hi @GregorBiswanger  There was more helpful pulls allready merged over long time but release is more than year old.. Can you publish what is in main?

(I currently building custom package to make it work)

Thx

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
