### ISSUE TITLE
Local development on M1 machine using Intel process

### ISSUE THREAD

**Issue by lukasportal** [ElectronNET/Electron.NET#731]
* **Version**:  13.5.1
* **Target**: .net 6 mac arm64 (Mac M1 pro)

Steps to Reproduce:

1. Start a brand new ASP.NET Core 6 project
2. Add Electron.NET
3. Run it on a Mac M1 (`electronize start /watch`)

It runs fine, but laggy since it's using an Intel process with Rosetta instead of native Apple Silicon
<img width="862" alt="image" src="https://user-images.githubusercontent.com/5941939/202825504-515419d6-6431-4fca-8790-36dd31fbafe0.png">

How do I get to run a development envinronment with Apple Silicion process instead of Intel?

**Comment by theolivenbaum** [comment]
I don't think this is yet supported as it needs integration with the Arm version of electron to work correctly
