### ISSUE TITLE
Newer versions of .NET

### ISSUE THREAD

**Issue by rushfrisby** [ElectronNET/Electron.NET#739]
Will this be recompiled using newer versions of .NET since .NET 5 is out of support?

I'm trying to build an electron app in Azure DevOps but the azure pipelines agent doesn't have .NET 5 installed by default any more. I can install it using a task before building the electron app but would rather see the package updated to a newer version of .NET.

![image](https://user-images.githubusercontent.com/574729/218833626-88246b33-2f64-482a-9c9b-2c808d7bbc20.png)

Thanks!

**Comment by DrBenvey** [comment]
Hi, have the same problem.
I tried to re-build ElectronNET.CLI from sourses for net-7.0, but it didn't worked.
https://github.com/ElectronNET/Electron.NET/issues/740

**Comment by riboyama** [comment]
I don't think this repository is maintained anymore. 
You can try [ElectronSharp](https://www.nuget.org/packages/ElectronSharp.API), which is a fork of this project based on .NET 7.

**Comment by GregorBiswanger** [comment]
The new version with .NET 7 support will be released in the next few days.

@riboyama  Why don't you make a pull request with your code?

**Comment by somasundar1997** [comment]
@GregorBiswanger Will the need for .NET 5.0 SDK to build electron app will be removed in mentioned release?

**Comment by somasundar1997** [comment]
@GregorBiswanger No... I am not asking for .NET 5.0 Support I am using .NET 6.0 Only but it asks for .NET 5.0 also. what is meant to ask was if any newer version gets released will it have/need any of the previous support for taking build.

**Comment by bangclash** [comment]
> The new version with .NET 7 support will be released in the next few days.
> 
> @riboyama Why don't you make a pull request with your code?

Great news!

**Comment by riboyama** [comment]
> The new version with .NET 7 support will be released in the next few days.
> 
> @riboyama Why don't you make a pull request with your code?

This isn't my work in any way. I was looking at this project's forks and noticed:
[This one by theolivenbaum](https://github.com/theolivenbaum/electron-sharp/)

Which is updated way more frequently...

**Comment by GregorBiswanger** [comment]
@riboyama I found a new co-developer for the project and we have a new refresh. A big update is coming in the next few weeks with some new innovations. Please just be patient.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
