### ISSUE TITLE
Application not starting with 23.6.1

### ISSUE THREAD

**Issue by jdjadav** [ElectronNET/Electron.NET#746]
Hello There,

I have upgraded my app to 23.6.1, but now it stopped working and stuck at splash screen. only splash screen opens, nothing happens after it. i see below error in terminal.
![image](https://user-images.githubusercontent.com/25253821/228236512-027ea2b0-bb50-4732-8e45-babd16f622d8.png)

also, same is happening with WebApp demo available in current Repository.

Please help.

**Comment by GregorBiswanger** [comment]
What .NET version is your application? What is your startup code for this? With threading? Are you using async-await correctly?

**Comment by jdjadav** [comment]
I am using .Net 6, and VS2022,  i am facing same in the demo application available in current repo.
it stucks at
![image](https://user-images.githubusercontent.com/25253821/228239932-b12f9d73-9de8-4034-ac20-c034738001f6.png)
with error i mentioned erlier

**Comment by GregorBiswanger** [comment]
You have downloaded the current version of the demo app and get these errors when you start it?
https://github.com/ElectronNET/electron.net-api-demos

**Comment by jdjadav** [comment]
@GregorBiswanger, i just found that i missed to update the electron cli global tool which result in error. Thank you s much for quick response. Appreciate it.

**Comment by GregorBiswanger** [comment]
Fortunately, I was already sweating ;)
