### ISSUE TITLE
Transparent window has white background

### ISSUE THREAD

**Issue by Yuvix25** [ElectronNET/Electron.NET#748]
* **Electron.NET** Version 23.6.1
* **.NET Core** Version 7.0
* **Node.js** Version 18.12
* **Target**: Windows

I have created a window like so:
```cs
var window = await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions()
{
   Resizable = false,
   Fullscreen = true,
   Minimizable = false,
   Movable = false,
   Frame = false,
   Transparent = true,
   BackgroundColor = "#00000000",
});
window.SetAlwaysOnTop(true, OnTopLevel.screenSaver);
```
Expecting the background the be transparent, but instead it is white. (The page itself only contains one `<p>` element, nothing more)
 I tried adding some delay before calling `CreateWindowAsync`, as I saw it solved the issue for some people using normal Electron, but that did not help either.

Any idea how can I fix this?

**Comment by IgorVolod** [comment]
The white background on startup was the first issue I had to deal with since my app loads in the "dark" theme by default. Try this option. My white canvas has disappeared ... completely ...

```
//electron.net - start
builder.Services.AddElectron();
builder.WebHost.UseElectron(args);
if (HybridSupport.IsElectronActive)
{
    // Open the Electron-Window here
    Task.Run(async () => {
        var window = await Electron.WindowManager.CreateWindowAsync(
           new BrowserWindowOptions
              {
               Title = "Name app",
               BackgroundColor = "#111",
               Show = false,
               AutoHideMenuBar = true,
           });
        window.Maximize();
        window.OnClosed += () =>
        {
            Electron.App.Quit();
        };
    });
}
```

**Comment by Yuvix25** [comment]
@GregorBiswanger Yes! That's it.
Your solution works perfectly 👌🏻

**Comment by FlorianRappl** [comment]
That is not (directly) possible (see https://github.com/electron/electron/issues/1335). You can, however, use one of the workarounds in the linked issue to fake this behavior.

**Comment by Yuvix25** [comment]
Ok, there are a few good solution there indeed, thanks!
However, this still does not solve keystrokes being recorded by the window. Is there something similar to `SetIgnoreMouseEvents` but for the keyboard? (`SetIgnoreKeyboardEvents` does not exist unfortunately 😅)
