### ISSUE TITLE
Linux Build doesn't run with cannot find module error

### ISSUE THREAD

**Issue by uclaitsscott** [ElectronNET/Electron.NET#75]
Uncaught Exception: Error: Cannot find module './bin/electron.manifest.json' 

Occurs after I copied linux build folder to Ubuntu and tried to run it. The error originates in the main.js when it cannot find this file (doesn't exist in linux build, nor does a bin folder). I didn't see any additional steps I'm supposed to take in the readme, but I suspect there must be something I missed.

**Comment by yoDon** [comment]
I've seen this error when the C# part of the build process reported errors but they were buried far enough up in the process that they weren't visible in the terminal so the building packaging appeared at first glance to have succeeded.

**Comment by uclaitsscott** [comment]
I was using the command line to "dotnet electronize build linux" and didn't see any errors. The windows build worked fine.

**Comment by westerncj** [comment]
I'm having the same issue on Mac. Are there any workarounds?

**Comment by ArunEdathadan** [comment]
There was a manifest error when used visual studio package manager console. but when run with visual studio code it worked.
