### ISSUE TITLE
Dev builds only run once on Windows (must reboot)

### ISSUE THREAD

**Issue by yoDon** [ElectronNET/Electron.NET#76]
Windows Fall Creators Update just installed on my machine, and now I have to reboot the machine between each attempt to run dev builds of the app.

**Comment by jcphlux** [comment]
I have this issue also. Not sure my issue is the same but to get it working I have to end task on ElectronNet that is showing in tasks.

**Comment by robertmuehsig** [comment]
Mhh.... I thought we had a similar problem on macOS as well. I'm this week quite busy, so hopefully I will find some time next week - sorry for this huge delay :/

**Comment by GregorBiswanger** [comment]
Fixed in version 0.0.9.
