### ISSUE TITLE
Test example is huge and it works slowly

### ISSUE THREAD

**Issue by nadzejam** [ElectronNET/Electron.NET#77]
I have followed instructions drom README of this project , also I’ve checked myself by watching  video instructions on YouTube.

And I have succeeded in running test example, but it runs very slowly. I have seen the note about slow first electronize start, but even next starts need about 15 seconds. Also the result of compilation contains so many library and its size is about 380MB.

I have tried a raw Electron before. And it works more quickly and its size is less.

May be I have done something wrong? Or are there any opportunities to reduce the start time and the size?

**Comment by CD1010** [comment]
I ran demo an it never started. Using vs 2017

**Comment by GregorBiswanger** [comment]
What exactly is slow? On startup or running time?

Yes, the filesize is currently bigger.. we optimize this in the next version...

**Comment by nadzejam** [comment]
The execution of command "dotnet electronize start" is slow. Both the first start and the next.

**Comment by GregorBiswanger** [comment]
Which node version do you use? Is your project with webpack?

**Comment by nadzejam** [comment]
nodejs 8.9.3
No, webpack is not used.

**Comment by srameh** [comment]
I have noticed the same behavior extremely slow start in Windows 10.
I upgraded my Node version to: v8.9.4 but still same problem.

**Comment by GregorBiswanger** [comment]
Fixed with the new Electron.NET version.
