### ISSUE TITLE
"A Javascript error occurred in the main process" when using React

### ISSUE THREAD

**Issue by Braed** [ElectronNET/Electron.NET#78]
I created a new .NET Core 2.0 Web Application and selected ReactJS during creation.

I added the NuGet package, startup, program, etc. I followed [this](https://www.youtube.com/watch?v=nuM6AojRFHk&user=BFreakout) tutorial.

Is this the correct way to use ReactJS with Electron.NET?

[Screenshot of the error.](http://prntscr.com/ho1gxj)

**Comment by GregorBiswanger** [comment]
I created a new ASP.NET Core React Project with the default VS2017 template and that works.

Which node.js version do you use? In your screenshot is the message "use as administrator".. did you try it as a admin user too?

**Comment by Braed** [comment]
I did try as Admin and the error still occurred. I'll look into it again as soon as possible and report back. I'm using node 8.9.1.

**Comment by GregorBiswanger** [comment]
The @yoDon implements a sample with Electron.NET and React.. 
You can try this one too: https://github.com/yoDon/Electron.NET-React-Typescript-MobX

**Comment by yoDon** [comment]
I find that error often means the C# build process failed with an error. There's a ton of log spew that can make the C# errors hard to spot, but it's worth looking for them in case that's the issue.

**Comment by yoDon** [comment]
Also there are undiagnosed reports of this issue on Linux builds (having nothing to do with React, they seem to be impacting all Linux builds) https://github.com/ElectronNET/Electron.NET/issues/75

**Comment by Braed** [comment]
Thank you. I'll take a look ASAP! :)
