### ISSUE TITLE
Web api in electron.net

### ISSUE THREAD

**Issue by CD1010** [ElectronNET/Electron.NET#79]
Is there a way to have angular 5 spa call a web api inside electron.net app? I want to avoid web round trip page refresh and use an existing .net codebase. No problem having .net lib emitting  json

**Comment by GregorBiswanger** [comment]
Yes, it is possible to call a web api inside the electron.net app. See the source code of a ASP.NET MVC Angular Project Sample Template (FetchDataComponent).. That works perfect in Electron.NET.. With this you´ll get the URL: 

`@Inject('BASE_URL') baseUrl: string`

In C# you can use the default IP address 0.0.0.0. and for the used Port the static BridgeSettings.SocketPort-Method from the Electron.NET API.

Could I help you?

**Comment by CD1010** [comment]
Thanks, i'll have to try that.  Javascript communication through web api seems to me the way to go to bridge C# to javascript through json.  I read other people using edge.js but sure how easy that is.

I'd be interested in any thoughts you have on the subject.

Awesome work on this, thanks.

**Comment by GregorBiswanger** [comment]
The best way in Electron.NET is the internal **IPC** communication.

Please take a look into the **Electron.NET API Demos App**:  
https://github.com/ElectronNET/electron.net-api-demos
