### ISSUE TITLE
Guidance on calling Electon APIs from Blazor server code

### ISSUE THREAD

**Issue by chrissmithptml** [ElectronNET/Electron.NET#794]
Maybe I'm just doing something wrong (which would not be the first time), but I just want to make sure.

So I have a Blazor Server app running in Electron.NET.  All Blazor stuff is fine, as are all standard javascript calls.

If I wire up calls to the Electron.NET API behind the scenes (say setting up the electron menus in my Program.cs), this all works fine.

However, when I try to call Electon APIs via a Blazor button on the server, my app not only DOESN'T do the expected Electron action, but it ends up freezing my app.

My call is pretty simple, but maybe this is just not possible / there's something else I must do to make this work

```
public async Task SomeButtonHandler() {
     var somePath = "/some/path/on/the/workstation";
     await Electron.Shell.ShowItemInFolderAsync(somePath);
} 

```

Should this work just fine?  Is there something else I need to do / some other way I need to wire this up in a Blazor Server app?  Just trying to get some confirmation.

**App Details**
Blazor app type:  Blazor server
Electon.NET Version: latest
.NET Version: 6.0x

**Comment by domingoladron** [comment]
Worked it out.  So while the code I showed above was async, when the button handler was generated, it was a void and the actual call was 

```
Electron.Shell.ShowItemInFolderAsync(somePath).Wait();
```

This, apparently, is a big ol' no-no.  Does not work.   Wait() and .Result got me the same pain and suffering.  Only allowing the Electron async methods to run naturally appears to work consistently.

Live and learn.

**Comment by chrissmithptml** [comment]
Worked it out, in case anyone else bumps up against this kind of thing.

My button method was a void, and my call to Electron used a `.Wait()`.  That and `.Result` are a big ol' no-no.  They do NOT work.  You have to ensure the Electron Shell calls are full on await async calls or they don't work.
