### ISSUE TITLE
dotnet electronize build doesn't build resizable app and bug in "put your app in the tray section" in the demo app

### ISSUE THREAD

**Issue by YoussefRekik** [ElectronNET/Electron.NET#80]
when using "dotnet electronize start" I get a resizable size screen and adaptive resolution but when building using "dotnet electronize build" I get small static size website and no way to resize it.
Also in the demo application in ''put your app in the tray section" I get an error when using the Demo button:
"Uncaught Exception:
type Error: Error processing argument at index 0, conversion failure from PATH\electron_32x32.png 
at socket.<anonymous>
at emitTwo (events.js:106:13)
et Socket.emit (events.js:194:7)
.......................
"
I am on Windows 7 by the way.

**Comment by GregorBiswanger** [comment]
I tried it on my Windows 10 and the resizable screen works on start and debug.. The same with the tray icon.. Can you start the Electron API Demo App and start in Visual Studio 2017 the Debug please?

Go in the **Debug** Menu and click on **Attach to Process....** Sort by **ElectronNET-API-Demos.exe** on the right and select it on the list...

**Comment by yoDon** [comment]
Looking at the path loading error, I'm wondering if this is another symptom of the https://github.com/ElectronNET/Electron.NET/issues/70 bug where dev and production builds copy files listed in the .csproj to different locations

**Comment by srameh** [comment]
I get the same error when trying the "put your app in the tray section"
I am using Windows 10 64bit.

**Comment by YoussefRekik** [comment]
Sorry for being away for so much time, turned out that the company Proxy prevents Bootstrap and jQuery from Loading.
