### ISSUE TITLE
Breakpointing Angular

### ISSUE THREAD

**Issue by thomasfrisko** [ElectronNET/Electron.NET#81]
Hey,

I have been trying to set up an Electron.NET project with Angular in Visual Studio. I followed your documentation which enables me to breakpoint the parts within .NET Core, however, I am unable to breakpoint the parts in Angular where I get the message "The breakpoint will currently not be hit. No symbols have been loaded for this document". 
Is there any way I can breakpoint the angular code?

**Comment by yoDon** [comment]
If you're referring to the Angular javascript code, that code you could breakpoint in the embedded browser using its integrated developer tools (it should be possible to connect visual studio's javascript debugging or VS Code's javascript debugging to the electron developer tools but I don't think anyone has reported doing that yet)
