### ISSUE TITLE
Allow electronize build to publish as release and not always as debug

### ISSUE THREAD

**Issue by ErenForce** [ElectronNET/Electron.NET#84]
By default the command `dotnet publish` uses the debug configuration unless it was told to use release using the syntax `-c|--configuration {Debug|Release}`. An option for the configuration should be added to the command `dotnet electronize build`. Some more in depth argument parsing should be used to support things like using `dotnet electronize build -c Release -r win` or `dotnet electronize build -r win -c release`

**Comment by robertmuehsig** [comment]
Good idea! Will take a look at it. Note to myself:
Currently we don't specify any configuration - see [here](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.CLI/Commands/BuildCommand.cs#L52)

**Comment by AirLancer** [comment]
Are you open for some help on this?
If you have a specific solution or implementation in mind I'd work it in.

**Comment by robertmuehsig** [comment]
I hope to fix it in this week.

**Comment by robertmuehsig** [comment]
Fixed with 0.0.9 - the default now is release, but the build-command accepts a new argument called /dotnet-configuration with debug or release or whatever you want.
