### ISSUE TITLE
build.cmd doesn't produce nuget packages

### ISSUE THREAD

**Issue by nazar322** [ElectronNET/Electron.NET#843]
* **Version**: 23.6.2

* **Target**: 

Steps to Reproduce:

The wiki states `Both projects create their own nuget package. The resulting nuget packages are saved under "/artifacts".`
After `build.cmd` completes I don't get any files in the `artifacts` folder.

The story is that I'm trying to ping-point issue I posted here https://github.com/ElectronNET/Electron.NET/issues/842
So I've added handlers for `apiProcess's` `uncaughtException` and `unhandledRejection`. 
I also want to add `render-process-gone` listener.

The problem is I want to replace electron.net's nuget files inside `%userprofile%/.dotnet` and `%userprofile%/.nuget`  with the files containing my changes but I cannot do it since nuget files missing in the artifacts folder. For instance, the plain build does not create `electronize.exe` executable of the CLI project.

**Comment by gorsheninmv** [comment]
What command do you use to create packages?
Checked right now and the command `build.cmd --target createpackages` produces packages under the `artifacts` directory.
