### ISSUE TITLE
build for certain platform  trouble

### ISSUE THREAD

**Issue by jbryant32** [ElectronNET/Electron.NET#86]
any idea how i can set the  build to a windows x86 compatible exe ?

**Comment by robertmuehsig** [comment]
We are now producing just x64 exes, right? I guess our Build-Command needs some more options. I will try to work on it soon.

**Comment by jbryant32** [comment]
Ok i was trying to adjust the settings the builder json but did not work

**Comment by robertmuehsig** [comment]
We released a new version and now support addional params like this (for a x86 application)
build /target custom win7-x86;win32 /electron-arch ia32  

Please update the CLI to version 0.0.9

If this doesn't work, please give feedback. Thanks!
