### ISSUE TITLE
No pull requests accepted in 2 months - is project still live?

### ISSUE THREAD

**Issue by yoDon** [ElectronNET/Electron.NET#87]
Electron.NET is an incredibly exciting project. As expected for an alpha- or pre-alpha project, it has serious and entirely expected new-project teething pains. Electron.NET is a cross-platform toolkit that doesn't yet work across platforms, it's a developer tool that doesn't yet work in debug mode, and it has a large and rapidly growing community of developers rallying around it and trying to use it.

But it has not accepted a PR in over two months. These aren't complex and subtle PR's that require tens of maintainer hours just to assess that are waiting to be accepted. These are minor tweaks to Readme's.

I've been [a huge fan of Electron.NET](https://github.com/yoDon/Electron.NET-React-Typescript-MobX), I remain a huge fan of Electron.NET, but if the maintainers refuse to accept PR's or can't invest the time to accept even the most trivial of PR's, we need to ask is this project still live?

I don't want to do this, but I have to start porting the projects I started on Electron.NET away from Electron.NET. That makes me profoundly sad. Electron.NET is a brilliant project. It is how I want to develop my applications. But there is no point in me or anyone else trying to fix the issues Electron.NET faces if no PR's are being accepted and no maintainer commits are happening either.

Two months with no PR accepts and no maintainer commits is a long time. Too long. Spending time tagging issues as "bug" or "feature" and "assigning" maintainers to them doesn't fix issues and isn't a solution to anything.

Is this project still live?

Is there a plan in place to allow it to succeed?

**Comment by robertmuehsig** [comment]
This will be just a short answer (I will write a longer answer when I'm at home) : The project is still more or less an experiment for us and you are completely right - we were quite lazy during the last months. I will check the open bugs and talk with @GregorBiswanger about the future of Electron.NET.

I really admire your energy 👍 

(and shame on us that we didn't accept typo PRs :/ )

**Comment by robertmuehsig** [comment]
As I already mentioned: From my point of view Electron.NET is still a expermient. It's working more or less, but there are still some [fundamental challenges](https://github.com/ElectronNET/Electron.NET/issues/22) which I see as a problem, but I don't know how to solve it.

What I try to do is to enhance the CLI project - there are a couple of bugs/feature requests to overwrite the generated application name or application arch and this would be my next ToDo and would hopefully resolve a hand full of issues.

There are still some other big issues open, like the zombie process on macOS. My guess is, that those will be harder to tackle, but if you have some good ideas: PRs are welcome 👍

**Comment by pardahlman** [comment]
Thanks for the update @robertmuehsig. I'd love to see this project evolve. If there are any "good first issues" in the near future, I'd be happy to help in some capacity!

**Comment by robertmuehsig** [comment]
@pardahlman Well - we have some trouble with the Mac. The main problem is: I have a Mac, but my electron knowledge is pretty low. If you are a Mac/Electron person this would be huge 👍 

We released a newer version: 0.0.9. Check the changelog please.

I will close this issue. We are very aware of the fact that the project is running super slow, but currently we do it as "fast" as possible. We love contributions - so, feel free to comment or send PRs :)
