### ISSUE TITLE
The process tried to write to a nonexistent pipe.

### ISSUE THREAD

**Issue by CD1010** [ElectronNET/Electron.NET#88]
I am getting the above error when i try to run electronnet on a win10 machine.
It does this for a bare bones electron.net app based in instructions in readme.
I have v2 2017 with latest patch and 
node 8.9.4 lts installed.  Any ideas?  
After i get this, it hangs and i get zombie electron.exe processes

Update: i am getting prompt from windows firewall when this happens. I click allow private and public networks. I run again but still get zombie electron.exe instances and no ui pops up.

**Comment by robertmuehsig** [comment]
Mhh... just a stupid thought: Have you saved your repository on a path with some special characters? Maybe we can't find the right path to the assembly.
Another thought: Could you kill all zombie processes and try it again?

**Comment by CD1010** [comment]
D:\docs\SourceCode\ElectricPortfolio\ElectricPortfolio
that is path
I killed zombies but they come back when i run again.

**Comment by GregorBiswanger** [comment]
Hi @CD1010 
do you tried the new 0.0.9 Version?
