### ISSUE TITLE
Appveyor Build status failing

### ISSUE THREAD

**Issue by GregorBiswanger** [ElectronNET/Electron.NET#9]
The appveyor Build status failing

**Comment by robertmuehsig** [comment]
'cause of this https://github.com/ElectronNET/Electron.NET/issues/7

**Comment by robertmuehsig** [comment]
real cause: electron darwin build uses symlinks, which can't be zipped (IDK...)

Another one described the issue here: http://help.appveyor.com/discussions/problems/6967-access-is-denied-when-zipping-files

maybe OSX and Linux builds should run on a linux vm (which appveyor may provide...)

**Comment by robertmuehsig** [comment]
OSX/Linux Builds doint on Travis CI: https://travis-ci.org/ElectronNET/Electron.NET 

WIP!

**Comment by robertmuehsig** [comment]
Fixed. 
Travis CI builds win/osx/linux
Appveyor builds win/linux - osx build has a bug on Windows :/
