### ISSUE TITLE
How to Debug the js file 

### ISSUE THREAD

**Issue by lyy0808** [ElectronNET/Electron.NET#90]
In my project ,i feel my js file bring some erro ,but i can't debug withd the vs2017,and the chrome debug is also don't work. Tell me some help .I think is a  important tools.Thanks

**Comment by robertmuehsig** [comment]
@GregorBiswanger ?

**Comment by GregorBiswanger** [comment]
Hi lyy0808,
use the **Chrome Developer Tools** direct from the Electron.NET App.

You can open this via code with:
`Electron.WindowManager.BrowserWindows.First().WebContents.OpenDevTools()`

Documentation for debugging with the Chrome Developer Tools:
https://developers.google.com/web/tools/chrome-devtools/javascript/

I hope my answer helps you.

**Comment by lyy0808** [comment]
Thank you ,it's ok

**Comment by jadhavrani123** [comment]
@GregorBiswanger  sir I want to close my developer tool on click cntrl + shift + I

**Comment by jadhavrani123** [comment]
WebPreferences = new WebPreferences
                        {
                            DevTools = false
                        }
I am use this code........but it not work for me

**Comment by jadhavrani123** [comment]
My editor is Visual studio 2019 with Angular fronted
At the time exe package create 3 folder local , swiftshader , resources but in resources folder bin folder is create how to remove it??
