### ISSUE TITLE
ipcmain listener miss

### ISSUE THREAD

**Issue by mojinxun** [ElectronNET/Electron.NET#92]
I have a question:
 when my app use a long time, all of my listener missing...
front can receive “send”
but in netcore can't receive "front" "send" 

please help me..

**Comment by GregorBiswanger** [comment]
Hi @mojinxun 
do you tried the new version 0.0.9?

**Comment by ocelikk** [comment]
@GregorBiswanger im facing same issue too. 
-behind in c# -
   Electron.IpcMain.On("async-msg", (data) =>
                {
                    var mainWindow = Electron.WindowManager.BrowserWindows.First();
                        Electron.IpcMain.Send(mainWindow, "async-msg-reply", "asdf");
                });
-behind in c# -

this code block triggers when app is just started but after a while however dont hit anymore.

**Comment by GregorBiswanger** [comment]
Fixed with the new Electron.NET version.
