### ISSUE TITLE
Starting application hangs

### ISSUE THREAD

**Issue by uveta** [ElectronNET/Electron.NET#98]
I ran into an issue where trying to run my project under Electron.NET seems to hang indefinitely. When I was experimenting with Electron.NET on one machine everything worked fine, however when I moved the working project code to another computer the application refuses to start. When I try to  run it via _dotnet electronize start_  the process hangs and output is the following

> Start Electron Desktop Application...

When I am attempting a build via _dotnet electronize build_ win it hangs as well with output

> Build Electron Application...
> Executing dotnet publish in this directory: ...
> Build ASP.NET Core App for win-x64...

Both machines have the same version of Windows (1709), .NET Core SDK (2.1.4) and Node.JS (8.9.4)

**Comment by sebi5000** [comment]
I have the same issue on my dev PC with Win10. Tried your example code from Readme with react Template in Visual-Studio. But without success, same problem as described by uveta.

**Comment by GregorBiswanger** [comment]
Hi @uveta, @sebi5000,
did you try the latest version of API and CLI 0.0.9?
Clear the project please and try again. 

**Important**, if you close the "start" process, check if the electron process is actually closed in the background.
